// Sky Runtime — modules copied into generated projects at build time.
// Builder.hs emits `mod sky_runtime; use sky_runtime::*;` instead of
// duplicating these definitions inline.
//
// config.rs is GENERATED by the Sky compiler at build time.
// core.rs is always included.

pub mod config;  // GENERATED at Sky build time
pub mod core;    // always included

pub use config::*;
pub use core::*;
