// Sky Runtime — modules copied into generated projects at build time.
// Builder.hs emits `mod sky_runtime; use sky_runtime::*;` instead of
// duplicating these definitions inline.
//
// config.rs is GENERATED by the Sky compiler at build time (contains
// SkyError type alias, str_err helper, DB pool types, etc.)
// core.rs and db.rs are shipped with the compiler and copied verbatim.

pub mod config;  // GENERATED at Sky build time
pub mod core;    // always included
pub mod db;      // included when user imports Std.Db

pub use config::*;
pub use core::*;
