//! sky-ffi-inspect-rs — Rust crate inspector for Sky FFI bindings.
//!
//! Uses `cargo +nightly rustdoc --output-format json` to introspect crate
//! public APIs.  Crucially, rustdoc runs *after* macro expansion, so items
//! generated by proc macros and derive macros that are invisible to
//! source-level parsers (syn) are fully visible here.
//!
//! Output JSON matches the `PkgInfo` schema that FfiGen.hs consumes.
//! The output contract is unchanged from v0.1 — only the inspection
//! backend changed.
//!
//! Usage:
//!   sky-ffi-inspect-rs uuid                          # single crate
//!   sky-ffi-inspect-rs uuid chrono                   # multi → JSON array
//!   sky-ffi-inspect-rs --features v4 uuid            # with features

use serde::Serialize;
use std::collections::{HashMap, HashSet};
use std::path::PathBuf;
use std::process::Command;

// ── Output schema (FfiGen.hs PkgInfo) ─────────────────────────────────

#[derive(Serialize, Debug)]
#[serde(rename_all = "camelCase")]
struct Param {
    name: String,
    #[serde(rename = "type")]
    ty: String,
    #[serde(skip_serializing_if = "String::is_empty")]
    sky_type: String,
    #[serde(skip_serializing_if = "String::is_empty")]
    rust_type: String,
}

#[derive(Serialize, Debug)]
#[serde(rename_all = "camelCase")]
struct Function {
    name: String,
    params: Vec<Param>,
    results: Vec<Param>,
    variadic: bool,
    effect: String,
    exported: bool,
    #[serde(skip_serializing_if = "String::is_empty")]
    recv_type: String,
    #[serde(skip_serializing_if = "String::is_empty")]
    recv_rust_type: String,
    #[serde(skip_serializing_if = "String::is_empty")]
    method_name: String,
    #[serde(skip_serializing_if = "std::ops::Not::not")]
    is_field: bool,
    #[serde(skip_serializing_if = "std::ops::Not::not")]
    is_field_set: bool,
    #[serde(skip_serializing_if = "std::ops::Not::not")]
    is_pkg_var: bool,
}

#[derive(Serialize, Debug)]
#[serde(rename_all = "camelCase")]
struct PkgInfo {
    pkg: String,
    name: String,
    #[serde(skip_serializing_if = "String::is_empty")]
    version: String,
    functions: Vec<Function>,
    // Full `::`-paths of every PUBLIC module in the crate (e.g.
    // "chrono::format").  FfiGen glob-imports each (`use <mod>::*;`) so that
    // types re-exported only in submodules resolve by their bare name in the
    // generated wrappers.
    #[serde(skip_serializing_if = "Vec::is_empty")]
    modules: Vec<String>,
    errors: Vec<String>,
}

// ── Entry point ────────────────────────────────────────────────────────

fn main() {
    let raw_args: Vec<String> = std::env::args().skip(1).collect();

    let mut features: Vec<String> = Vec::new();
    let mut crate_args: Vec<String> = Vec::new();

    let mut i = 0;
    while i < raw_args.len() {
        if raw_args[i] == "--features" {
            i += 1;
            if i < raw_args.len() {
                for feat in raw_args[i].split(',') {
                    let f = feat.trim().to_string();
                    if !f.is_empty() {
                        features.push(f);
                    }
                }
            }
        } else {
            crate_args.push(raw_args[i].clone());
        }
        i += 1;
    }

    if crate_args.is_empty() {
        eprintln!("Usage: sky-ffi-inspect-rs [--features f1,f2] <crate-name> [crate-name...]");
        eprintln!();
        eprintln!("Requires nightly Rust: rustup toolchain install nightly");
        std::process::exit(1);
    }

    let results: Vec<PkgInfo> = crate_args
        .iter()
        .map(|name| inspect_crate(name, &features))
        .collect();

    let json = if crate_args.len() == 1 {
        serde_json::to_string_pretty(&results[0])
    } else {
        serde_json::to_string_pretty(&results)
    };

    match json {
        Ok(s) => println!("{}", s),
        Err(e) => {
            let err = PkgInfo {
                pkg: crate_args.join(" "),
                name: "error".into(),
                version: String::new(),
                functions: vec![],
                modules: vec![],
                errors: vec![format!("JSON serialization failed: {}", e)],
            };
            println!("{}", serde_json::to_string_pretty(&err).unwrap());
        }
    }
}

// ── Top-level inspection ───────────────────────────────────────────────

fn inspect_crate(crate_name: &str, features: &[String]) -> PkgInfo {
    match run_rustdoc(crate_name, features) {
        Ok((json_content, version)) => match serde_json::from_str::<serde_json::Value>(&json_content) {
            Ok(doc) => parse_rustdoc(&doc, crate_name, &version),
            Err(e) => pkg_error(crate_name, &format!("rustdoc JSON parse error: {}", e)),
        },
        Err(e) => pkg_error(crate_name, &e),
    }
}

/// Create a temporary Cargo project that depends on `crate_name`, run
/// `cargo +nightly rustdoc` with JSON output, and return the raw JSON
/// and the resolved crate version.
///
/// Handles thin re-export facades (e.g. `clap` re-exports `clap_builder`):
/// if the first rustdoc run produces 0 functions, we scan the JSON for glob
/// `pub use other_crate::*` re-exports and re-run on the underlying crate.
fn run_rustdoc(crate_name: &str, features: &[String]) -> Result<(String, String), String> {
    let tmp = tempfile::tempdir().map_err(|e| format!("tempdir: {}", e))?;
    let dir = tmp.path();

    let safe_name = crate_name.replace('-', "_");
    let dep_entry = build_dep_entry(crate_name, features);

    let toml_content = format!(
        r#"[package]
name = "_sky_ffi_probe_{safe_name}"
version = "0.1.0"
edition = "2021"

[dependencies]
{dep_entry}
"#
    );

    let src_dir = dir.join("src");
    std::fs::create_dir_all(&src_dir).map_err(|e| format!("mkdir src: {}", e))?;
    std::fs::write(dir.join("Cargo.toml"), &toml_content)
        .map_err(|e| format!("write Cargo.toml: {}", e))?;
    std::fs::write(src_dir.join("lib.rs"), "// placeholder\n")
        .map_err(|e| format!("write lib.rs: {}", e))?;

    let manifest_str = dir.join("Cargo.toml").to_string_lossy().to_string();
    let target_dir = dir.join("target");

    // Fetch first (uses cargo cache — fast on repeated calls)
    fetch_dep(&manifest_str)?;

    let (json_content, version) =
        run_rustdoc_package(crate_name, &manifest_str, &target_dir, &safe_name)?;

    // If 0 public functions were found, the crate may be a thin re-export
    // facade (e.g. `clap` is just `pub use clap_builder::*`).  Detect glob
    // re-exports in the JSON and re-run on the underlying crate.
    let has_fns = json_has_functions(&json_content);
    if !has_fns {
        if let Some(underlying) = find_glob_reexport_source(&json_content) {
            let under_safe = underlying.replace('-', "_");
            if let Ok((under_json, under_ver)) =
                run_rustdoc_package(&underlying, &manifest_str, &target_dir, &under_safe)
            {
                if json_has_functions(&under_json) {
                    return Ok((under_json, under_ver));
                }
            }
        }
    }

    Ok((json_content, version))
}

/// Run `cargo +nightly rustdoc --package pkg` and return the JSON content.
fn run_rustdoc_package(
    package_name: &str,
    manifest_str: &str,
    target_dir: &PathBuf,
    safe_name: &str,
) -> Result<(String, String), String> {
    let output = Command::new("cargo")
        .args([
            "+nightly",
            "rustdoc",
            "--package",
            package_name,
            "--lib",          // pin to library target; avoids "extra arguments"
                              // errors on crates with binary or example targets.
            "--manifest-path",
            manifest_str,
            "--target-dir",
            target_dir.to_str().unwrap(),
            "--quiet",
            "--",
            "--output-format",
            "json",
            "-Z",
            "unstable-options",
        ])
        .output()
        .map_err(|e| {
            format!(
                "cargo +nightly rustdoc failed: {}.\n\
                 Is nightly installed? Run: rustup toolchain install nightly",
                e
            )
        })?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr).to_string();
        if stderr.contains("toolchain") && stderr.contains("not installed") {
            return Err(format!(
                "nightly toolchain not found. Install it with:\n  rustup toolchain install nightly\n\n{}",
                stderr
            ));
        }
        return Err(format!("cargo rustdoc failed:\n{}", stderr));
    }

    // Locate the JSON file under target/doc/
    let doc_dir = target_dir.join("doc");
    let json_path = find_rustdoc_json(&doc_dir, safe_name).ok_or_else(|| {
        format!(
            "rustdoc JSON not found in {}. Expected {}.json",
            doc_dir.display(),
            safe_name
        )
    })?;

    let content = std::fs::read_to_string(&json_path)
        .map_err(|e| format!("read {}: {}", json_path.display(), e))?;
    let version = extract_crate_version(&content).unwrap_or_default();

    Ok((content, version))
}

/// Return true if the rustdoc JSON contains at least one public function.
fn json_has_functions(json: &str) -> bool {
    if let Ok(doc) = serde_json::from_str::<serde_json::Value>(json) {
        if let Some(index) = doc["index"].as_object() {
            return index.values().any(|item| {
                item.get("inner")
                    .and_then(|i| i.get("function"))
                    .is_some()
            });
        }
    }
    false
}

/// Scan the rustdoc JSON index for a glob re-export (`pub use other_crate::*`)
/// and return the source crate name.  Used to follow thin re-export facades.
fn find_glob_reexport_source(json: &str) -> Option<String> {
    let doc: serde_json::Value = serde_json::from_str(json).ok()?;
    let index = doc["index"].as_object()?;
    for item in index.values() {
        if let Some(use_inner) = item.get("inner").and_then(|i| i.get("use")) {
            if use_inner["is_glob"].as_bool().unwrap_or(false) {
                if let Some(src) = use_inner["source"].as_str() {
                    // Skip stdlib-style re-exports (e.g. re-exporting from std::)
                    if !src.starts_with("std") && !src.starts_with("core")
                        && !src.starts_with("alloc")
                    {
                        return Some(src.to_string());
                    }
                }
            }
        }
    }
    None
}

fn find_rustdoc_json(doc_dir: &PathBuf, safe_name: &str) -> Option<PathBuf> {
    // Direct match first
    let direct = doc_dir.join(format!("{}.json", safe_name));
    if direct.exists() {
        return Some(direct);
    }
    // Scan directory for any .json file (handles edge cases in crate name casing)
    if let Ok(entries) = std::fs::read_dir(doc_dir) {
        for entry in entries.flatten() {
            let name = entry.file_name();
            let n = name.to_string_lossy();
            if n.ends_with(".json") && !n.starts_with('_') {
                return Some(entry.path());
            }
        }
    }
    None
}

fn fetch_dep(manifest_str: &str) -> Result<(), String> {
    // Offline first (cache hit, fast)
    if let Ok(o) = Command::new("cargo")
        .args(["fetch", "--offline", "--manifest-path", manifest_str])
        .output()
    {
        if o.status.success() {
            return Ok(());
        }
    }
    // Fall back to network
    let o = Command::new("cargo")
        .args(["fetch", "--manifest-path", manifest_str])
        .output()
        .map_err(|e| format!("cargo fetch: {}", e))?;
    if o.status.success() {
        Ok(())
    } else {
        Err(format!(
            "cargo fetch failed: {}",
            String::from_utf8_lossy(&o.stderr)
        ))
    }
}

fn build_dep_entry(crate_name: &str, features: &[String]) -> String {
    if features.is_empty() {
        format!("{} = \"*\"", crate_name)
    } else {
        let feats = features
            .iter()
            .map(|f| format!("\"{}\"", f))
            .collect::<Vec<_>>()
            .join(", ");
        format!(
            "{} = {{ version = \"*\", features = [{}] }}",
            crate_name, feats
        )
    }
}

fn extract_crate_version(json: &str) -> Option<String> {
    let doc: serde_json::Value = serde_json::from_str(json).ok()?;
    doc["crate_version"].as_str().map(|s| s.to_string())
}

// ── Parse rustdoc JSON → PkgInfo ───────────────────────────────────────

fn parse_rustdoc(doc: &serde_json::Value, crate_name: &str, version: &str) -> PkgInfo {
    // Make the crate-local public-path map available to
    // rustdoc_type_to_rust_str so it can fully-qualify opaque types.  Must be
    // set BEFORE any function is parsed (parse_fn_item -> rust_str reads it).
    REACHABLE_PATHS.with(|c| *c.borrow_mut() = collect_reachable_paths(doc));
    ALIAS_MAP.with(|c| *c.borrow_mut() = collect_aliases(doc));

    let index = match doc["index"].as_object() {
        Some(idx) => idx,
        None => return pkg_error(crate_name, "rustdoc JSON missing 'index' field"),
    };

    let aliases: HashMap<String, String> = HashMap::new();
    let mut functions: Vec<Function> = Vec::new();
    // Maps Sky type name → full Rust type string (may include generic params).
    // Used by emit_display_fromstr_bridges to carry the concrete Rust type
    // through to FfiGen so it can detect generic receivers and emit
    // `impl Display` / `impl FromStr` bounds rather than bare type names.
    let mut display_types: HashMap<String, String> = HashMap::new();
    let mut fromstr_types: HashMap<String, String> = HashMap::new();
    let mut errors: Vec<String> = Vec::new();

    // First pass: collect the IDs of every item that belongs to an impl or
    // trait `items` list — i.e. every associated function / method.  In the
    // flat rustdoc index, an associated function (e.g. `NaiveDate::from_ymd`)
    // appears BOTH as a standalone `function` item AND inside the owning
    // impl's `items` list.  Emitting the standalone copy as a free function
    // would generate a bogus `crate::from_ymd(..)` call that doesn't exist.
    // We skip the standalone copy here; the impl-block walk below emits the
    // correct receiver-tagged variant (`NaiveDate::from_ymd` / `arg0.method`).
    let mut associated_ids: HashSet<String> = HashSet::new();
    for (_, item) in index {
        let inner = &item["inner"];
        for kind in ["impl", "trait"] {
            if let Some(block) = inner.get(kind) {
                if let Some(items) = block.get("items").and_then(|i| i.as_array()) {
                    for mid in items {
                        associated_ids.insert(item_id_to_str(mid));
                    }
                }
            }
        }
    }

    for (item_id, item) in index {
        // Only items from this crate (crate_id == 0); deps have crate_id > 0
        let crate_id = item["crate_id"].as_u64().unwrap_or(1);
        if crate_id != 0 {
            continue;
        }

        let name = item["name"].as_str().unwrap_or("").to_string();
        let inner = &item["inner"];

        // Free function — must be public AND not an associated item of an
        // impl/trait (those are handled by the impl-block walk with a receiver).
        if let Some(fn_data) = inner.get("function") {
            if is_public(item) && !associated_ids.contains(item_id.as_str()) {
                if let Some(f) = parse_fn_item(&name, fn_data, &aliases, None) {
                    functions.push(f);
                }
            }
        }

        // Impl block — includes derive-generated trait impls.
        // Impl blocks always have visibility "default" (they don't have their
        // own visibility in Rust — it's inherited from the type), so we must
        // NOT filter by is_public() here.
        // The self type is under "for" (NOT "for_") in the rustdoc JSON.
        if let Some(impl_data) = inner.get("impl") {
            // "for" is a Rust keyword but JSON keys can be anything.
            let for_val = impl_data.get("for").or_else(|| impl_data.get("for_"));
            let self_sky = for_val
                .map(|v| rustdoc_type_to_sky(v, &aliases))
                .unwrap_or_default();
            let self_rust = for_val
                .map(|v| rustdoc_type_to_rust_str(v))
                .unwrap_or_default();

            if self_sky.is_empty() {
                continue;
            }

            // Track Display / FromStr for synthetic bridge functions
            let trait_name = impl_data
                .get("trait")
                .and_then(|t| t.as_object())
                .and_then(|t| t.get("name").or_else(|| t.get("path")))
                .and_then(|n| n.as_str())
                .unwrap_or("");
            if trait_name == "Display" || trait_name.ends_with("::Display") {
                // key = Sky type name; value = full Rust type (may have generics)
                display_types.entry(self_sky.clone()).or_insert_with(|| self_rust.clone());
            }
            if trait_name == "FromStr" || trait_name.ends_with("::FromStr") {
                fromstr_types.entry(self_sky.clone()).or_insert_with(|| self_rust.clone());
            }

            // Walk method items.
            // Item IDs may be integers (new format) or strings (old format).
            if let Some(items) = impl_data["items"].as_array() {
                for method_id in items {
                    let id = item_id_to_str(method_id);
                    if let Some(method_item) = index.get(&id) {
                        if !is_public(method_item) {
                            continue;
                        }
                        let method_name = method_item["name"].as_str().unwrap_or("");
                        if let Some(fn_data) = method_item["inner"].get("function") {
                            if let Some(f) =
                                parse_fn_item(method_name, fn_data, &aliases, Some((&self_sky, &self_rust)))
                            {
                                functions.push(f);
                            }
                        }
                    }
                }
            }
        }
    }

    // Synthetic to_string / from_string bridge functions (Display/FromStr)
    emit_display_fromstr_bridges(&mut functions, &display_types, &fromstr_types);

    // Drop functions whose param/result/receiver types can't be named in the
    // generated wrapper: impl-level generics (`Tz`), private crate types, and
    // external types whose canonical path runs through a private module.  After
    // qualification, a reachable type appears as `crate::Path::Type`; anything
    // still bare-and-unknown is unresolved.  `to_string` bridges are exempt —
    // FfiGen emits them with an `impl std::fmt::Display` bound and never spells
    // the receiver type.
    functions.retain(|f| f.method_name == "to_string" || fn_types_nameable(f));

    if functions.is_empty() && !errors.is_empty() {
        // surface errors visibly
        errors.insert(0, format!("{}: 0 functions extracted", crate_name));
    }

    PkgInfo {
        pkg: crate_name.to_string(),
        name: crate_name.to_string(),
        version: version.to_string(),
        functions,
        modules: collect_public_modules(doc),
        errors,
    }
}

/// Collect the `::`-joined paths of every PUBLIC module defined in this crate
/// (crate_id == 0).  FfiGen glob-imports each so that types re-exported only
/// inside a submodule (e.g. `chrono::format::ParseErrorKind`) resolve by their
/// bare name in the generated wrappers.  Private modules are excluded — they
/// can't be `use`d — and so are crates' synthetic/hidden internals.
fn collect_public_modules(doc: &serde_json::Value) -> Vec<String> {
    let index = match doc["index"].as_object() {
        Some(i) => i,
        None => return vec![],
    };
    let paths = doc["paths"].as_object();
    let mut mods: Vec<String> = Vec::new();
    for (id, item) in index {
        let inner = &item["inner"];
        if inner.get("module").is_some()
            && item["crate_id"].as_u64().unwrap_or(1) == 0
            && is_public(item)
        {
            if let Some(segs) = paths
                .and_then(|m| m.get(id))
                .and_then(|e| e.get("path"))
                .and_then(|p| p.as_array())
            {
                let joined: Vec<String> = segs
                    .iter()
                    .filter_map(|s| s.as_str().map(String::from))
                    .collect();
                if !joined.is_empty() {
                    mods.push(joined.join("::"));
                }
            }
        }
    }
    mods.sort();
    mods.dedup();
    mods
}

fn is_public(item: &serde_json::Value) -> bool {
    item["visibility"].as_str() == Some("public")
}

/// Parse a function item from the rustdoc JSON index.
///
/// `recv` is `Some((sky_type, rust_type))` for methods, `None` for free fns.
fn parse_fn_item(
    name: &str,
    fn_data: &serde_json::Value,
    aliases: &HashMap<String, String>,
    recv: Option<(&str, &str)>,
) -> Option<Function> {
    // Signature is under "sig" (format v38+) or "decl" (earlier).
    let sig = fn_data.get("sig").or_else(|| fn_data.get("decl"))?;

    let inputs = sig["inputs"].as_array()?;
    let output = &sig["output"];

    let is_async = fn_data["header"]["is_async"].as_bool().unwrap_or(false)
        || fn_data["header"]["async_"].as_bool().unwrap_or(false);

    // Skip `unsafe fn`: the generated wrapper calls it outside an `unsafe`
    // block, and auto-exposing unsafe constructors (e.g. new_unchecked) to
    // Sky would bypass the very invariants `unsafe` exists to protect.
    let is_unsafe = fn_data["header"]["is_unsafe"].as_bool().unwrap_or(false)
        || fn_data["header"]["unsafe_"].as_bool().unwrap_or(false);
    if is_unsafe {
        return None;
    }

    // Monomorphise-on-demand (Alt-1): resolve each generic param's bound to a
    // concrete Sky-representable type. `None` => unresolvable => drop the fn,
    // exactly as the old wholesale skip did, but now only when we genuinely
    // cannot pick a sound concrete type.
    let subst_map = resolve_generics(fn_data)?;

    // Drop if any `impl Trait` arg/return can't be soundly monomorphised.
    if !sig["inputs"].as_array().map(|ins| ins.iter().all(impl_traits_resolvable)).unwrap_or(true)
        || !impl_traits_resolvable(output)
    {
        return None;
    }

    let mut params: Vec<Param> = Vec::new();

    // Determine if this is an instance method by checking whether `self`
    // appears as the first entry in sig["inputs"].  Associated (static)
    // functions don't have a self input even though they live in an impl block.
    let has_self_in_inputs = inputs
        .first()
        .and_then(|i| i[0].as_str())
        .map(|n| n == "self")
        .unwrap_or(false);

    // For instance methods: push the receiver as first param so FfiGen
    // can generate `arg0.method(rest...)`.  For static/associated functions
    // in an impl block (recv.is_some() but no self input): don't push a
    // receiver param — FfiGen will use `RecvType::fn(args)` via isStaticFn.
    if let Some((sky_ty, rust_ty)) = recv {
        if has_self_in_inputs {
            params.push(Param {
                name: "self".into(),
                ty: sky_ty.to_string(),
                sky_type: sky_ty.to_string(),
                rust_type: rust_ty.to_string(),
            });
        }
    }

    // Ordinary parameters: inputs is [(name, type_json)].
    // Skip the "self" entry — it is already accounted for by the receiver
    // push above (instance method) or is not needed (static method).
    for input in inputs {
        let param_name = input[0].as_str().unwrap_or("_");
        if param_name == "self" {
            continue;
        }
        let type_json = subst_generic_json(&input[1], &subst_map);
        let sky = rustdoc_type_to_sky(&type_json, aliases);
        let rust = rustdoc_type_to_rust_str(&type_json);
        // `Self` in a parameter position means "the receiver type" (e.g.
        // `fn signed_duration_since(self, rhs: Self)`, or nested as
        // `Option<Self>`).  `Self` is not valid in a free-function signature,
        // so substitute the concrete receiver type token throughout.
        let (rsky, rrust) = recv.unwrap_or(("", ""));
        let sky = subst_self(&sky, rsky);
        let rust = subst_self(&rust, rrust);
        params.push(Param {
            name: param_name.to_string(),
            ty: sky.clone(),
            sky_type: sky,
            rust_type: rust,
        });
    }

    // Return type
    let mut results: Vec<Param> = Vec::new();
    if !output.is_null() {
        let out_json = subst_generic_json(output, &subst_map);
        let sky = rustdoc_type_to_sky(&out_json, aliases);
        let rust = rustdoc_type_to_rust_str(&out_json);
        // Substitute `Self` (possibly nested, e.g. `Option<Self>`) with the
        // concrete receiver type so the wrapper's return type is valid Rust.
        let (rsky, rrust) = recv.unwrap_or(("", ""));
        let sky = subst_self(&sky, rsky);
        let rust = subst_self(&rust, rrust);
        if sky != "()" {
            results.push(Param {
                name: String::new(),
                ty: sky.clone(),
                sky_type: sky,
                rust_type: rust,
            });
        }
    }

    // Skip functions whose params or results carry a lifetime parameter
    // (e.g. `Item<'_>`, `StrftimeItems<'a>`, `&'a str`).  Such types are tied
    // to a borrow scope and cannot be expressed in a monomorphic, owned FFI
    // wrapper — the wrapper signature would reference an undeclared lifetime.
    // These are iterator / borrowed-view types that aren't usable from Sky
    // anyway, so dropping them is the correct boundary behaviour.
    let touches_lifetime = params.iter().any(|p| has_lifetime(&p.rust_type))
        || results.iter().any(|p| has_lifetime(&p.rust_type));
    if touches_lifetime {
        return None;
    }

    // Skip functions whose RESULT is a borrow (`&mut Builder` from a builder
    // setter, a nested `(.., &[u8; 8])` tuple, `&InnerType`).  A borrowed
    // return binds to a lifetime the owned wrapper can't supply (E0106) or
    // needs a ToOwned impl that may not exist (E0599).  Plain `&str`/`&String`
    // is fine — FfiGen copies it to an owned String.  References in PARAMETER
    // position are unaffected (the wrapper takes an owned value and borrows).
    let result_borrows = results.iter().any(|p| {
        let rt = p.rust_type.trim();
        rt.contains('&') && rt != "&str" && rt != "&String" && !is_byte_seq(rt)
    });
    if result_borrows {
        return None;
    }

    // Skip fixed-size arrays / slices (`[u8; 16]`, `&[u8]`, `&[u8; 6]`).  Sky's
    // `Bytes` maps to `Vec<u8>`, which doesn't coerce to a fixed-size array or
    // borrowed slice parameter, and such a result can't be returned by value.
    // (`Vec<u8>` itself has no brackets and is unaffected.)
    let has_bad_array_or_slice = params
        .iter()
        .chain(results.iter())
        .any(|p| p.rust_type.contains('[') && !is_byte_seq(&p.rust_type));
    if has_bad_array_or_slice {
        return None;
    }

    let effect = classify_effect(output, &params, is_async);
    let (recv_sky, recv_rust) = recv.unwrap_or(("", ""));

    Some(Function {
        name: name.to_string(),
        params,
        results,
        variadic: false,
        effect,
        exported: true,
        recv_type: recv_sky.to_string(),
        recv_rust_type: recv_rust.to_string(),
        method_name: if recv.is_some() { name.to_string() } else { String::new() },
        is_field: false,
        is_field_set: false,
        is_pkg_var: false,
    })
}

fn is_ident_byte(c: u8) -> bool {
    c.is_ascii_alphanumeric() || c == b'_'
}

thread_local! {
    // Crate-local type id -> fully-qualified public path (see
    // collect_reachable_paths).  Used to qualify opaque types unambiguously.
    static REACHABLE_PATHS: std::cell::RefCell<HashMap<String, String>> =
        std::cell::RefCell::new(HashMap::new());

    // Crate-local NON-generic type-alias id -> the aliased type JSON.  Lets the
    // type converters see through aliases like `uuid::Bytes = [u8; 16]` so the
    // array/slice filter drops constructors that can't take a Sky Vec<u8>.
    static ALIAS_MAP: std::cell::RefCell<HashMap<String, serde_json::Value>> =
        std::cell::RefCell::new(HashMap::new());
}

/// Fully-qualified public path of a crate-local type by its rustdoc id, if
/// reachable via a public module.  None for unreachable (private) types and
/// for external-crate types (which are dropped by the nameability filter).
fn reachable_local_path(id: &serde_json::Value) -> Option<String> {
    let key = item_id_to_str(id);
    REACHABLE_PATHS.with(|c| c.borrow().get(&key).cloned())
}

/// If `id` is a crate-local non-generic type alias, return the aliased type.
fn resolve_alias(id: &serde_json::Value) -> Option<serde_json::Value> {
    let key = item_id_to_str(id);
    ALIAS_MAP.with(|c| c.borrow().get(&key).cloned())
}

/// Build the id -> aliased-type map for every crate-local, NON-generic type
/// alias (`pub type Bytes = [u8; 16];`).  Generic aliases are skipped — their
/// definitions reference the alias's own type params, which we can't bind.
fn collect_aliases(doc: &serde_json::Value) -> HashMap<String, serde_json::Value> {
    let mut out = HashMap::new();
    let index = match doc["index"].as_object() {
        Some(i) => i,
        None => return out,
    };
    for (id, item) in index {
        if item["crate_id"].as_u64().unwrap_or(1) != 0 {
            continue;
        }
        let alias = item["inner"]
            .get("type_alias")
            .or_else(|| item["inner"].get("typedef"));
        if let Some(a) = alias {
            let generic = a["generics"]["params"]
                .as_array()
                .map(|p| !p.is_empty())
                .unwrap_or(false);
            if generic {
                continue;
            }
            if let Some(ty) = a.get("type").or_else(|| a.get("type_")) {
                out.insert(id.clone(), ty.clone());
            }
        }
    }
    out
}

/// Replace every whole-word `Self` token in a type string with `replacement`.
/// Used to monomorphise `Self`-typed params/results to the concrete receiver
/// type (`Option<Self>` -> `Option<NaiveDate>`).  Type strings are ASCII.
fn subst_self(ty: &str, replacement: &str) -> String {
    if replacement.is_empty() || !ty.contains("Self") {
        return ty.to_string();
    }
    let b = ty.as_bytes();
    let mut out = String::new();
    let mut i = 0;
    while i < b.len() {
        if b[i..].starts_with(b"Self")
            && (i == 0 || !is_ident_byte(b[i - 1]))
            && (i + 4 >= b.len() || !is_ident_byte(b[i + 4]))
        {
            out.push_str(replacement);
            i += 4;
        } else {
            out.push(b[i] as char);
            i += 1;
        }
    }
    out
}

/// Container / std-prelude type names that are always nameable in generated
/// wrappers, regardless of crate re-exports.  Anything else with an
/// uppercase-initial name must be reachable via the crate's public modules.
const ALWAYS_NAMEABLE: &[&str] = &[
    "Option", "Result", "Vec", "Box", "Rc", "Arc", "Mutex", "RwLock", "Cell",
    "RefCell", "HashMap", "BTreeMap", "HashSet", "BTreeSet", "VecDeque", "Cow",
    "String",
];

const TYPE_KINDS: &[&str] =
    &["struct", "enum", "trait", "type_alias", "typedef", "union", "primitive"];

fn item_is_type(it: &serde_json::Value) -> bool {
    let ik = &it["inner"];
    TYPE_KINDS.iter().any(|k| ik.get(*k).is_some())
}

/// True if a Rust type string is fully nameable in a generated wrapper: every
/// uppercase-initial token is either already qualified (preceded by `::`, e.g.
/// `chrono::NaiveDate`, `std::time::Duration`) or an always-nameable container
/// (`Option`, `Result`, `Vec`, …).  A *bare* uppercase token that is neither
/// means an unresolved type — an impl-level generic (`Tz`), a private crate
/// type, or an external type with no public path — so the function is dropped.
fn type_is_nameable(ty: &str) -> bool {
    let b = ty.as_bytes();
    let mut i = 0;
    while i < b.len() {
        if b[i].is_ascii_alphabetic() || b[i] == b'_' {
            let start = i;
            while i < b.len() && is_ident_byte(b[i]) {
                i += 1;
            }
            let tok = &ty[start..i];
            if tok.as_bytes()[0].is_ascii_uppercase() {
                let qualified = start >= 2 && &ty[start - 2..start] == "::";
                if !qualified && !ALWAYS_NAMEABLE.contains(&tok) {
                    return false;
                }
            }
        } else {
            i += 1;
        }
    }
    true
}

/// All of a function's param / result / receiver types are nameable.
fn fn_types_nameable(f: &Function) -> bool {
    f.params.iter().all(|p| type_is_nameable(&p.rust_type))
        && f.results.iter().all(|p| type_is_nameable(&p.rust_type))
        && (f.recv_rust_type.is_empty() || type_is_nameable(&f.recv_rust_type))
}

/// Map every crate-local type's rustdoc item id to a fully-qualified PUBLIC
/// path (`chrono::NaiveDate`, `chrono::format::Parsed`).  Walks each public
/// module, recording defined types as `<module-path>::<name>` and named
/// re-exports as `<module-path>::<reexport-name>`, following `use` edges into
/// other modules transitively.  Prefers the shortest path so root re-exports
/// win over deep submodule definitions.  rustdoc_type_to_rust_str uses this to
/// qualify opaque types unambiguously instead of relying on glob imports.
fn collect_reachable_paths(doc: &serde_json::Value) -> HashMap<String, String> {
    let mut out: HashMap<String, String> = HashMap::new();
    let index = match doc["index"].as_object() {
        Some(i) => i,
        None => return out,
    };
    let paths = doc["paths"].as_object();
    let mpath = |mid: &str| -> Option<String> {
        paths
            .and_then(|m| m.get(mid))
            .and_then(|e| e.get("path"))
            .and_then(|p| p.as_array())
            .map(|segs| {
                segs.iter()
                    .filter_map(|s| s.as_str())
                    .collect::<Vec<_>>()
                    .join("::")
            })
    };
    let insert_shorter = |out: &mut HashMap<String, String>, id: String, path: String| {
        if out.get(&id).map_or(true, |e| path.len() < e.len()) {
            out.insert(id, path);
        }
    };

    let mut stack: Vec<String> = Vec::new();
    for (id, item) in index {
        if item["inner"].get("module").is_some()
            && item["crate_id"].as_u64().unwrap_or(1) == 0
            && is_public(item)
        {
            stack.push(id.clone());
        }
    }

    let mut seen: HashSet<String> = HashSet::new();
    while let Some(mid) = stack.pop() {
        if !seen.insert(mid.clone()) {
            continue;
        }
        let mp = match mpath(&mid) {
            Some(p) => p,
            None => continue,
        };
        let module = match index.get(&mid).and_then(|it| it["inner"].get("module")) {
            Some(m) => m,
            None => continue,
        };
        let items = match module["items"].as_array() {
            Some(a) => a,
            None => continue,
        };
        for child in items {
            let cid = item_id_to_str(child);
            let it = match index.get(&cid) {
                Some(x) => x,
                None => continue,
            };
            if item_is_type(it) {
                if let Some(n) = it["name"].as_str() {
                    insert_shorter(&mut out, cid.clone(), format!("{}::{}", mp, n));
                }
            }
            if let Some(u) = it["inner"].get("use") {
                let tid = u.get("id").map(item_id_to_str);
                if !u["is_glob"].as_bool().unwrap_or(false) {
                    if let (Some(n), Some(tids)) = (u["name"].as_str(), tid.as_ref()) {
                        if index.get(tids).map(item_is_type).unwrap_or(false) {
                            insert_shorter(&mut out, tids.clone(), format!("{}::{}", mp, n));
                        }
                    }
                }
                if let Some(tids) = tid {
                    if index
                        .get(&tids)
                        .and_then(|x| x["inner"].get("module"))
                        .is_some()
                    {
                        stack.push(tids);
                    }
                }
            }
        }
    }
    out
}

/// True for a read-only byte sequence: `&[u8]`, `Vec<u8>`, `[u8; N]`, or
/// `&[u8; N]` (N = literal digits). Excludes `&mut [u8]` and non-u8 elements.
fn is_byte_seq(rt: &str) -> bool {
    let t = rt.trim();
    if t == "Vec<u8>" || t == "&[u8]" {
        return true;
    }
    // [u8; N] or &[u8; N] (the leading & has no `mut`, since &mut is excluded)
    let body = t.strip_prefix('&').unwrap_or(t).trim();
    if let Some(rest) = body.strip_prefix("[u8;") {
        if let Some(inner) = rest.strip_suffix(']') {
            let n = inner.trim();
            return !n.is_empty() && n.chars().all(|c| c.is_ascii_digit());
        }
    }
    false
}

/// True if a Rust type string contains a lifetime token (`'a`, `'static`,
/// `'_`).  A `'` in a type string is always a lifetime (char literals never
/// appear in type positions), so detecting `'` followed by an identifier
/// char is sufficient and unambiguous.
fn has_lifetime(ty: &str) -> bool {
    let bytes = ty.as_bytes();
    for i in 0..bytes.len() {
        if bytes[i] == b'\'' {
            if let Some(&next) = bytes.get(i + 1) {
                if next.is_ascii_alphanumeric() || next == b'_' {
                    return true;
                }
            }
        }
    }
    false
}

fn classify_effect(
    output: &serde_json::Value,
    _params: &[Param],
    is_async: bool,
) -> String {
    if is_async {
        return "effectful".into();
    }
    if is_future_type(output) {
        return "effectful".into();
    }
    let sky = rustdoc_type_to_sky(output, &HashMap::new());
    if sky.starts_with("Result ") {
        return "fallible".into();
    }
    if sky.starts_with("Task ") {
        return "effectful".into();
    }
    "pure".into()
}

fn is_future_type(val: &serde_json::Value) -> bool {
    if let Some(rp) = val.get("resolved_path") {
        let n = rp["name"].as_str().unwrap_or("");
        if n == "Pin" || n == "Future" || n == "BoxFuture" {
            return true;
        }
    }
    false
}

// ── Synthetic bridge functions ─────────────────────────────────────────

fn emit_display_fromstr_bridges(
    functions: &mut Vec<Function>,
    display_types: &HashMap<String, String>,
    fromstr_types: &HashMap<String, String>,
) {
    for (sky_ty, rust_ty) in display_types {
        // recv_rust_type carries the FULL Rust type string (e.g. "DateTime<Tz>")
        // so FfiGen can detect generic params and emit `impl Display` instead of
        // a bare (possibly incomplete) type name.
        functions.push(Function {
            name: "to_string".into(),
            params: vec![Param {
                name: "self".into(),
                ty: sky_ty.clone(),
                sky_type: sky_ty.clone(),
                rust_type: rust_ty.clone(),
            }],
            results: vec![Param {
                name: String::new(),
                ty: "String".into(),
                sky_type: "String".into(),
                rust_type: String::new(),
            }],
            variadic: false,
            effect: "pure".into(),
            exported: true,
            recv_type: sky_ty.clone(),
            recv_rust_type: rust_ty.clone(),
            method_name: "to_string".into(),
            is_field: false,
            is_field_set: false,
            is_pkg_var: false,
        });
    }

    for (sky_ty, rust_ty) in fromstr_types {
        functions.push(Function {
            name: "from_string".into(),
            params: vec![Param {
                name: "s".into(),
                ty: "String".into(),
                sky_type: "String".into(),
                rust_type: "&str".into(),
            }],
            results: vec![Param {
                name: String::new(),
                ty: sky_ty.clone(),
                sky_type: sky_ty.clone(),
                rust_type: rust_ty.clone(),
            }],
            variadic: false,
            effect: "fallible".into(),
            exported: true,
            recv_type: sky_ty.clone(),
            recv_rust_type: rust_ty.clone(),
            method_name: "from_string".into(),
            is_field: false,
            is_field_set: false,
            is_pkg_var: false,
        });
    }
}

// ── rustdoc JSON type → Sky type string ───────────────────────────────
//
// The rustdoc JSON represents Rust types as tagged JSON objects.  The
// tag names have been stable across format versions 28–38+.  We
// gracefully fall back to "String" for unknown shapes rather than
// crashing, so format version drift degrades gracefully.

fn rustdoc_type_to_sky(val: &serde_json::Value, aliases: &HashMap<String, String>) -> String {
    if val.is_null() {
        return "()".to_string();
    }

    // { "primitive": "bool" | "usize" | "str" | … }
    if let Some(prim) = val.get("primitive") {
        return type_str_to_sky(prim.as_str().unwrap_or(""), aliases);
    }

    // { "borrowed_ref": { "type": … } }  →  strip the reference
    if let Some(inner) = val.get("borrowed_ref") {
        return rustdoc_type_to_sky(inner_type(inner), aliases);
    }

    // { "raw_pointer": { "type": … } }
    if let Some(inner) = val.get("raw_pointer") {
        return rustdoc_type_to_sky(inner_type(inner), aliases);
    }

    // { "resolved_path": { "name": "Vec", "args": { "angle_bracketed": … } } }
    if let Some(rp) = val.get("resolved_path") {
        // See through a crate-local non-generic alias (uuid::Bytes -> [u8;16]).
        if let Some(aliased) = rp.get("id").and_then(resolve_alias) {
            return rustdoc_type_to_sky(&aliased, aliases);
        }
        return resolve_path_to_sky(rp, aliases);
    }

    // { "tuple": [type, …] }
    if let Some(items) = val.get("tuple") {
        let parts: Vec<String> = items
            .as_array()
            .map(|arr| {
                arr.iter()
                    .map(|t| rustdoc_type_to_sky(t, aliases))
                    .collect()
            })
            .unwrap_or_default();
        return if parts.is_empty() {
            "()".to_string()
        } else {
            format!("({})", parts.join(", "))
        };
    }

    // { "slice": type }  →  List T
    if let Some(inner) = val.get("slice") {
        return format!("List {}", rustdoc_type_to_sky(inner, aliases));
    }

    // { "array": { "type": …, "len": "N" } }
    if let Some(arr) = val.get("array") {
        let inner = rustdoc_type_to_sky(inner_type(arr), aliases);
        // Fixed arrays surface as `List T`; `[u8; N]` -> `List Int`, matching
        // slices and Vec<u8>. The real Rust shape is preserved in rust_type.
        return format!("List {}", inner);
    }

    // { "generic": "T" }  — unresolved type parameter
    if let Some(g) = val.get("generic") {
        return g.as_str().unwrap_or("String").to_string();
    }

    // impl Trait / dyn Trait — opaque
    if val.get("impl_trait").is_some() || val.get("dyn_trait").is_some() {
        return "String".to_string();
    }

    // Associated type path
    if let Some(qp) = val.get("qualified_path") {
        let name = qp["name"].as_str().unwrap_or("");
        return name.to_string();
    }

    "String".to_string()
}

fn resolve_path_to_sky(rp: &serde_json::Value, aliases: &HashMap<String, String>) -> String {
    // "name" (format <35) or "path" (format 35+) — try both
    let name = rp["name"]
        .as_str()
        .or_else(|| rp["path"].as_str())
        .unwrap_or("");
    let args = extract_angle_type_args(rp.get("args"), aliases);

    match name {
        "Vec" => format!(
            "List {}",
            args.first().cloned().unwrap_or_else(|| "String".into())
        ),
        "Option" => format!(
            "Maybe {}",
            args.first().cloned().unwrap_or_else(|| "String".into())
        ),
        "Box" | "Arc" | "Rc" | "Mutex" | "RwLock" | "Cell" | "RefCell" => {
            args.first().cloned().unwrap_or_else(|| name.to_string())
        }
        "String" | "str" | "OsStr" | "OsString" | "PathBuf" | "Path" => "String".to_string(),
        "HashMap" | "BTreeMap" | "IndexMap" | "AHashMap" => {
            let val = args.get(1).cloned().unwrap_or_else(|| "String".into());
            format!("Dict String {}", val)
        }
        "Result" => {
            // Rust Result<T, E>  →  Sky Result E T
            let ok = args.first().cloned().unwrap_or_else(|| "()".into());
            let err = args.get(1).cloned().unwrap_or_else(|| "String".into());
            format!("Result {} {}", err, ok)
        }
        "SkyResult" => {
            // SkyResult<E, A>  →  Result E A
            let err = args.first().cloned().unwrap_or_else(|| "String".into());
            let ok = args.get(1).cloned().unwrap_or_else(|| "()".into());
            format!("Result {} {}", err, ok)
        }
        "SkyError" => "Error".to_string(),
        "SkyTask" => {
            let err = args.first().cloned().unwrap_or_else(|| "Error".into());
            let ok = args.get(1).cloned().unwrap_or_else(|| "()".into());
            format!("Task {} {}", err, ok)
        }
        // async / future wrappers
        "Pin" => {
            // Pin<Box<dyn Future<Output = T>>>  →  Task Error T
            // Try to extract Output from the inner Future
            args.first()
                .map(|inner| {
                    if inner.starts_with("Task ") {
                        inner.clone()
                    } else {
                        format!("Task Error {}", inner)
                    }
                })
                .unwrap_or_else(|| "Task Error ()".into())
        }
        "Future" => {
            // Extract Output = T binding
            let output = extract_binding_type(rp.get("args"), "Output", aliases)
                .unwrap_or_else(|| "()".into());
            format!("Task Error {}", output)
        }
        _ => {
            // Strip module-path qualifier: std::collections::HashMap → HashMap
            let base = name.rsplit_once("::").map(|(_, last)| last).unwrap_or(name);
            aliases.get(base).cloned().unwrap_or_else(|| base.to_string())
        }
    }
}

/// Extract angle-bracket type arguments from a rustdoc args object.
/// Each entry looks like `{ "type": <type_json> }` (or lifetime, const — skip those).
fn extract_angle_type_args(
    args: Option<&serde_json::Value>,
    aliases: &HashMap<String, String>,
) -> Vec<String> {
    args.and_then(|a| a.get("angle_bracketed"))
        .and_then(|ab| ab.get("args"))
        .and_then(|a| a.as_array())
        .map(|arr| {
            arr.iter()
                .filter_map(|arg| {
                    arg.get("type")
                        .map(|t| rustdoc_type_to_sky(t, aliases))
                })
                .collect()
        })
        .unwrap_or_default()
}

/// Extract an associated-type binding (e.g. `Output = T`) from args.
fn extract_binding_type(
    args: Option<&serde_json::Value>,
    binding_name: &str,
    aliases: &HashMap<String, String>,
) -> Option<String> {
    let bindings = args?
        .get("angle_bracketed")?
        .get("bindings")?
        .as_array()?;
    for b in bindings {
        if b["name"].as_str() == Some(binding_name) {
            // binding value is under b["binding"]["equality"] in newer formats
            if let Some(ty) = b.get("binding").and_then(|bv| bv.get("equality")) {
                return Some(rustdoc_type_to_sky(ty, aliases));
            }
            // older format: b["value"] or b["type"]
            if let Some(ty) = b.get("value").or_else(|| b.get("type")) {
                return Some(rustdoc_type_to_sky(ty, aliases));
            }
        }
    }
    None
}

// ── rustdoc JSON type → Rust type string ──────────────────────────────
//
// Used to populate the `rustType` field in the output JSON that
// FfiGen.hs reads for coercion decisions.

fn rustdoc_type_to_rust_str(val: &serde_json::Value) -> String {
    if val.is_null() {
        return "()".to_string();
    }

    if let Some(prim) = val.get("primitive") {
        return prim.as_str().unwrap_or("()").to_string();
    }

    if let Some(inner) = val.get("borrowed_ref") {
        let m = if is_mutable(inner) { "mut " } else { "" };
        // rustdoc JSON stores lifetimes WITH the leading apostrophe already
        // (e.g. "'static", "'a").  Don't prepend another one.
        let lt = inner["lifetime"]
            .as_str()
            .map(|l| {
                let s = if l.starts_with('\'') { l.to_string() } else { format!("'{}", l) };
                format!("{} ", s)
            })
            .unwrap_or_default();
        return format!("&{}{}{}", lt, m, rustdoc_type_to_rust_str(inner_type(inner)));
    }

    if let Some(inner) = val.get("raw_pointer") {
        let m = if is_mutable(inner) { "mut" } else { "const" };
        return format!("*{} {}", m, rustdoc_type_to_rust_str(inner_type(inner)));
    }

    if let Some(rp) = val.get("resolved_path") {
        // See through a crate-local non-generic alias (uuid::Bytes -> [u8;16]),
        // so the array/slice filter sees the real shape.
        if let Some(aliased) = rp.get("id").and_then(resolve_alias) {
            return rustdoc_type_to_rust_str(&aliased);
        }
        let raw_name = rp["name"]
            .as_str()
            .or_else(|| rp["path"].as_str())
            .unwrap_or("");
        // For an EXTERNAL-crate type (crate_id != 0, e.g. `core::time::Duration`),
        // emit the fully-qualified path: it's unambiguous and avoids colliding
        // with a same-named crate-local re-export (chrono aliases `Duration`).
        // For a CRATE-LOCAL type strip to the last segment — the generated
        // bindings glob-import the crate's public modules so the bare name is
        // in scope; a `crate::`-prefixed path would wrongly resolve against the
        // sky-app crate.  External types whose canonical path runs through a
        // private module (e.g. `core::ops::range::RangeInclusive`) are emitted
        // verbatim but get dropped later by the nameability filter.
        // Qualify CRATE-LOCAL opaque types with their public path
        // (`chrono::NaiveDate`).  External/std types are left bare: the only
        // ones usable are the always-nameable containers (Vec, Option, …);
        // anything else (`Duration`, `RangeInclusive`) stays a bare unknown
        // and is dropped by the nameability filter, since std's rustdoc paths
        // route through private modules and can't be reproduced reliably.
        let qualified = rp.get("id").and_then(reachable_local_path);
        let name: String = match qualified {
            Some(full) => full,
            None => raw_name.rsplit("::").next().unwrap_or(raw_name).to_string(),
        };
        let name = name.as_str();
        let args: Vec<String> = rp
            .get("args")
            .and_then(|a| a.get("angle_bracketed"))
            .and_then(|ab| ab.get("args"))
            .and_then(|a| a.as_array())
            .map(|arr| {
                arr.iter()
                    .filter_map(|arg| {
                        if let Some(t) = arg.get("type") {
                            Some(rustdoc_type_to_rust_str(t))
                        } else if let Some(l) = arg.get("lifetime") {
                            // rustdoc JSON already includes the leading apostrophe
                            let s = l.as_str().unwrap_or("'a");
                            Some(if s.starts_with('\'') { s.to_string() } else { format!("'{}", s) })
                        } else {
                            None
                        }
                    })
                    .collect()
            })
            .unwrap_or_default();
        return if args.is_empty() {
            name.to_string()
        } else {
            format!("{}<{}>", name, args.join(", "))
        };
    }

    if let Some(items) = val.get("tuple") {
        let parts: Vec<String> = items
            .as_array()
            .map(|arr| arr.iter().map(|t| rustdoc_type_to_rust_str(t)).collect())
            .unwrap_or_default();
        return format!("({})", parts.join(", "));
    }

    if let Some(inner) = val.get("slice") {
        return format!("[{}]", rustdoc_type_to_rust_str(inner));
    }

    if let Some(arr) = val.get("array") {
        let len = arr["len"].as_str().unwrap_or("?");
        return format!("[{}; {}]", rustdoc_type_to_rust_str(inner_type(arr)), len);
    }

    if let Some(g) = val.get("generic") {
        return g.as_str().unwrap_or("_").to_string();
    }

    String::new()
}

// ── String-based type mapping (for primitives) ─────────────────────────

fn type_str_to_sky(s: &str, aliases: &HashMap<String, String>) -> String {
    let s = s.trim();

    if let Some(sky) = aliases.get(s) {
        return sky.clone();
    }

    match s {
        "str" | "String" | "OsStr" | "OsString" | "CStr" | "CString" => "String".into(),
        "bool" => "Bool".into(),
        "()" => "()".into(),
        "i8" | "i16" | "i32" | "i64" | "i128" | "isize" | "u8" | "u16" | "u32" | "u64"
        | "u128" | "usize" => "Int".into(),
        "f32" | "f64" => "Float".into(),
        "SkyError" | "Error" => "Error".into(),
        _ => {
            // Strip module path
            let base = s.rsplit_once("::").map(|(_, l)| l).unwrap_or(s);
            let base = base.split('<').next().unwrap_or(base).trim();
            if base.is_empty() {
                return "String".into();
            }
            // Lowercase primitive names
            match base {
                "string" | "str" => "String".into(),
                "bool" => "Bool".into(),
                "int" | "integer" => "Int".into(),
                "float" => "Float".into(),
                _ => base.to_string(),
            }
        }
    }
}

// ── Helpers ────────────────────────────────────────────────────────────

/// Fetch the wrapped inner type from a `borrowed_ref` / `raw_pointer` /
/// `array` node, tolerating rustdoc format drift: older formats use the
/// key `"type_"`, newer formats use `"type"`.  Returns the JSON null value
/// when neither is present (callers map that to `()`).
fn inner_type(wrapper: &serde_json::Value) -> &serde_json::Value {
    let t = &wrapper["type"];
    if !t.is_null() {
        t
    } else {
        &wrapper["type_"]
    }
}

/// Read a reference/pointer mutability flag, tolerating both the newer
/// `"is_mutable"` and older `"mutable"` rustdoc keys.
fn is_mutable(wrapper: &serde_json::Value) -> bool {
    wrapper["is_mutable"]
        .as_bool()
        .or_else(|| wrapper["mutable"].as_bool())
        .unwrap_or(false)
}

/// Convert a rustdoc item ID to a string key for index lookups.
/// Item IDs appear as integers in new format (35+) and strings in old format.
fn item_id_to_str(id: &serde_json::Value) -> String {
    if let Some(n) = id.as_u64() {
        return n.to_string();
    }
    id.as_str().unwrap_or("").to_string()
}

fn pkg_error(name: &str, msg: &str) -> PkgInfo {
    PkgInfo {
        pkg: name.into(),
        name: name.into(),
        version: String::new(),
        functions: vec![],
        modules: vec![],
        errors: vec![msg.into()],
    }
}

/// Split a comma-separated generic arg list respecting nested `<>` and `()`.
#[allow(dead_code)]
fn split_top_level(s: &str, sep: char) -> Vec<&str> {
    let mut result = Vec::new();
    let mut depth = 0i32;
    let mut start = 0;
    for (i, c) in s.char_indices() {
        match c {
            '<' | '(' => depth += 1,
            '>' | ')' => depth -= 1,
            _ if depth == 0 && c == sep => {
                result.push(s[start..i].trim());
                start = i + 1;
            }
            _ => {}
        }
    }
    if start < s.len() {
        result.push(s[start..].trim());
    }
    result
}

// ── Monomorphisation-on-demand (Alt-1) ─────────────────────────────────
// A generic param bound maps to a concrete, Sky-representable type that we
// substitute into the signature so the inspector can emit a normal binding.
// We use OWNED concretes (Vec<u8>/String): valid for every bound below
// (Vec<u8>: AsRef<[u8]>+Into<Vec<u8>>+IntoIterator<Item=u8>; String:
// AsRef<str>+Into<String>+Display+ToString), and the exact raw shapes FfiGen
// already coerces from Sky List Int / String.

fn vec_u8_node() -> serde_json::Value {
    serde_json::json!({ "resolved_path": { "name": "Vec", "path": "Vec", "id": 0,
        "args": { "angle_bracketed": { "args": [{ "type": { "primitive": "u8" } }], "constraints": [] } } } })
}

fn string_node() -> serde_json::Value {
    serde_json::json!({ "resolved_path": { "name": "String", "path": "String", "id": 0, "args": null } })
}

fn i64_node() -> serde_json::Value {
    serde_json::json!({ "primitive": "i64" })
}
fn f64_node() -> serde_json::Value {
    serde_json::json!({ "primitive": "f64" })
}
fn usize_node() -> serde_json::Value {
    serde_json::json!({ "primitive": "usize" })
}

fn node_is_u8_primitive(t: &serde_json::Value) -> bool {
    t.get("primitive").and_then(|p| p.as_str()) == Some("u8")
}
/// True if a rustdoc type node is the `u8` slice `[u8]`.
fn node_is_u8_slice(t: &serde_json::Value) -> bool {
    t.get("slice").and_then(|s| s.get("primitive")).and_then(|p| p.as_str()) == Some("u8")
}
/// True if a rustdoc type node is the primitive `str` (possibly borrowed).
fn node_is_str(t: &serde_json::Value) -> bool {
    if t.get("primitive").and_then(|p| p.as_str()) == Some("str") { return true; }
    let inner = t.get("borrowed_ref").and_then(|b| b.get("type").or_else(|| b.get("type_")));
    inner.map(node_is_str).unwrap_or(false)
}
/// True if a rustdoc type node is `Vec<u8>`.
fn node_is_vec_u8(t: &serde_json::Value) -> bool {
    let rp = match t.get("resolved_path") { Some(r) => r, None => return false };
    let name = rp.get("name").or_else(|| rp.get("path")).and_then(|n| n.as_str()).unwrap_or("");
    if name.rsplit("::").next().unwrap_or(name) != "Vec" { return false; }
    rp.get("args").and_then(|a| a.get("angle_bracketed")).and_then(|ab| ab.get("args"))
        .and_then(|v| v.as_array()).and_then(|a| a.first())
        .and_then(|a| a.get("type"))
        .map(|t| t.get("primitive").and_then(|p| p.as_str()) == Some("u8"))
        .unwrap_or(false)
}
/// True if a rustdoc type node is `String`.
fn node_is_string(t: &serde_json::Value) -> bool {
    let rp = match t.get("resolved_path") { Some(r) => r, None => return false };
    let name = rp.get("name").or_else(|| rp.get("path")).and_then(|n| n.as_str()).unwrap_or("");
    name.rsplit("::").next().unwrap_or(name) == "String"
}

/// Map an INNER TYPE NODE (the X in AsRef<X> / Into<X> / IntoIterator<Item=X>)
/// to its canonical Sky-coercible concrete type-JSON node, or None if X isn't
/// representable in Sky. Recursive: handles primitives, paths, slices.
fn concrete_for_inner_type(t: &serde_json::Value) -> Option<serde_json::Value> {
    // primitive: u8 slice element, str, integers, floats, bool, char
    if let Some(p) = t.get("primitive").and_then(|p| p.as_str()) {
        return match p {
            "str" => Some(string_node()),
            "u8" => Some(serde_json::json!({ "primitive": "u8" })),
            "i8" | "i16" | "i32" | "i64" | "isize"
            | "u16" | "u32" | "u64" | "usize" => Some(i64_node()),
            "f32" | "f64" => Some(f64_node()),
            "bool" => Some(serde_json::json!({ "primitive": "bool" })),
            "char" => Some(serde_json::json!({ "primitive": "char" })),
            _ => None,
        };
    }
    // slice: [u8] -> Vec<u8>; [other] -> recurse element (Vec<T'>)
    if let Some(inner) = t.get("slice") {
        let elem = concrete_for_inner_type(inner)?;
        return Some(serde_json::json!({
            "resolved_path": { "name": "Vec", "path": "Vec", "id": 0,
                "args": { "angle_bracketed": { "args": [{ "type": elem }], "constraints": [] } } }
        }));
    }
    // borrowed_ref: see through to the inner type (then resolve it)
    if let Some(br) = t.get("borrowed_ref") {
        let inner = br.get("type").or_else(|| br.get("type_"))?;
        return concrete_for_inner_type(inner);
    }
    // resolved_path: known std/prelude types map to Sky concretes
    if let Some(rp) = t.get("resolved_path") {
        let name = rp.get("name").or_else(|| rp.get("path")).and_then(|n| n.as_str()).unwrap_or("");
        let leaf = name.rsplit("::").next().unwrap_or(name);
        return match leaf {
            "String" | "OsString" | "PathBuf"
            | "Path" | "OsStr" => Some(string_node()),
            "Vec" => {
                let inner = rp.get("args").and_then(|a| a.get("angle_bracketed"))
                    .and_then(|ab| ab.get("args")).and_then(|v| v.as_array())
                    .and_then(|a| a.first()).and_then(|a| a.get("type"))?;
                let elem = concrete_for_inner_type(inner)?;
                Some(serde_json::json!({
                    "resolved_path": { "name": "Vec", "path": "Vec", "id": 0,
                        "args": { "angle_bracketed": { "args": [{ "type": elem }], "constraints": [] } } }
                }))
            }
            _ => None,
        };
    }
    None
}

/// Map a single trait bound to the concrete type-JSON node to substitute, or
/// `None` if the bound is not in the v1 table.
fn bound_to_concrete(bound: &serde_json::Value) -> Option<serde_json::Value> {
    let tr = bound.get("trait_bound")?.get("trait")?;
    let path = tr.get("path").or_else(|| tr.get("name")).and_then(|p| p.as_str())?;
    let name = path.rsplit("::").next().unwrap_or(path);
    let args: Vec<&serde_json::Value> = tr.get("args")
        .and_then(|a| a.get("angle_bracketed")).and_then(|ab| ab.get("args"))
        .and_then(|v| v.as_array())
        .map(|arr| arr.iter().filter_map(|a| a.get("type")).collect())
        .unwrap_or_default();
    match name {
        "Display" | "ToString" => Some(string_node()),
        "AsRef" | "Borrow" => {
            let arg = args.first()?;
            if node_is_u8_slice(arg) { Some(vec_u8_node()) }
            else if node_is_str(arg) { Some(string_node()) }
            else { None }
        }
        "Into" => {
            let arg = args.first()?;
            if node_is_vec_u8(arg) { Some(vec_u8_node()) }
            else if node_is_string(arg) { Some(string_node()) }
            else { None }
        }
        "IntoIterator" => {
            // Item is an associated-type constraint: args.angle_bracketed.constraints[]
            // with name "Item" and an equality binding to the element type.
            let item_is_u8 = tr.get("args")
                .and_then(|a| a.get("angle_bracketed"))
                .and_then(|ab| ab.get("constraints"))
                .and_then(|c| c.as_array())
                .map(|cs| cs.iter().any(|c| {
                    c.get("name").and_then(|n| n.as_str()) == Some("Item")
                        && c.get("binding").and_then(|b| b.get("equality")).and_then(|e| e.get("type"))
                            .map(node_is_u8_primitive).unwrap_or(false)
                }))
                .unwrap_or(false);
            if item_is_u8 { Some(vec_u8_node()) } else { None }
        }
        _ => None,
    }
}

/// Auto/marker traits that don't constrain the Sky-facing type — ignored when
/// resolving a param's bounds.
const MARKER_TRAITS: &[&str] = &[
    "Sized", "Send", "Sync", "Copy", "Clone", "Debug", "Default", "Unpin",
    "RefUnwindSafe", "UnwindSafe", "Eq", "PartialEq", "Hash", "Ord", "PartialOrd",
];

/// A bound that contributes no type information: a marker/auto trait, or a
/// lifetime/outlives bound (no `trait_bound` key).
fn is_marker_bound(bound: &serde_json::Value) -> bool {
    let tr = match bound.get("trait_bound").and_then(|tb| tb.get("trait")) {
        Some(t) => t,
        None => return true, // outlives/lifetime bound -> ignore
    };
    let path = tr.get("path").or_else(|| tr.get("name")).and_then(|p| p.as_str()).unwrap_or("");
    let name = path.rsplit("::").next().unwrap_or(path);
    MARKER_TRAITS.contains(&name)
}

/// Resolve a parameter's full bound list to a single concrete node, or `None`
/// (drop) if: only markers (no type pinned), an unmappable non-marker bound, or
/// two disagreeing shape bounds.
fn resolve_param_bounds(bounds: &[serde_json::Value]) -> Option<serde_json::Value> {
    let mut concrete: Option<serde_json::Value> = None;
    for b in bounds {
        if is_marker_bound(b) { continue; }
        match bound_to_concrete(b) {
            Some(c) => match &concrete {
                Some(prev) if *prev != c => return None, // conflict
                Some(_) => {}
                None => concrete = Some(c),
            },
            None => return None, // non-marker bound we can't map
        }
    }
    concrete
}

/// Recursively replace every `{"generic":"NAME"}` node whose NAME is in `map`
/// with the mapped concrete type node. Other nodes pass through unchanged.
/// (`impl Trait` nodes are handled separately in Task 6.)
fn subst_generic_json(
    val: &serde_json::Value,
    map: &std::collections::HashMap<String, serde_json::Value>,
) -> serde_json::Value {
    if let Some(g) = val.get("generic").and_then(|g| g.as_str()) {
        if let Some(concrete) = map.get(g) {
            return concrete.clone();
        }
    }
    // impl Trait: replace with the concrete the bounds resolve to (if any).
    if let Some(bounds) = val.get("impl_trait").and_then(|b| b.as_array()) {
        if let Some(concrete) = resolve_param_bounds(bounds) {
            return concrete;
        }
    }
    match val {
        serde_json::Value::Object(obj) => serde_json::Value::Object(
            obj.iter().map(|(k, v)| (k.clone(), subst_generic_json(v, map))).collect(),
        ),
        serde_json::Value::Array(arr) => serde_json::Value::Array(
            arr.iter().map(|v| subst_generic_json(v, map)).collect(),
        ),
        other => other.clone(),
    }
}

/// Build the substitution map for a function's generic params, or `None` if the
/// function should be dropped (a `const` generic, or any type param whose bounds
/// don't resolve). Lifetime params are ignored. A type param that appears only in
/// return position with an unmappable bound (e.g. `T: FromStr`) yields `None`,
/// which is the correct drop. Bounds are gathered from both inline param bounds
/// and `where_predicates`.
fn resolve_generics(
    fn_data: &serde_json::Value,
) -> Option<std::collections::HashMap<String, serde_json::Value>> {
    let params = match fn_data["generics"]["params"].as_array() {
        Some(p) => p,
        None => return Some(std::collections::HashMap::new()),
    };

    // where-clause bounds, keyed by generic name
    let mut where_bounds: std::collections::HashMap<String, Vec<serde_json::Value>> =
        std::collections::HashMap::new();
    if let Some(wps) = fn_data["generics"]["where_predicates"].as_array() {
        for wp in wps {
            if let Some(bp) = wp.get("bound_predicate") {
                if let Some(g) = bp.get("type").and_then(|t| t.get("generic")).and_then(|g| g.as_str()) {
                    if let Some(bs) = bp.get("bounds").and_then(|b| b.as_array()) {
                        where_bounds.entry(g.to_string()).or_default().extend(bs.iter().cloned());
                    }
                }
            }
        }
    }

    let mut map = std::collections::HashMap::new();
    for p in params {
        let kind = &p["kind"];
        if kind.get("const").is_some() { return None; }   // const generic -> drop
        if kind.get("lifetime").is_some() { continue; }   // lifetime param -> ignore
        let name = p.get("name").and_then(|n| n.as_str()).unwrap_or("");
        let mut bounds: Vec<serde_json::Value> = kind.get("type")
            .and_then(|t| t.get("bounds")).and_then(|b| b.as_array())
            .cloned().unwrap_or_default();
        if let Some(extra) = where_bounds.get(name) { bounds.extend(extra.iter().cloned()); }
        match resolve_param_bounds(&bounds) {
            Some(concrete) => { map.insert(name.to_string(), concrete); }
            None => return None, // unresolvable type param -> drop whole fn
        }
    }
    Some(map)
}

/// True if every `impl Trait` node anywhere in `val` resolves to a concrete
/// type. An UNresolvable `impl Trait` arg would otherwise fall through to the
/// `"String"` fallback in `rustdoc_type_to_sky`, which is unsound — so the
/// caller drops the function instead.
fn impl_traits_resolvable(val: &serde_json::Value) -> bool {
    if let Some(bounds) = val.get("impl_trait").and_then(|b| b.as_array()) {
        if resolve_param_bounds(bounds).is_none() {
            return false;
        }
    }
    match val {
        serde_json::Value::Object(obj) => obj.values().all(impl_traits_resolvable),
        serde_json::Value::Array(arr) => arr.iter().all(impl_traits_resolvable),
        _ => true,
    }
}

// ── Tests ──────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    fn sky(val: &serde_json::Value) -> String {
        rustdoc_type_to_sky(val, &HashMap::new())
    }

    fn prim(s: &str) -> serde_json::Value {
        serde_json::json!({ "primitive": s })
    }

    fn path(name: &str) -> serde_json::Value {
        // Use both "name" and "path" to cover old and new format versions.
        serde_json::json!({ "resolved_path": { "name": name, "path": name, "id": 0, "args": null } })
    }

    fn path_with_args(name: &str, args: Vec<serde_json::Value>) -> serde_json::Value {
        let type_args: Vec<serde_json::Value> = args
            .into_iter()
            .map(|t| serde_json::json!({ "type": t }))
            .collect();
        serde_json::json!({
            "resolved_path": {
                "name": name,
                "path": name,
                "id": 0,
                "args": {
                    "angle_bracketed": {
                        "args": type_args,
                        "bindings": []
                    }
                }
            }
        })
    }

    fn borrowed(inner: serde_json::Value) -> serde_json::Value {
        serde_json::json!({ "borrowed_ref": { "lifetime": null, "mutable": false, "type_": inner } })
    }

    #[test]
    fn test_primitives() {
        assert_eq!(sky(&prim("u64")), "Int");
        assert_eq!(sky(&prim("usize")), "Int");
        assert_eq!(sky(&prim("i32")), "Int");
        assert_eq!(sky(&prim("f32")), "Float");
        assert_eq!(sky(&prim("bool")), "Bool");
        assert_eq!(sky(&prim("str")), "String");
    }

    #[test]
    fn test_string_path() {
        assert_eq!(sky(&path("String")), "String");
        assert_eq!(sky(&path("OsString")), "String");
    }

    #[test]
    fn test_generic_containers() {
        assert_eq!(sky(&path_with_args("Vec", vec![prim("u64")])), "List Int");
        assert_eq!(
            sky(&path_with_args("Option", vec![path("String")])),
            "Maybe String"
        );
        assert_eq!(
            sky(&path_with_args("HashMap", vec![path("String"), prim("u64")])),
            "Dict String Int"
        );
    }

    #[test]
    fn test_result_and_sky_result() {
        // Rust Result<String, SkyError>  →  Sky Result Error String
        let r = path_with_args("Result", vec![path("String"), path("SkyError")]);
        assert_eq!(sky(&r), "Result Error String");

        // SkyResult<SkyError, String>  →  Sky Result Error String
        let sr = path_with_args("SkyResult", vec![path("SkyError"), path("String")]);
        assert_eq!(sky(&sr), "Result Error String");
    }

    #[test]
    fn test_borrowed_ref_stripped() {
        // &str → String
        assert_eq!(sky(&borrowed(prim("str"))), "String");
        // &Vec<u64> → List Int
        assert_eq!(
            sky(&borrowed(path_with_args("Vec", vec![prim("u64")]))),
            "List Int"
        );
    }

    #[test]
    fn test_is_byte_seq() {
        assert!(is_byte_seq("&[u8]"));
        assert!(is_byte_seq("Vec<u8>"));
        assert!(is_byte_seq("[u8; 16]"));
        assert!(is_byte_seq("&[u8; 32]"));
        // Not byte sequences:
        assert!(!is_byte_seq("&mut [u8]"));
        assert!(!is_byte_seq("&[u16]"));
        assert!(!is_byte_seq("[f64; 3]"));
        assert!(!is_byte_seq("Vec<i64>"));
        assert!(!is_byte_seq("&str"));
    }

    fn trait_bound(path: &str, args: Vec<serde_json::Value>) -> serde_json::Value {
        let type_args: Vec<_> = args.into_iter().map(|t| serde_json::json!({ "type": t })).collect();
        serde_json::json!({ "trait_bound": { "trait": {
            "path": path, "name": path, "id": 0,
            "args": { "angle_bracketed": { "args": type_args, "constraints": [] } }
        }, "modifier": "none" } })
    }

    #[test]
    fn test_bound_to_concrete() {
        // AsRef<[u8]> / Borrow<[u8]>  -> Vec<u8> (List Int)
        let asref_u8 = trait_bound("AsRef", vec![serde_json::json!({ "slice": { "primitive": "u8" } })]);
        assert_eq!(bound_to_concrete(&asref_u8), Some(vec_u8_node()));
        // AsRef<str> / Borrow<str>    -> String
        assert_eq!(bound_to_concrete(&trait_bound("AsRef", vec![prim("str")])), Some(string_node()));
        // Display / ToString (no arg) -> String
        assert_eq!(bound_to_concrete(&trait_bound("Display", vec![])), Some(string_node()));
        assert_eq!(bound_to_concrete(&trait_bound("ToString", vec![])), Some(string_node()));
        // Into<Vec<u8>> -> Vec<u8> ; Into<String> -> String
        assert_eq!(bound_to_concrete(&trait_bound("Into", vec![path_with_args("Vec", vec![prim("u8")])])), Some(vec_u8_node()));
        assert_eq!(bound_to_concrete(&trait_bound("Into", vec![path("String")])), Some(string_node()));
        // Unknown / unsupported -> None
        assert_eq!(bound_to_concrete(&trait_bound("FromStr", vec![])), None);
        assert_eq!(bound_to_concrete(&trait_bound("AsRef", vec![prim("u16")])), None);
    }

    #[test]
    fn test_resolve_param_bounds() {
        let asref_u8 = trait_bound("AsRef", vec![serde_json::json!({ "slice": { "primitive": "u8" } })]);
        let clone = trait_bound("Clone", vec![]);
        let send = trait_bound("Send", vec![]);
        let foo = trait_bound("SomeWeirdTrait", vec![]);
        let asref_str = trait_bound("AsRef", vec![prim("str")]);

        // shape bound alone -> resolves
        assert_eq!(resolve_param_bounds(&[asref_u8.clone()]), Some(vec_u8_node()));
        // shape + marker bounds -> markers ignored, resolves
        assert_eq!(resolve_param_bounds(&[asref_u8.clone(), clone.clone(), send]), Some(vec_u8_node()));
        // only markers -> can't pin a type -> None
        assert_eq!(resolve_param_bounds(&[clone]), None);
        // an unknown non-marker bound -> None (unsound to guess)
        assert_eq!(resolve_param_bounds(&[asref_u8.clone(), foo]), None);
        // two conflicting shape bounds -> None
        assert_eq!(resolve_param_bounds(&[asref_u8, asref_str]), None);
    }

    fn type_param(name: &str, bounds: Vec<serde_json::Value>) -> serde_json::Value {
        serde_json::json!({ "name": name, "kind": { "type": { "bounds": bounds, "default": null, "is_synthetic": false } } })
    }
    fn fn_with_generics(params: Vec<serde_json::Value>, wheres: Vec<serde_json::Value>) -> serde_json::Value {
        serde_json::json!({ "generics": { "params": params, "where_predicates": wheres } })
    }

    #[test]
    fn test_resolve_generics() {
        let asref_u8 = trait_bound("AsRef", vec![serde_json::json!({ "slice": { "primitive": "u8" } })]);
        let display = trait_bound("Display", vec![]);

        // no generics -> empty map (Some)
        assert_eq!(resolve_generics(&fn_with_generics(vec![], vec![])), Some(std::collections::HashMap::new()));

        // <T: AsRef<[u8]>> -> {T: Vec<u8>}
        let r = resolve_generics(&fn_with_generics(vec![type_param("T", vec![asref_u8.clone()])], vec![])).unwrap();
        assert_eq!(r.get("T"), Some(&vec_u8_node()));

        // two params both resolve
        let r2 = resolve_generics(&fn_with_generics(
            vec![type_param("T", vec![asref_u8.clone()]), type_param("U", vec![display])], vec![])).unwrap();
        assert_eq!(r2.get("T"), Some(&vec_u8_node()));
        assert_eq!(r2.get("U"), Some(&string_node()));

        // unresolvable bound -> None (drop whole fn)
        assert_eq!(resolve_generics(&fn_with_generics(vec![type_param("T", vec![trait_bound("FromStr", vec![])])], vec![])), None);

        // const generic present -> None
        let const_p = serde_json::json!({ "name": "N", "kind": { "const": { "type": { "primitive": "usize" } } } });
        assert_eq!(resolve_generics(&fn_with_generics(vec![const_p], vec![])), None);

        // bound supplied via where-predicate instead of inline
        let wp = serde_json::json!({ "bound_predicate": { "type": { "generic": "T" }, "bounds": [asref_u8] } });
        let r3 = resolve_generics(&fn_with_generics(vec![type_param("T", vec![])], vec![wp])).unwrap();
        assert_eq!(r3.get("T"), Some(&vec_u8_node()));
    }

    #[test]
    fn test_subst_generic_json() {
        let mut map = std::collections::HashMap::new();
        map.insert("T".to_string(), vec_u8_node());
        // bare {generic:"T"} -> Vec<u8>
        assert_eq!(subst_generic_json(&serde_json::json!({ "generic": "T" }), &map), vec_u8_node());
        // nested Option<T> -> Option<Vec<u8>>: the T node deep inside is replaced
        let opt_t = path_with_args("Option", vec![serde_json::json!({ "generic": "T" })]);
        let got = subst_generic_json(&opt_t, &map);
        assert_eq!(sky(&got), "Maybe List Int");
        // an unrelated generic "U" not in map is left intact
        assert_eq!(subst_generic_json(&serde_json::json!({ "generic": "U" }), &map),
                   serde_json::json!({ "generic": "U" }));
    }

    // Build a function item shaped like rustdoc's: encode<T: AsRef<[u8]>>(data: T) -> String
    fn encode_fn_data() -> serde_json::Value {
        let asref_u8 = trait_bound("AsRef", vec![serde_json::json!({ "slice": { "primitive": "u8" } })]);
        serde_json::json!({
            "header": { "is_async": false, "is_unsafe": false },
            "generics": { "params": [ type_param("T", vec![asref_u8]) ], "where_predicates": [] },
            "sig": { "inputs": [ ["data", { "generic": "T" }] ], "output": prim("str") }
        })
    }

    #[test]
    fn test_parse_fn_item_monomorphises() {
        let f = parse_fn_item("encode", &encode_fn_data(), &HashMap::new(), None)
            .expect("encode<T:AsRef<[u8]>> should now bind, not drop");
        assert_eq!(f.name, "encode");
        assert_eq!(f.params.len(), 1);
        assert_eq!(f.params[0].sky_type, "List Int");   // T -> Vec<u8> -> List Int
        assert_eq!(f.params[0].rust_type, "Vec<u8>");
        assert_eq!(f.results[0].sky_type, "String");    // -> str -> String
    }

    #[test]
    fn test_parse_fn_item_drops_unresolvable_generic() {
        // parse<T: FromStr>() -> T  must still drop
        let fd = serde_json::json!({
            "header": { "is_async": false, "is_unsafe": false },
            "generics": { "params": [ type_param("T", vec![trait_bound("FromStr", vec![])]) ], "where_predicates": [] },
            "sig": { "inputs": [], "output": { "generic": "T" } }
        });
        assert!(parse_fn_item("parse", &fd, &HashMap::new(), None).is_none());
    }

    #[test]
    fn test_parse_fn_item_nongeneric_unchanged() {
        // fn len(s: &str) -> u64  : no generics, behaves exactly as before
        let fd = serde_json::json!({
            "header": { "is_async": false, "is_unsafe": false },
            "generics": { "params": [], "where_predicates": [] },
            "sig": { "inputs": [ ["s", borrowed(prim("str"))] ], "output": prim("u64") }
        });
        let f = parse_fn_item("len", &fd, &HashMap::new(), None).unwrap();
        assert_eq!(f.params[0].sky_type, "String");
        assert_eq!(f.results[0].sky_type, "Int");
    }

    #[test]
    fn test_into_iterator_u8() {
        // IntoIterator<Item = u8>  -> Vec<u8> (List Int). Item is an associated-type
        // constraint, carried in args.angle_bracketed.constraints, not in args.
        let b = serde_json::json!({ "trait_bound": { "trait": {
            "path": "IntoIterator", "name": "IntoIterator", "id": 0,
            "args": { "angle_bracketed": { "args": [], "constraints": [
                { "name": "Item", "binding": { "equality": { "type": { "primitive": "u8" } } } }
            ] } }
        }, "modifier": "none" } });
        assert_eq!(bound_to_concrete(&b), Some(vec_u8_node()));
    }

    #[test]
    fn test_impl_trait_arg() {
        // fn write_all(data: impl AsRef<[u8]>) -> ()  : impl-Trait arg -> List Int
        let asref_u8 = trait_bound("AsRef", vec![serde_json::json!({ "slice": { "primitive": "u8" } })]);
        let fd = serde_json::json!({
            "header": { "is_async": false, "is_unsafe": false },
            "generics": { "params": [], "where_predicates": [] },
            "sig": { "inputs": [ ["data", { "impl_trait": [asref_u8] }] ], "output": null }
        });
        let f = parse_fn_item("write_all", &fd, &HashMap::new(), None).unwrap();
        assert_eq!(f.params[0].sky_type, "List Int");
        assert_eq!(f.params[0].rust_type, "Vec<u8>");

        // impl Trait with an unmappable bound -> drop
        let fd2 = serde_json::json!({
            "header": { "is_async": false, "is_unsafe": false },
            "generics": { "params": [], "where_predicates": [] },
            "sig": { "inputs": [ ["x", { "impl_trait": [trait_bound("FromStr", vec![])] }] ], "output": null }
        });
        assert!(parse_fn_item("f", &fd2, &HashMap::new(), None).is_none());
    }

    #[test]
    fn test_v2_concrete_node_builders() {
        // The new owned-concrete nodes for v2 entries:
        assert_eq!(sky(&i64_node()), "Int");
        assert_eq!(sky(&f64_node()), "Float");
        assert_eq!(sky(&usize_node()), "Int");

        // Owned String concretes for path/osstr-derived bounds; these are the
        // same `string_node()` from v1 — verify they still map cleanly.
        assert_eq!(sky(&string_node()), "String");
    }

    fn primitive(name: &str) -> serde_json::Value {
        serde_json::json!({ "primitive": name })
    }

    #[test]
    fn test_concrete_for_inner_type() {
        // The slice [u8] becomes Vec<u8> (List Int)
        let u8_slice = serde_json::json!({ "slice": { "primitive": "u8" } });
        assert_eq!(concrete_for_inner_type(&u8_slice), Some(vec_u8_node()));

        // The str primitive becomes String
        assert_eq!(concrete_for_inner_type(&primitive("str")), Some(string_node()));

        // A borrowed &str becomes String too
        let str_ref = serde_json::json!({ "borrowed_ref": { "lifetime": null, "is_mutable": false, "type": { "primitive": "str" } } });
        assert_eq!(concrete_for_inner_type(&str_ref), Some(string_node()));

        // resolved_path "String" / "PathBuf" / "OsString" / "Path" / "OsStr" all become String
        for name in ["String", "PathBuf", "OsString", "Path", "OsStr"] {
            let node = serde_json::json!({ "resolved_path": { "name": name, "path": name, "id": 0, "args": null } });
            assert_eq!(concrete_for_inner_type(&node), Some(string_node()),
                "expected {} -> String", name);
        }

        // Numeric primitives -> their owned concrete
        for name in ["i8", "i16", "i32", "i64", "isize", "u8", "u16", "u32", "u64", "usize"] {
            let r = concrete_for_inner_type(&primitive(name)).expect(&format!("missing: {}", name));
            assert_eq!(sky(&r), "Int", "bad sky for {}", name);
        }
        for name in ["f32", "f64"] {
            let r = concrete_for_inner_type(&primitive(name)).expect(&format!("missing: {}", name));
            assert_eq!(sky(&r), "Float", "bad sky for {}", name);
        }

        // Vec<u8> resolves to Vec<u8>
        let vec_u8 = path_with_args("Vec", vec![primitive("u8")]);
        assert_eq!(concrete_for_inner_type(&vec_u8), Some(vec_u8_node()));

        // Unknown -> None
        let unknown = serde_json::json!({ "resolved_path": { "name": "SomeWeirdType", "path": "SomeWeirdType", "id": 0, "args": null } });
        assert_eq!(concrete_for_inner_type(&unknown), None);
    }
}
