//! sky-ffi-inspect-rs — Rust crate inspector for Sky FFI bindings.
//!
//! Uses `cargo +nightly rustdoc --output-format json` to introspect crate
//! public APIs.  Crucially, rustdoc runs *after* macro expansion, so items
//! generated by proc macros and derive macros that are invisible to
//! source-level parsers (syn) are fully visible here.
//!
//! Output JSON matches the `PkgInfo` schema that FfiGen.hs consumes.
//! The output contract is unchanged from v0.1 — only the inspection
//! backend changed.
//!
//! Usage:
//!   sky-ffi-inspect-rs uuid                          # single crate
//!   sky-ffi-inspect-rs uuid chrono                   # multi → JSON array
//!   sky-ffi-inspect-rs --features v4 uuid            # with features

use serde::Serialize;
use std::collections::{HashMap, HashSet};
use std::path::PathBuf;
use std::process::Command;

// ── Output schema (FfiGen.hs PkgInfo) ─────────────────────────────────

#[derive(Serialize, Debug)]
#[serde(rename_all = "camelCase")]
struct Param {
    name: String,
    #[serde(rename = "type")]
    ty: String,
    #[serde(skip_serializing_if = "String::is_empty")]
    sky_type: String,
    #[serde(skip_serializing_if = "String::is_empty")]
    rust_type: String,
}

#[derive(Serialize, Debug)]
#[serde(rename_all = "camelCase")]
struct Function {
    name: String,
    params: Vec<Param>,
    results: Vec<Param>,
    variadic: bool,
    effect: String,
    exported: bool,
    #[serde(skip_serializing_if = "String::is_empty")]
    recv_type: String,
    #[serde(skip_serializing_if = "String::is_empty")]
    recv_rust_type: String,
    #[serde(skip_serializing_if = "String::is_empty")]
    method_name: String,
    #[serde(skip_serializing_if = "std::ops::Not::not")]
    is_field: bool,
    #[serde(skip_serializing_if = "std::ops::Not::not")]
    is_field_set: bool,
    #[serde(skip_serializing_if = "std::ops::Not::not")]
    is_pkg_var: bool,
}

#[derive(Serialize, Debug)]
#[serde(rename_all = "camelCase")]
struct PkgInfo {
    pkg: String,
    name: String,
    #[serde(skip_serializing_if = "String::is_empty")]
    version: String,
    functions: Vec<Function>,
    // Full `::`-paths of every PUBLIC module in the crate (e.g.
    // "chrono::format").  FfiGen glob-imports each (`use <mod>::*;`) so that
    // types re-exported only in submodules resolve by their bare name in the
    // generated wrappers.
    #[serde(skip_serializing_if = "Vec::is_empty")]
    modules: Vec<String>,
    errors: Vec<String>,
}

// ── Entry point ────────────────────────────────────────────────────────

fn main() {
    let raw_args: Vec<String> = std::env::args().skip(1).collect();

    let mut features: Vec<String> = Vec::new();
    let mut crate_args: Vec<String> = Vec::new();

    let mut i = 0;
    while i < raw_args.len() {
        if raw_args[i] == "--features" {
            i += 1;
            if i < raw_args.len() {
                for feat in raw_args[i].split(',') {
                    let f = feat.trim().to_string();
                    if !f.is_empty() {
                        features.push(f);
                    }
                }
            }
        } else {
            crate_args.push(raw_args[i].clone());
        }
        i += 1;
    }

    if crate_args.is_empty() {
        eprintln!("Usage: sky-ffi-inspect-rs [--features f1,f2] <crate-name> [crate-name...]");
        eprintln!();
        eprintln!("Requires nightly Rust: rustup toolchain install nightly");
        std::process::exit(1);
    }

    let results: Vec<PkgInfo> = crate_args
        .iter()
        .map(|name| inspect_crate(name, &features))
        .collect();

    let json = if crate_args.len() == 1 {
        serde_json::to_string_pretty(&results[0])
    } else {
        serde_json::to_string_pretty(&results)
    };

    match json {
        Ok(s) => println!("{}", s),
        Err(e) => {
            let err = PkgInfo {
                pkg: crate_args.join(" "),
                name: "error".into(),
                version: String::new(),
                functions: vec![],
                modules: vec![],
                errors: vec![format!("JSON serialization failed: {}", e)],
            };
            println!("{}", serde_json::to_string_pretty(&err).unwrap());
        }
    }
}

// ── Top-level inspection ───────────────────────────────────────────────

fn inspect_crate(crate_name: &str, features: &[String]) -> PkgInfo {
    match run_rustdoc(crate_name, features) {
        Ok((json_content, version)) => match serde_json::from_str::<serde_json::Value>(&json_content) {
            Ok(doc) => parse_rustdoc(&doc, crate_name, &version),
            Err(e) => pkg_error(crate_name, &format!("rustdoc JSON parse error: {}", e)),
        },
        Err(e) => pkg_error(crate_name, &e),
    }
}

/// Create a temporary Cargo project that depends on `crate_name`, run
/// `cargo +nightly rustdoc` with JSON output, and return the raw JSON
/// and the resolved crate version.
///
/// Handles thin re-export facades (e.g. `clap` re-exports `clap_builder`):
/// if the first rustdoc run produces 0 functions, we scan the JSON for glob
/// `pub use other_crate::*` re-exports and re-run on the underlying crate.
fn run_rustdoc(crate_name: &str, features: &[String]) -> Result<(String, String), String> {
    let tmp = tempfile::tempdir().map_err(|e| format!("tempdir: {}", e))?;
    let dir = tmp.path();

    let safe_name = crate_name.replace('-', "_");
    let dep_entry = build_dep_entry(crate_name, features);

    let toml_content = format!(
        r#"[package]
name = "_sky_ffi_probe_{safe_name}"
version = "0.1.0"
edition = "2021"

[dependencies]
{dep_entry}
"#
    );

    let src_dir = dir.join("src");
    std::fs::create_dir_all(&src_dir).map_err(|e| format!("mkdir src: {}", e))?;
    std::fs::write(dir.join("Cargo.toml"), &toml_content)
        .map_err(|e| format!("write Cargo.toml: {}", e))?;
    std::fs::write(src_dir.join("lib.rs"), "// placeholder\n")
        .map_err(|e| format!("write lib.rs: {}", e))?;

    let manifest_str = dir.join("Cargo.toml").to_string_lossy().to_string();
    let target_dir = dir.join("target");

    // Fetch first (uses cargo cache — fast on repeated calls)
    fetch_dep(&manifest_str)?;

    let (json_content, version) =
        run_rustdoc_package(crate_name, &manifest_str, &target_dir, &safe_name)?;

    // If 0 public functions were found, the crate may be a thin re-export
    // facade (e.g. `clap` is just `pub use clap_builder::*`).  Detect glob
    // re-exports in the JSON and re-run on the underlying crate.
    let has_fns = json_has_functions(&json_content);
    if !has_fns {
        if let Some(underlying) = find_glob_reexport_source(&json_content) {
            let under_safe = underlying.replace('-', "_");
            if let Ok((under_json, under_ver)) =
                run_rustdoc_package(&underlying, &manifest_str, &target_dir, &under_safe)
            {
                if json_has_functions(&under_json) {
                    return Ok((under_json, under_ver));
                }
            }
        }
    }

    Ok((json_content, version))
}

/// Run `cargo +nightly rustdoc --package pkg` and return the JSON content.
fn run_rustdoc_package(
    package_name: &str,
    manifest_str: &str,
    target_dir: &PathBuf,
    safe_name: &str,
) -> Result<(String, String), String> {
    let output = Command::new("cargo")
        .args([
            "+nightly",
            "rustdoc",
            "--package",
            package_name,
            "--lib",          // pin to library target; avoids "extra arguments"
                              // errors on crates with binary or example targets.
            "--manifest-path",
            manifest_str,
            "--target-dir",
            target_dir.to_str().unwrap(),
            "--quiet",
            "--",
            "--output-format",
            "json",
            "-Z",
            "unstable-options",
        ])
        .output()
        .map_err(|e| {
            format!(
                "cargo +nightly rustdoc failed: {}.\n\
                 Is nightly installed? Run: rustup toolchain install nightly",
                e
            )
        })?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr).to_string();
        if stderr.contains("toolchain") && stderr.contains("not installed") {
            return Err(format!(
                "nightly toolchain not found. Install it with:\n  rustup toolchain install nightly\n\n{}",
                stderr
            ));
        }
        return Err(format!("cargo rustdoc failed:\n{}", stderr));
    }

    // Locate the JSON file under target/doc/
    let doc_dir = target_dir.join("doc");
    let json_path = find_rustdoc_json(&doc_dir, safe_name).ok_or_else(|| {
        format!(
            "rustdoc JSON not found in {}. Expected {}.json",
            doc_dir.display(),
            safe_name
        )
    })?;

    let content = std::fs::read_to_string(&json_path)
        .map_err(|e| format!("read {}: {}", json_path.display(), e))?;
    let version = extract_crate_version(&content).unwrap_or_default();

    Ok((content, version))
}

/// Return true if the rustdoc JSON contains at least one public function.
fn json_has_functions(json: &str) -> bool {
    if let Ok(doc) = serde_json::from_str::<serde_json::Value>(json) {
        if let Some(index) = doc["index"].as_object() {
            return index.values().any(|item| {
                item.get("inner")
                    .and_then(|i| i.get("function"))
                    .is_some()
            });
        }
    }
    false
}

/// Scan the rustdoc JSON index for a glob re-export (`pub use other_crate::*`)
/// and return the source crate name.  Used to follow thin re-export facades.
fn find_glob_reexport_source(json: &str) -> Option<String> {
    let doc: serde_json::Value = serde_json::from_str(json).ok()?;
    let index = doc["index"].as_object()?;
    for item in index.values() {
        if let Some(use_inner) = item.get("inner").and_then(|i| i.get("use")) {
            if use_inner["is_glob"].as_bool().unwrap_or(false) {
                if let Some(src) = use_inner["source"].as_str() {
                    // Skip stdlib-style re-exports (e.g. re-exporting from std::)
                    if !src.starts_with("std") && !src.starts_with("core")
                        && !src.starts_with("alloc")
                    {
                        return Some(src.to_string());
                    }
                }
            }
        }
    }
    None
}

fn find_rustdoc_json(doc_dir: &PathBuf, safe_name: &str) -> Option<PathBuf> {
    // Direct match first
    let direct = doc_dir.join(format!("{}.json", safe_name));
    if direct.exists() {
        return Some(direct);
    }
    // Scan directory for any .json file (handles edge cases in crate name casing)
    if let Ok(entries) = std::fs::read_dir(doc_dir) {
        for entry in entries.flatten() {
            let name = entry.file_name();
            let n = name.to_string_lossy();
            if n.ends_with(".json") && !n.starts_with('_') {
                return Some(entry.path());
            }
        }
    }
    None
}

fn fetch_dep(manifest_str: &str) -> Result<(), String> {
    // Offline first (cache hit, fast)
    if let Ok(o) = Command::new("cargo")
        .args(["fetch", "--offline", "--manifest-path", manifest_str])
        .output()
    {
        if o.status.success() {
            return Ok(());
        }
    }
    // Fall back to network
    let o = Command::new("cargo")
        .args(["fetch", "--manifest-path", manifest_str])
        .output()
        .map_err(|e| format!("cargo fetch: {}", e))?;
    if o.status.success() {
        Ok(())
    } else {
        Err(format!(
            "cargo fetch failed: {}",
            String::from_utf8_lossy(&o.stderr)
        ))
    }
}

fn build_dep_entry(crate_name: &str, features: &[String]) -> String {
    if features.is_empty() {
        format!("{} = \"*\"", crate_name)
    } else {
        let feats = features
            .iter()
            .map(|f| format!("\"{}\"", f))
            .collect::<Vec<_>>()
            .join(", ");
        format!(
            "{} = {{ version = \"*\", features = [{}] }}",
            crate_name, feats
        )
    }
}

fn extract_crate_version(json: &str) -> Option<String> {
    let doc: serde_json::Value = serde_json::from_str(json).ok()?;
    doc["crate_version"].as_str().map(|s| s.to_string())
}

// ── Parse rustdoc JSON → PkgInfo ───────────────────────────────────────

fn parse_rustdoc(doc: &serde_json::Value, crate_name: &str, version: &str) -> PkgInfo {
    // Make the crate-local public-path map available to
    // rustdoc_type_to_rust_str so it can fully-qualify opaque types.  Must be
    // set BEFORE any function is parsed (parse_fn_item -> rust_str reads it).
    REACHABLE_PATHS.with(|c| *c.borrow_mut() = collect_reachable_paths(doc));
    ALIAS_MAP.with(|c| *c.borrow_mut() = collect_aliases(doc));

    let index = match doc["index"].as_object() {
        Some(idx) => idx,
        None => return pkg_error(crate_name, "rustdoc JSON missing 'index' field"),
    };

    let aliases: HashMap<String, String> = HashMap::new();
    let mut functions: Vec<Function> = Vec::new();
    // Maps Sky type name → full Rust type string (may include generic params).
    // Used by emit_display_fromstr_bridges to carry the concrete Rust type
    // through to FfiGen so it can detect generic receivers and emit
    // `impl Display` / `impl FromStr` bounds rather than bare type names.
    let mut display_types: HashMap<String, String> = HashMap::new();
    let mut fromstr_types: HashMap<String, String> = HashMap::new();
    let mut errors: Vec<String> = Vec::new();

    // First pass: collect the IDs of every item that belongs to an impl or
    // trait `items` list — i.e. every associated function / method.  In the
    // flat rustdoc index, an associated function (e.g. `NaiveDate::from_ymd`)
    // appears BOTH as a standalone `function` item AND inside the owning
    // impl's `items` list.  Emitting the standalone copy as a free function
    // would generate a bogus `crate::from_ymd(..)` call that doesn't exist.
    // We skip the standalone copy here; the impl-block walk below emits the
    // correct receiver-tagged variant (`NaiveDate::from_ymd` / `arg0.method`).
    let mut associated_ids: HashSet<String> = HashSet::new();
    for (_, item) in index {
        let inner = &item["inner"];
        for kind in ["impl", "trait"] {
            if let Some(block) = inner.get(kind) {
                if let Some(items) = block.get("items").and_then(|i| i.as_array()) {
                    for mid in items {
                        associated_ids.insert(item_id_to_str(mid));
                    }
                }
            }
        }
    }

    for (item_id, item) in index {
        // Only items from this crate (crate_id == 0); deps have crate_id > 0
        let crate_id = item["crate_id"].as_u64().unwrap_or(1);
        if crate_id != 0 {
            continue;
        }

        let name = item["name"].as_str().unwrap_or("").to_string();
        let inner = &item["inner"];

        // Free function — must be public AND not an associated item of an
        // impl/trait (those are handled by the impl-block walk with a receiver).
        if let Some(fn_data) = inner.get("function") {
            if is_public(item) && !associated_ids.contains(item_id.as_str()) {
                if let Some(f) = parse_fn_item(&name, fn_data, &aliases, None) {
                    functions.push(f);
                }
            }
        }

        // Impl block — includes derive-generated trait impls.
        // Impl blocks always have visibility "default" (they don't have their
        // own visibility in Rust — it's inherited from the type), so we must
        // NOT filter by is_public() here.
        // The self type is under "for" (NOT "for_") in the rustdoc JSON.
        if let Some(impl_data) = inner.get("impl") {
            // "for" is a Rust keyword but JSON keys can be anything.
            let for_val = impl_data.get("for").or_else(|| impl_data.get("for_"));
            let self_sky = for_val
                .map(|v| rustdoc_type_to_sky(v, &aliases))
                .unwrap_or_default();
            let self_rust = for_val
                .map(|v| rustdoc_type_to_rust_str(v))
                .unwrap_or_default();

            if self_sky.is_empty() {
                continue;
            }

            // Track Display / FromStr for synthetic bridge functions
            let trait_name = impl_data
                .get("trait")
                .and_then(|t| t.as_object())
                .and_then(|t| t.get("name").or_else(|| t.get("path")))
                .and_then(|n| n.as_str())
                .unwrap_or("");
            if trait_name == "Display" || trait_name.ends_with("::Display") {
                // key = Sky type name; value = full Rust type (may have generics)
                display_types.entry(self_sky.clone()).or_insert_with(|| self_rust.clone());
            }
            if trait_name == "FromStr" || trait_name.ends_with("::FromStr") {
                fromstr_types.entry(self_sky.clone()).or_insert_with(|| self_rust.clone());
            }

            // Walk method items.
            // Item IDs may be integers (new format) or strings (old format).
            if let Some(items) = impl_data["items"].as_array() {
                for method_id in items {
                    let id = item_id_to_str(method_id);
                    if let Some(method_item) = index.get(&id) {
                        if !is_public(method_item) {
                            continue;
                        }
                        let method_name = method_item["name"].as_str().unwrap_or("");
                        if let Some(fn_data) = method_item["inner"].get("function") {
                            if let Some(f) =
                                parse_fn_item(method_name, fn_data, &aliases, Some((&self_sky, &self_rust)))
                            {
                                functions.push(f);
                            }
                        }
                    }
                }
            }
        }
    }

    // Synthetic to_string / from_string bridge functions (Display/FromStr)
    emit_display_fromstr_bridges(&mut functions, &display_types, &fromstr_types);

    // Drop functions whose param/result/receiver types can't be named in the
    // generated wrapper: impl-level generics (`Tz`), private crate types, and
    // external types whose canonical path runs through a private module.  After
    // qualification, a reachable type appears as `crate::Path::Type`; anything
    // still bare-and-unknown is unresolved.  `to_string` bridges are exempt —
    // FfiGen emits them with an `impl std::fmt::Display` bound and never spells
    // the receiver type.
    functions.retain(|f| f.method_name == "to_string" || fn_types_nameable(f));

    if functions.is_empty() && !errors.is_empty() {
        // surface errors visibly
        errors.insert(0, format!("{}: 0 functions extracted", crate_name));
    }

    PkgInfo {
        pkg: crate_name.to_string(),
        name: crate_name.to_string(),
        version: version.to_string(),
        functions,
        modules: collect_public_modules(doc),
        errors,
    }
}

/// Collect the `::`-joined paths of every PUBLIC module defined in this crate
/// (crate_id == 0).  FfiGen glob-imports each so that types re-exported only
/// inside a submodule (e.g. `chrono::format::ParseErrorKind`) resolve by their
/// bare name in the generated wrappers.  Private modules are excluded — they
/// can't be `use`d — and so are crates' synthetic/hidden internals.
fn collect_public_modules(doc: &serde_json::Value) -> Vec<String> {
    let index = match doc["index"].as_object() {
        Some(i) => i,
        None => return vec![],
    };
    let paths = doc["paths"].as_object();
    let mut mods: Vec<String> = Vec::new();
    for (id, item) in index {
        let inner = &item["inner"];
        if inner.get("module").is_some()
            && item["crate_id"].as_u64().unwrap_or(1) == 0
            && is_public(item)
        {
            if let Some(segs) = paths
                .and_then(|m| m.get(id))
                .and_then(|e| e.get("path"))
                .and_then(|p| p.as_array())
            {
                let joined: Vec<String> = segs
                    .iter()
                    .filter_map(|s| s.as_str().map(String::from))
                    .collect();
                if !joined.is_empty() {
                    mods.push(joined.join("::"));
                }
            }
        }
    }
    mods.sort();
    mods.dedup();
    mods
}

fn is_public(item: &serde_json::Value) -> bool {
    item["visibility"].as_str() == Some("public")
}

/// Parse a function item from the rustdoc JSON index.
///
/// `recv` is `Some((sky_type, rust_type))` for methods, `None` for free fns.
fn parse_fn_item(
    name: &str,
    fn_data: &serde_json::Value,
    aliases: &HashMap<String, String>,
    recv: Option<(&str, &str)>,
) -> Option<Function> {
    // Signature is under "sig" (format v38+) or "decl" (earlier).
    let sig = fn_data.get("sig").or_else(|| fn_data.get("decl"))?;

    let inputs = sig["inputs"].as_array()?;
    let output = &sig["output"];

    let is_async = fn_data["header"]["is_async"].as_bool().unwrap_or(false)
        || fn_data["header"]["async_"].as_bool().unwrap_or(false);

    // Skip `unsafe fn`: the generated wrapper calls it outside an `unsafe`
    // block, and auto-exposing unsafe constructors (e.g. new_unchecked) to
    // Sky would bypass the very invariants `unsafe` exists to protect.
    let is_unsafe = fn_data["header"]["is_unsafe"].as_bool().unwrap_or(false)
        || fn_data["header"]["unsafe_"].as_bool().unwrap_or(false);
    if is_unsafe {
        return None;
    }

    // Skip generic functions — type parameters can't be resolved without
    // a concrete call site.  This matches the previous syn-based behaviour.
    if let Some(params) = fn_data["generics"]["params"].as_array() {
        if !params.is_empty() {
            return None;
        }
    }

    let mut params: Vec<Param> = Vec::new();

    // Determine if this is an instance method by checking whether `self`
    // appears as the first entry in sig["inputs"].  Associated (static)
    // functions don't have a self input even though they live in an impl block.
    let has_self_in_inputs = inputs
        .first()
        .and_then(|i| i[0].as_str())
        .map(|n| n == "self")
        .unwrap_or(false);

    // For instance methods: push the receiver as first param so FfiGen
    // can generate `arg0.method(rest...)`.  For static/associated functions
    // in an impl block (recv.is_some() but no self input): don't push a
    // receiver param — FfiGen will use `RecvType::fn(args)` via isStaticFn.
    if let Some((sky_ty, rust_ty)) = recv {
        if has_self_in_inputs {
            params.push(Param {
                name: "self".into(),
                ty: sky_ty.to_string(),
                sky_type: sky_ty.to_string(),
                rust_type: rust_ty.to_string(),
            });
        }
    }

    // Ordinary parameters: inputs is [(name, type_json)].
    // Skip the "self" entry — it is already accounted for by the receiver
    // push above (instance method) or is not needed (static method).
    for input in inputs {
        let param_name = input[0].as_str().unwrap_or("_");
        if param_name == "self" {
            continue;
        }
        let type_json = &input[1];
        let sky = rustdoc_type_to_sky(type_json, aliases);
        let rust = rustdoc_type_to_rust_str(type_json);
        // `Self` in a parameter position means "the receiver type" (e.g.
        // `fn signed_duration_since(self, rhs: Self)`, or nested as
        // `Option<Self>`).  `Self` is not valid in a free-function signature,
        // so substitute the concrete receiver type token throughout.
        let (rsky, rrust) = recv.unwrap_or(("", ""));
        let sky = subst_self(&sky, rsky);
        let rust = subst_self(&rust, rrust);
        params.push(Param {
            name: param_name.to_string(),
            ty: sky.clone(),
            sky_type: sky,
            rust_type: rust,
        });
    }

    // Return type
    let mut results: Vec<Param> = Vec::new();
    if !output.is_null() {
        let sky = rustdoc_type_to_sky(output, aliases);
        let rust = rustdoc_type_to_rust_str(output);
        // Substitute `Self` (possibly nested, e.g. `Option<Self>`) with the
        // concrete receiver type so the wrapper's return type is valid Rust.
        let (rsky, rrust) = recv.unwrap_or(("", ""));
        let sky = subst_self(&sky, rsky);
        let rust = subst_self(&rust, rrust);
        if sky != "()" {
            results.push(Param {
                name: String::new(),
                ty: sky.clone(),
                sky_type: sky,
                rust_type: rust,
            });
        }
    }

    // Skip functions whose params or results carry a lifetime parameter
    // (e.g. `Item<'_>`, `StrftimeItems<'a>`, `&'a str`).  Such types are tied
    // to a borrow scope and cannot be expressed in a monomorphic, owned FFI
    // wrapper — the wrapper signature would reference an undeclared lifetime.
    // These are iterator / borrowed-view types that aren't usable from Sky
    // anyway, so dropping them is the correct boundary behaviour.
    let touches_lifetime = params.iter().any(|p| has_lifetime(&p.rust_type))
        || results.iter().any(|p| has_lifetime(&p.rust_type));
    if touches_lifetime {
        return None;
    }

    // Skip functions whose RESULT is a borrow (`&mut Builder` from a builder
    // setter, a nested `(.., &[u8; 8])` tuple, `&InnerType`).  A borrowed
    // return binds to a lifetime the owned wrapper can't supply (E0106) or
    // needs a ToOwned impl that may not exist (E0599).  Plain `&str`/`&String`
    // is fine — FfiGen copies it to an owned String.  References in PARAMETER
    // position are unaffected (the wrapper takes an owned value and borrows).
    let result_borrows = results.iter().any(|p| {
        let rt = p.rust_type.trim();
        rt.contains('&') && rt != "&str" && rt != "&String"
    });
    if result_borrows {
        return None;
    }

    // Skip fixed-size arrays / slices (`[u8; 16]`, `&[u8]`, `&[u8; 6]`).  Sky's
    // `Bytes` maps to `Vec<u8>`, which doesn't coerce to a fixed-size array or
    // borrowed slice parameter, and such a result can't be returned by value.
    // (`Vec<u8>` itself has no brackets and is unaffected.)
    let has_array_or_slice = params
        .iter()
        .chain(results.iter())
        .any(|p| p.rust_type.contains('['));
    if has_array_or_slice {
        return None;
    }

    let effect = classify_effect(output, &params, is_async);
    let (recv_sky, recv_rust) = recv.unwrap_or(("", ""));

    Some(Function {
        name: name.to_string(),
        params,
        results,
        variadic: false,
        effect,
        exported: true,
        recv_type: recv_sky.to_string(),
        recv_rust_type: recv_rust.to_string(),
        method_name: if recv.is_some() { name.to_string() } else { String::new() },
        is_field: false,
        is_field_set: false,
        is_pkg_var: false,
    })
}

fn is_ident_byte(c: u8) -> bool {
    c.is_ascii_alphanumeric() || c == b'_'
}

thread_local! {
    // Crate-local type id -> fully-qualified public path (see
    // collect_reachable_paths).  Used to qualify opaque types unambiguously.
    static REACHABLE_PATHS: std::cell::RefCell<HashMap<String, String>> =
        std::cell::RefCell::new(HashMap::new());

    // Crate-local NON-generic type-alias id -> the aliased type JSON.  Lets the
    // type converters see through aliases like `uuid::Bytes = [u8; 16]` so the
    // array/slice filter drops constructors that can't take a Sky Vec<u8>.
    static ALIAS_MAP: std::cell::RefCell<HashMap<String, serde_json::Value>> =
        std::cell::RefCell::new(HashMap::new());
}

/// Fully-qualified public path of a crate-local type by its rustdoc id, if
/// reachable via a public module.  None for unreachable (private) types and
/// for external-crate types (which are dropped by the nameability filter).
fn reachable_local_path(id: &serde_json::Value) -> Option<String> {
    let key = item_id_to_str(id);
    REACHABLE_PATHS.with(|c| c.borrow().get(&key).cloned())
}

/// If `id` is a crate-local non-generic type alias, return the aliased type.
fn resolve_alias(id: &serde_json::Value) -> Option<serde_json::Value> {
    let key = item_id_to_str(id);
    ALIAS_MAP.with(|c| c.borrow().get(&key).cloned())
}

/// Build the id -> aliased-type map for every crate-local, NON-generic type
/// alias (`pub type Bytes = [u8; 16];`).  Generic aliases are skipped — their
/// definitions reference the alias's own type params, which we can't bind.
fn collect_aliases(doc: &serde_json::Value) -> HashMap<String, serde_json::Value> {
    let mut out = HashMap::new();
    let index = match doc["index"].as_object() {
        Some(i) => i,
        None => return out,
    };
    for (id, item) in index {
        if item["crate_id"].as_u64().unwrap_or(1) != 0 {
            continue;
        }
        let alias = item["inner"]
            .get("type_alias")
            .or_else(|| item["inner"].get("typedef"));
        if let Some(a) = alias {
            let generic = a["generics"]["params"]
                .as_array()
                .map(|p| !p.is_empty())
                .unwrap_or(false);
            if generic {
                continue;
            }
            if let Some(ty) = a.get("type").or_else(|| a.get("type_")) {
                out.insert(id.clone(), ty.clone());
            }
        }
    }
    out
}

/// Replace every whole-word `Self` token in a type string with `replacement`.
/// Used to monomorphise `Self`-typed params/results to the concrete receiver
/// type (`Option<Self>` -> `Option<NaiveDate>`).  Type strings are ASCII.
fn subst_self(ty: &str, replacement: &str) -> String {
    if replacement.is_empty() || !ty.contains("Self") {
        return ty.to_string();
    }
    let b = ty.as_bytes();
    let mut out = String::new();
    let mut i = 0;
    while i < b.len() {
        if b[i..].starts_with(b"Self")
            && (i == 0 || !is_ident_byte(b[i - 1]))
            && (i + 4 >= b.len() || !is_ident_byte(b[i + 4]))
        {
            out.push_str(replacement);
            i += 4;
        } else {
            out.push(b[i] as char);
            i += 1;
        }
    }
    out
}

/// Container / std-prelude type names that are always nameable in generated
/// wrappers, regardless of crate re-exports.  Anything else with an
/// uppercase-initial name must be reachable via the crate's public modules.
const ALWAYS_NAMEABLE: &[&str] = &[
    "Option", "Result", "Vec", "Box", "Rc", "Arc", "Mutex", "RwLock", "Cell",
    "RefCell", "HashMap", "BTreeMap", "HashSet", "BTreeSet", "VecDeque", "Cow",
    "String",
];

const TYPE_KINDS: &[&str] =
    &["struct", "enum", "trait", "type_alias", "typedef", "union", "primitive"];

fn item_is_type(it: &serde_json::Value) -> bool {
    let ik = &it["inner"];
    TYPE_KINDS.iter().any(|k| ik.get(*k).is_some())
}

/// True if a Rust type string is fully nameable in a generated wrapper: every
/// uppercase-initial token is either already qualified (preceded by `::`, e.g.
/// `chrono::NaiveDate`, `std::time::Duration`) or an always-nameable container
/// (`Option`, `Result`, `Vec`, …).  A *bare* uppercase token that is neither
/// means an unresolved type — an impl-level generic (`Tz`), a private crate
/// type, or an external type with no public path — so the function is dropped.
fn type_is_nameable(ty: &str) -> bool {
    let b = ty.as_bytes();
    let mut i = 0;
    while i < b.len() {
        if b[i].is_ascii_alphabetic() || b[i] == b'_' {
            let start = i;
            while i < b.len() && is_ident_byte(b[i]) {
                i += 1;
            }
            let tok = &ty[start..i];
            if tok.as_bytes()[0].is_ascii_uppercase() {
                let qualified = start >= 2 && &ty[start - 2..start] == "::";
                if !qualified && !ALWAYS_NAMEABLE.contains(&tok) {
                    return false;
                }
            }
        } else {
            i += 1;
        }
    }
    true
}

/// All of a function's param / result / receiver types are nameable.
fn fn_types_nameable(f: &Function) -> bool {
    f.params.iter().all(|p| type_is_nameable(&p.rust_type))
        && f.results.iter().all(|p| type_is_nameable(&p.rust_type))
        && (f.recv_rust_type.is_empty() || type_is_nameable(&f.recv_rust_type))
}

/// Map every crate-local type's rustdoc item id to a fully-qualified PUBLIC
/// path (`chrono::NaiveDate`, `chrono::format::Parsed`).  Walks each public
/// module, recording defined types as `<module-path>::<name>` and named
/// re-exports as `<module-path>::<reexport-name>`, following `use` edges into
/// other modules transitively.  Prefers the shortest path so root re-exports
/// win over deep submodule definitions.  rustdoc_type_to_rust_str uses this to
/// qualify opaque types unambiguously instead of relying on glob imports.
fn collect_reachable_paths(doc: &serde_json::Value) -> HashMap<String, String> {
    let mut out: HashMap<String, String> = HashMap::new();
    let index = match doc["index"].as_object() {
        Some(i) => i,
        None => return out,
    };
    let paths = doc["paths"].as_object();
    let mpath = |mid: &str| -> Option<String> {
        paths
            .and_then(|m| m.get(mid))
            .and_then(|e| e.get("path"))
            .and_then(|p| p.as_array())
            .map(|segs| {
                segs.iter()
                    .filter_map(|s| s.as_str())
                    .collect::<Vec<_>>()
                    .join("::")
            })
    };
    let insert_shorter = |out: &mut HashMap<String, String>, id: String, path: String| {
        if out.get(&id).map_or(true, |e| path.len() < e.len()) {
            out.insert(id, path);
        }
    };

    let mut stack: Vec<String> = Vec::new();
    for (id, item) in index {
        if item["inner"].get("module").is_some()
            && item["crate_id"].as_u64().unwrap_or(1) == 0
            && is_public(item)
        {
            stack.push(id.clone());
        }
    }

    let mut seen: HashSet<String> = HashSet::new();
    while let Some(mid) = stack.pop() {
        if !seen.insert(mid.clone()) {
            continue;
        }
        let mp = match mpath(&mid) {
            Some(p) => p,
            None => continue,
        };
        let module = match index.get(&mid).and_then(|it| it["inner"].get("module")) {
            Some(m) => m,
            None => continue,
        };
        let items = match module["items"].as_array() {
            Some(a) => a,
            None => continue,
        };
        for child in items {
            let cid = item_id_to_str(child);
            let it = match index.get(&cid) {
                Some(x) => x,
                None => continue,
            };
            if item_is_type(it) {
                if let Some(n) = it["name"].as_str() {
                    insert_shorter(&mut out, cid.clone(), format!("{}::{}", mp, n));
                }
            }
            if let Some(u) = it["inner"].get("use") {
                let tid = u.get("id").map(item_id_to_str);
                if !u["is_glob"].as_bool().unwrap_or(false) {
                    if let (Some(n), Some(tids)) = (u["name"].as_str(), tid.as_ref()) {
                        if index.get(tids).map(item_is_type).unwrap_or(false) {
                            insert_shorter(&mut out, tids.clone(), format!("{}::{}", mp, n));
                        }
                    }
                }
                if let Some(tids) = tid {
                    if index
                        .get(&tids)
                        .and_then(|x| x["inner"].get("module"))
                        .is_some()
                    {
                        stack.push(tids);
                    }
                }
            }
        }
    }
    out
}

/// True if a Rust type string contains a lifetime token (`'a`, `'static`,
/// `'_`).  A `'` in a type string is always a lifetime (char literals never
/// appear in type positions), so detecting `'` followed by an identifier
/// char is sufficient and unambiguous.
fn has_lifetime(ty: &str) -> bool {
    let bytes = ty.as_bytes();
    for i in 0..bytes.len() {
        if bytes[i] == b'\'' {
            if let Some(&next) = bytes.get(i + 1) {
                if next.is_ascii_alphanumeric() || next == b'_' {
                    return true;
                }
            }
        }
    }
    false
}

fn classify_effect(
    output: &serde_json::Value,
    _params: &[Param],
    is_async: bool,
) -> String {
    if is_async {
        return "effectful".into();
    }
    if is_future_type(output) {
        return "effectful".into();
    }
    let sky = rustdoc_type_to_sky(output, &HashMap::new());
    if sky.starts_with("Result ") {
        return "fallible".into();
    }
    if sky.starts_with("Task ") {
        return "effectful".into();
    }
    "pure".into()
}

fn is_future_type(val: &serde_json::Value) -> bool {
    if let Some(rp) = val.get("resolved_path") {
        let n = rp["name"].as_str().unwrap_or("");
        if n == "Pin" || n == "Future" || n == "BoxFuture" {
            return true;
        }
    }
    false
}

// ── Synthetic bridge functions ─────────────────────────────────────────

fn emit_display_fromstr_bridges(
    functions: &mut Vec<Function>,
    display_types: &HashMap<String, String>,
    fromstr_types: &HashMap<String, String>,
) {
    for (sky_ty, rust_ty) in display_types {
        // recv_rust_type carries the FULL Rust type string (e.g. "DateTime<Tz>")
        // so FfiGen can detect generic params and emit `impl Display` instead of
        // a bare (possibly incomplete) type name.
        functions.push(Function {
            name: "to_string".into(),
            params: vec![Param {
                name: "self".into(),
                ty: sky_ty.clone(),
                sky_type: sky_ty.clone(),
                rust_type: rust_ty.clone(),
            }],
            results: vec![Param {
                name: String::new(),
                ty: "String".into(),
                sky_type: "String".into(),
                rust_type: String::new(),
            }],
            variadic: false,
            effect: "pure".into(),
            exported: true,
            recv_type: sky_ty.clone(),
            recv_rust_type: rust_ty.clone(),
            method_name: "to_string".into(),
            is_field: false,
            is_field_set: false,
            is_pkg_var: false,
        });
    }

    for (sky_ty, rust_ty) in fromstr_types {
        functions.push(Function {
            name: "from_string".into(),
            params: vec![Param {
                name: "s".into(),
                ty: "String".into(),
                sky_type: "String".into(),
                rust_type: "&str".into(),
            }],
            results: vec![Param {
                name: String::new(),
                ty: sky_ty.clone(),
                sky_type: sky_ty.clone(),
                rust_type: rust_ty.clone(),
            }],
            variadic: false,
            effect: "fallible".into(),
            exported: true,
            recv_type: sky_ty.clone(),
            recv_rust_type: rust_ty.clone(),
            method_name: "from_string".into(),
            is_field: false,
            is_field_set: false,
            is_pkg_var: false,
        });
    }
}

// ── rustdoc JSON type → Sky type string ───────────────────────────────
//
// The rustdoc JSON represents Rust types as tagged JSON objects.  The
// tag names have been stable across format versions 28–38+.  We
// gracefully fall back to "String" for unknown shapes rather than
// crashing, so format version drift degrades gracefully.

fn rustdoc_type_to_sky(val: &serde_json::Value, aliases: &HashMap<String, String>) -> String {
    if val.is_null() {
        return "()".to_string();
    }

    // { "primitive": "bool" | "usize" | "str" | … }
    if let Some(prim) = val.get("primitive") {
        return type_str_to_sky(prim.as_str().unwrap_or(""), aliases);
    }

    // { "borrowed_ref": { "type": … } }  →  strip the reference
    if let Some(inner) = val.get("borrowed_ref") {
        return rustdoc_type_to_sky(inner_type(inner), aliases);
    }

    // { "raw_pointer": { "type": … } }
    if let Some(inner) = val.get("raw_pointer") {
        return rustdoc_type_to_sky(inner_type(inner), aliases);
    }

    // { "resolved_path": { "name": "Vec", "args": { "angle_bracketed": … } } }
    if let Some(rp) = val.get("resolved_path") {
        // See through a crate-local non-generic alias (uuid::Bytes -> [u8;16]).
        if let Some(aliased) = rp.get("id").and_then(resolve_alias) {
            return rustdoc_type_to_sky(&aliased, aliases);
        }
        return resolve_path_to_sky(rp, aliases);
    }

    // { "tuple": [type, …] }
    if let Some(items) = val.get("tuple") {
        let parts: Vec<String> = items
            .as_array()
            .map(|arr| {
                arr.iter()
                    .map(|t| rustdoc_type_to_sky(t, aliases))
                    .collect()
            })
            .unwrap_or_default();
        return if parts.is_empty() {
            "()".to_string()
        } else {
            format!("({})", parts.join(", "))
        };
    }

    // { "slice": type }  →  List T
    if let Some(inner) = val.get("slice") {
        return format!("List {}", rustdoc_type_to_sky(inner, aliases));
    }

    // { "array": { "type": …, "len": "N" } }
    if let Some(arr) = val.get("array") {
        let inner = rustdoc_type_to_sky(inner_type(arr), aliases);
        // [u8; N] → Bytes, other fixed arrays → List T
        return if inner == "Int" {
            "Bytes".to_string()
        } else {
            format!("List {}", inner)
        };
    }

    // { "generic": "T" }  — unresolved type parameter
    if let Some(g) = val.get("generic") {
        return g.as_str().unwrap_or("String").to_string();
    }

    // impl Trait / dyn Trait — opaque
    if val.get("impl_trait").is_some() || val.get("dyn_trait").is_some() {
        return "String".to_string();
    }

    // Associated type path
    if let Some(qp) = val.get("qualified_path") {
        let name = qp["name"].as_str().unwrap_or("");
        return name.to_string();
    }

    "String".to_string()
}

fn resolve_path_to_sky(rp: &serde_json::Value, aliases: &HashMap<String, String>) -> String {
    // "name" (format <35) or "path" (format 35+) — try both
    let name = rp["name"]
        .as_str()
        .or_else(|| rp["path"].as_str())
        .unwrap_or("");
    let args = extract_angle_type_args(rp.get("args"), aliases);

    match name {
        "Vec" => format!(
            "List {}",
            args.first().cloned().unwrap_or_else(|| "String".into())
        ),
        "Option" => format!(
            "Maybe {}",
            args.first().cloned().unwrap_or_else(|| "String".into())
        ),
        "Box" | "Arc" | "Rc" | "Mutex" | "RwLock" | "Cell" | "RefCell" => {
            args.first().cloned().unwrap_or_else(|| name.to_string())
        }
        "String" | "str" | "OsStr" | "OsString" | "PathBuf" | "Path" => "String".to_string(),
        "HashMap" | "BTreeMap" | "IndexMap" | "AHashMap" => {
            let val = args.get(1).cloned().unwrap_or_else(|| "String".into());
            format!("Dict String {}", val)
        }
        "Result" => {
            // Rust Result<T, E>  →  Sky Result E T
            let ok = args.first().cloned().unwrap_or_else(|| "()".into());
            let err = args.get(1).cloned().unwrap_or_else(|| "String".into());
            format!("Result {} {}", err, ok)
        }
        "SkyResult" => {
            // SkyResult<E, A>  →  Result E A
            let err = args.first().cloned().unwrap_or_else(|| "String".into());
            let ok = args.get(1).cloned().unwrap_or_else(|| "()".into());
            format!("Result {} {}", err, ok)
        }
        "SkyError" => "Error".to_string(),
        "SkyTask" => {
            let err = args.first().cloned().unwrap_or_else(|| "Error".into());
            let ok = args.get(1).cloned().unwrap_or_else(|| "()".into());
            format!("Task {} {}", err, ok)
        }
        // async / future wrappers
        "Pin" => {
            // Pin<Box<dyn Future<Output = T>>>  →  Task Error T
            // Try to extract Output from the inner Future
            args.first()
                .map(|inner| {
                    if inner.starts_with("Task ") {
                        inner.clone()
                    } else {
                        format!("Task Error {}", inner)
                    }
                })
                .unwrap_or_else(|| "Task Error ()".into())
        }
        "Future" => {
            // Extract Output = T binding
            let output = extract_binding_type(rp.get("args"), "Output", aliases)
                .unwrap_or_else(|| "()".into());
            format!("Task Error {}", output)
        }
        _ => {
            // Strip module-path qualifier: std::collections::HashMap → HashMap
            let base = name.rsplit_once("::").map(|(_, last)| last).unwrap_or(name);
            aliases.get(base).cloned().unwrap_or_else(|| base.to_string())
        }
    }
}

/// Extract angle-bracket type arguments from a rustdoc args object.
/// Each entry looks like `{ "type": <type_json> }` (or lifetime, const — skip those).
fn extract_angle_type_args(
    args: Option<&serde_json::Value>,
    aliases: &HashMap<String, String>,
) -> Vec<String> {
    args.and_then(|a| a.get("angle_bracketed"))
        .and_then(|ab| ab.get("args"))
        .and_then(|a| a.as_array())
        .map(|arr| {
            arr.iter()
                .filter_map(|arg| {
                    arg.get("type")
                        .map(|t| rustdoc_type_to_sky(t, aliases))
                })
                .collect()
        })
        .unwrap_or_default()
}

/// Extract an associated-type binding (e.g. `Output = T`) from args.
fn extract_binding_type(
    args: Option<&serde_json::Value>,
    binding_name: &str,
    aliases: &HashMap<String, String>,
) -> Option<String> {
    let bindings = args?
        .get("angle_bracketed")?
        .get("bindings")?
        .as_array()?;
    for b in bindings {
        if b["name"].as_str() == Some(binding_name) {
            // binding value is under b["binding"]["equality"] in newer formats
            if let Some(ty) = b.get("binding").and_then(|bv| bv.get("equality")) {
                return Some(rustdoc_type_to_sky(ty, aliases));
            }
            // older format: b["value"] or b["type"]
            if let Some(ty) = b.get("value").or_else(|| b.get("type")) {
                return Some(rustdoc_type_to_sky(ty, aliases));
            }
        }
    }
    None
}

// ── rustdoc JSON type → Rust type string ──────────────────────────────
//
// Used to populate the `rustType` field in the output JSON that
// FfiGen.hs reads for coercion decisions.

fn rustdoc_type_to_rust_str(val: &serde_json::Value) -> String {
    if val.is_null() {
        return "()".to_string();
    }

    if let Some(prim) = val.get("primitive") {
        return prim.as_str().unwrap_or("()").to_string();
    }

    if let Some(inner) = val.get("borrowed_ref") {
        let m = if is_mutable(inner) { "mut " } else { "" };
        // rustdoc JSON stores lifetimes WITH the leading apostrophe already
        // (e.g. "'static", "'a").  Don't prepend another one.
        let lt = inner["lifetime"]
            .as_str()
            .map(|l| {
                let s = if l.starts_with('\'') { l.to_string() } else { format!("'{}", l) };
                format!("{} ", s)
            })
            .unwrap_or_default();
        return format!("&{}{}{}", lt, m, rustdoc_type_to_rust_str(inner_type(inner)));
    }

    if let Some(inner) = val.get("raw_pointer") {
        let m = if is_mutable(inner) { "mut" } else { "const" };
        return format!("*{} {}", m, rustdoc_type_to_rust_str(inner_type(inner)));
    }

    if let Some(rp) = val.get("resolved_path") {
        // See through a crate-local non-generic alias (uuid::Bytes -> [u8;16]),
        // so the array/slice filter sees the real shape.
        if let Some(aliased) = rp.get("id").and_then(resolve_alias) {
            return rustdoc_type_to_rust_str(&aliased);
        }
        let raw_name = rp["name"]
            .as_str()
            .or_else(|| rp["path"].as_str())
            .unwrap_or("");
        // For an EXTERNAL-crate type (crate_id != 0, e.g. `core::time::Duration`),
        // emit the fully-qualified path: it's unambiguous and avoids colliding
        // with a same-named crate-local re-export (chrono aliases `Duration`).
        // For a CRATE-LOCAL type strip to the last segment — the generated
        // bindings glob-import the crate's public modules so the bare name is
        // in scope; a `crate::`-prefixed path would wrongly resolve against the
        // sky-app crate.  External types whose canonical path runs through a
        // private module (e.g. `core::ops::range::RangeInclusive`) are emitted
        // verbatim but get dropped later by the nameability filter.
        // Qualify CRATE-LOCAL opaque types with their public path
        // (`chrono::NaiveDate`).  External/std types are left bare: the only
        // ones usable are the always-nameable containers (Vec, Option, …);
        // anything else (`Duration`, `RangeInclusive`) stays a bare unknown
        // and is dropped by the nameability filter, since std's rustdoc paths
        // route through private modules and can't be reproduced reliably.
        let qualified = rp.get("id").and_then(reachable_local_path);
        let name: String = match qualified {
            Some(full) => full,
            None => raw_name.rsplit("::").next().unwrap_or(raw_name).to_string(),
        };
        let name = name.as_str();
        let args: Vec<String> = rp
            .get("args")
            .and_then(|a| a.get("angle_bracketed"))
            .and_then(|ab| ab.get("args"))
            .and_then(|a| a.as_array())
            .map(|arr| {
                arr.iter()
                    .filter_map(|arg| {
                        if let Some(t) = arg.get("type") {
                            Some(rustdoc_type_to_rust_str(t))
                        } else if let Some(l) = arg.get("lifetime") {
                            // rustdoc JSON already includes the leading apostrophe
                            let s = l.as_str().unwrap_or("'a");
                            Some(if s.starts_with('\'') { s.to_string() } else { format!("'{}", s) })
                        } else {
                            None
                        }
                    })
                    .collect()
            })
            .unwrap_or_default();
        return if args.is_empty() {
            name.to_string()
        } else {
            format!("{}<{}>", name, args.join(", "))
        };
    }

    if let Some(items) = val.get("tuple") {
        let parts: Vec<String> = items
            .as_array()
            .map(|arr| arr.iter().map(|t| rustdoc_type_to_rust_str(t)).collect())
            .unwrap_or_default();
        return format!("({})", parts.join(", "));
    }

    if let Some(inner) = val.get("slice") {
        return format!("[{}]", rustdoc_type_to_rust_str(inner));
    }

    if let Some(arr) = val.get("array") {
        let len = arr["len"].as_str().unwrap_or("?");
        return format!("[{}; {}]", rustdoc_type_to_rust_str(inner_type(arr)), len);
    }

    if let Some(g) = val.get("generic") {
        return g.as_str().unwrap_or("_").to_string();
    }

    String::new()
}

// ── String-based type mapping (for primitives) ─────────────────────────

fn type_str_to_sky(s: &str, aliases: &HashMap<String, String>) -> String {
    let s = s.trim();

    if let Some(sky) = aliases.get(s) {
        return sky.clone();
    }

    match s {
        "str" | "String" | "OsStr" | "OsString" | "CStr" | "CString" => "String".into(),
        "bool" => "Bool".into(),
        "()" => "()".into(),
        "i8" | "i16" | "i32" | "i64" | "i128" | "isize" | "u8" | "u16" | "u32" | "u64"
        | "u128" | "usize" => "Int".into(),
        "f32" | "f64" => "Float".into(),
        "SkyError" | "Error" => "Error".into(),
        _ => {
            // Strip module path
            let base = s.rsplit_once("::").map(|(_, l)| l).unwrap_or(s);
            let base = base.split('<').next().unwrap_or(base).trim();
            if base.is_empty() {
                return "String".into();
            }
            // Lowercase primitive names
            match base {
                "string" | "str" => "String".into(),
                "bool" => "Bool".into(),
                "int" | "integer" => "Int".into(),
                "float" => "Float".into(),
                _ => base.to_string(),
            }
        }
    }
}

// ── Helpers ────────────────────────────────────────────────────────────

/// Fetch the wrapped inner type from a `borrowed_ref` / `raw_pointer` /
/// `array` node, tolerating rustdoc format drift: older formats use the
/// key `"type_"`, newer formats use `"type"`.  Returns the JSON null value
/// when neither is present (callers map that to `()`).
fn inner_type(wrapper: &serde_json::Value) -> &serde_json::Value {
    let t = &wrapper["type"];
    if !t.is_null() {
        t
    } else {
        &wrapper["type_"]
    }
}

/// Read a reference/pointer mutability flag, tolerating both the newer
/// `"is_mutable"` and older `"mutable"` rustdoc keys.
fn is_mutable(wrapper: &serde_json::Value) -> bool {
    wrapper["is_mutable"]
        .as_bool()
        .or_else(|| wrapper["mutable"].as_bool())
        .unwrap_or(false)
}

/// Convert a rustdoc item ID to a string key for index lookups.
/// Item IDs appear as integers in new format (35+) and strings in old format.
fn item_id_to_str(id: &serde_json::Value) -> String {
    if let Some(n) = id.as_u64() {
        return n.to_string();
    }
    id.as_str().unwrap_or("").to_string()
}

fn pkg_error(name: &str, msg: &str) -> PkgInfo {
    PkgInfo {
        pkg: name.into(),
        name: name.into(),
        version: String::new(),
        functions: vec![],
        modules: vec![],
        errors: vec![msg.into()],
    }
}

/// Split a comma-separated generic arg list respecting nested `<>` and `()`.
#[allow(dead_code)]
fn split_top_level(s: &str, sep: char) -> Vec<&str> {
    let mut result = Vec::new();
    let mut depth = 0i32;
    let mut start = 0;
    for (i, c) in s.char_indices() {
        match c {
            '<' | '(' => depth += 1,
            '>' | ')' => depth -= 1,
            _ if depth == 0 && c == sep => {
                result.push(s[start..i].trim());
                start = i + 1;
            }
            _ => {}
        }
    }
    if start < s.len() {
        result.push(s[start..].trim());
    }
    result
}

// ── Tests ──────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    fn sky(val: &serde_json::Value) -> String {
        rustdoc_type_to_sky(val, &HashMap::new())
    }

    fn prim(s: &str) -> serde_json::Value {
        serde_json::json!({ "primitive": s })
    }

    fn path(name: &str) -> serde_json::Value {
        // Use both "name" and "path" to cover old and new format versions.
        serde_json::json!({ "resolved_path": { "name": name, "path": name, "id": 0, "args": null } })
    }

    fn path_with_args(name: &str, args: Vec<serde_json::Value>) -> serde_json::Value {
        let type_args: Vec<serde_json::Value> = args
            .into_iter()
            .map(|t| serde_json::json!({ "type": t }))
            .collect();
        serde_json::json!({
            "resolved_path": {
                "name": name,
                "path": name,
                "id": 0,
                "args": {
                    "angle_bracketed": {
                        "args": type_args,
                        "bindings": []
                    }
                }
            }
        })
    }

    fn borrowed(inner: serde_json::Value) -> serde_json::Value {
        serde_json::json!({ "borrowed_ref": { "lifetime": null, "mutable": false, "type_": inner } })
    }

    #[test]
    fn test_primitives() {
        assert_eq!(sky(&prim("u64")), "Int");
        assert_eq!(sky(&prim("usize")), "Int");
        assert_eq!(sky(&prim("i32")), "Int");
        assert_eq!(sky(&prim("f32")), "Float");
        assert_eq!(sky(&prim("bool")), "Bool");
        assert_eq!(sky(&prim("str")), "String");
    }

    #[test]
    fn test_string_path() {
        assert_eq!(sky(&path("String")), "String");
        assert_eq!(sky(&path("OsString")), "String");
    }

    #[test]
    fn test_generic_containers() {
        assert_eq!(sky(&path_with_args("Vec", vec![prim("u64")])), "List Int");
        assert_eq!(
            sky(&path_with_args("Option", vec![path("String")])),
            "Maybe String"
        );
        assert_eq!(
            sky(&path_with_args("HashMap", vec![path("String"), prim("u64")])),
            "Dict String Int"
        );
    }

    #[test]
    fn test_result_and_sky_result() {
        // Rust Result<String, SkyError>  →  Sky Result Error String
        let r = path_with_args("Result", vec![path("String"), path("SkyError")]);
        assert_eq!(sky(&r), "Result Error String");

        // SkyResult<SkyError, String>  →  Sky Result Error String
        let sr = path_with_args("SkyResult", vec![path("SkyError"), path("String")]);
        assert_eq!(sky(&sr), "Result Error String");
    }

    #[test]
    fn test_borrowed_ref_stripped() {
        // &str → String
        assert_eq!(sky(&borrowed(prim("str"))), "String");
        // &Vec<u64> → List Int
        assert_eq!(
            sky(&borrowed(path_with_args("Vec", vec![prim("u64")]))),
            "List Int"
        );
    }
}
