//! sky-ffi-inspect-rs — Rust crate inspector for Sky FFI bindings.
//!
//! Uses `cargo +nightly rustdoc --output-format json` to introspect crate
//! public APIs.  Crucially, rustdoc runs *after* macro expansion, so items
//! generated by proc macros and derive macros that are invisible to
//! source-level parsers (syn) are fully visible here.
//!
//! Output JSON matches the `PkgInfo` schema that FfiGen.hs consumes.
//! The output contract is unchanged from v0.1 — only the inspection
//! backend changed.
//!
//! Usage:
//!   sky-ffi-inspect-rs uuid                          # single crate
//!   sky-ffi-inspect-rs uuid chrono                   # multi → JSON array
//!   sky-ffi-inspect-rs --features v4 uuid            # with features

use serde::Serialize;
use std::collections::{HashMap, HashSet};
use std::path::PathBuf;
use std::process::Command;

// ── Output schema (FfiGen.hs PkgInfo) ─────────────────────────────────

#[derive(Serialize, Debug)]
#[serde(rename_all = "camelCase")]
struct Param {
    name: String,
    #[serde(rename = "type")]
    ty: String,
    #[serde(skip_serializing_if = "String::is_empty")]
    sky_type: String,
    #[serde(skip_serializing_if = "String::is_empty")]
    rust_type: String,
}

#[derive(Serialize, Debug)]
#[serde(rename_all = "camelCase")]
struct Function {
    name: String,
    params: Vec<Param>,
    results: Vec<Param>,
    variadic: bool,
    effect: String,
    exported: bool,
    #[serde(skip_serializing_if = "String::is_empty")]
    recv_type: String,
    #[serde(skip_serializing_if = "String::is_empty")]
    recv_rust_type: String,
    #[serde(skip_serializing_if = "String::is_empty")]
    method_name: String,
    #[serde(skip_serializing_if = "std::ops::Not::not")]
    is_field: bool,
    #[serde(skip_serializing_if = "std::ops::Not::not")]
    is_field_set: bool,
    #[serde(skip_serializing_if = "std::ops::Not::not")]
    is_pkg_var: bool,
}

#[derive(Serialize, Debug)]
#[serde(rename_all = "camelCase")]
struct PkgInfo {
    pkg: String,
    name: String,
    #[serde(skip_serializing_if = "String::is_empty")]
    version: String,
    functions: Vec<Function>,
    errors: Vec<String>,
}

// ── Entry point ────────────────────────────────────────────────────────

fn main() {
    let raw_args: Vec<String> = std::env::args().skip(1).collect();

    let mut features: Vec<String> = Vec::new();
    let mut crate_args: Vec<String> = Vec::new();

    let mut i = 0;
    while i < raw_args.len() {
        if raw_args[i] == "--features" {
            i += 1;
            if i < raw_args.len() {
                for feat in raw_args[i].split(',') {
                    let f = feat.trim().to_string();
                    if !f.is_empty() {
                        features.push(f);
                    }
                }
            }
        } else {
            crate_args.push(raw_args[i].clone());
        }
        i += 1;
    }

    if crate_args.is_empty() {
        eprintln!("Usage: sky-ffi-inspect-rs [--features f1,f2] <crate-name> [crate-name...]");
        eprintln!();
        eprintln!("Requires nightly Rust: rustup toolchain install nightly");
        std::process::exit(1);
    }

    let results: Vec<PkgInfo> = crate_args
        .iter()
        .map(|name| inspect_crate(name, &features))
        .collect();

    let json = if crate_args.len() == 1 {
        serde_json::to_string_pretty(&results[0])
    } else {
        serde_json::to_string_pretty(&results)
    };

    match json {
        Ok(s) => println!("{}", s),
        Err(e) => {
            let err = PkgInfo {
                pkg: crate_args.join(" "),
                name: "error".into(),
                version: String::new(),
                functions: vec![],
                errors: vec![format!("JSON serialization failed: {}", e)],
            };
            println!("{}", serde_json::to_string_pretty(&err).unwrap());
        }
    }
}

// ── Top-level inspection ───────────────────────────────────────────────

fn inspect_crate(crate_name: &str, features: &[String]) -> PkgInfo {
    match run_rustdoc(crate_name, features) {
        Ok((json_content, version)) => match serde_json::from_str::<serde_json::Value>(&json_content) {
            Ok(doc) => parse_rustdoc(&doc, crate_name, &version),
            Err(e) => pkg_error(crate_name, &format!("rustdoc JSON parse error: {}", e)),
        },
        Err(e) => pkg_error(crate_name, &e),
    }
}

/// Create a temporary Cargo project that depends on `crate_name`, run
/// `cargo +nightly rustdoc` with JSON output, and return the raw JSON
/// and the resolved crate version.
///
/// Handles thin re-export facades (e.g. `clap` re-exports `clap_builder`):
/// if the first rustdoc run produces 0 functions, we scan the JSON for glob
/// `pub use other_crate::*` re-exports and re-run on the underlying crate.
fn run_rustdoc(crate_name: &str, features: &[String]) -> Result<(String, String), String> {
    let tmp = tempfile::tempdir().map_err(|e| format!("tempdir: {}", e))?;
    let dir = tmp.path();

    let safe_name = crate_name.replace('-', "_");
    let dep_entry = build_dep_entry(crate_name, features);

    let toml_content = format!(
        r#"[package]
name = "_sky_ffi_probe_{safe_name}"
version = "0.1.0"
edition = "2021"

[dependencies]
{dep_entry}
"#
    );

    let src_dir = dir.join("src");
    std::fs::create_dir_all(&src_dir).map_err(|e| format!("mkdir src: {}", e))?;
    std::fs::write(dir.join("Cargo.toml"), &toml_content)
        .map_err(|e| format!("write Cargo.toml: {}", e))?;
    std::fs::write(src_dir.join("lib.rs"), "// placeholder\n")
        .map_err(|e| format!("write lib.rs: {}", e))?;

    let manifest_str = dir.join("Cargo.toml").to_string_lossy().to_string();
    let target_dir = dir.join("target");

    // Fetch first (uses cargo cache — fast on repeated calls)
    fetch_dep(&manifest_str)?;

    let (json_content, version) =
        run_rustdoc_package(crate_name, &manifest_str, &target_dir, &safe_name)?;

    // If 0 public functions were found, the crate may be a thin re-export
    // facade (e.g. `clap` is just `pub use clap_builder::*`).  Detect glob
    // re-exports in the JSON and re-run on the underlying crate.
    let has_fns = json_has_functions(&json_content);
    if !has_fns {
        if let Some(underlying) = find_glob_reexport_source(&json_content) {
            let under_safe = underlying.replace('-', "_");
            if let Ok((under_json, under_ver)) =
                run_rustdoc_package(&underlying, &manifest_str, &target_dir, &under_safe)
            {
                if json_has_functions(&under_json) {
                    return Ok((under_json, under_ver));
                }
            }
        }
    }

    Ok((json_content, version))
}

/// Run `cargo +nightly rustdoc --package pkg` and return the JSON content.
fn run_rustdoc_package(
    package_name: &str,
    manifest_str: &str,
    target_dir: &PathBuf,
    safe_name: &str,
) -> Result<(String, String), String> {
    let output = Command::new("cargo")
        .args([
            "+nightly",
            "rustdoc",
            "--package",
            package_name,
            "--lib",          // pin to library target; avoids "extra arguments"
                              // errors on crates with binary or example targets.
            "--manifest-path",
            manifest_str,
            "--target-dir",
            target_dir.to_str().unwrap(),
            "--quiet",
            "--",
            "--output-format",
            "json",
            "-Z",
            "unstable-options",
        ])
        .output()
        .map_err(|e| {
            format!(
                "cargo +nightly rustdoc failed: {}.\n\
                 Is nightly installed? Run: rustup toolchain install nightly",
                e
            )
        })?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr).to_string();
        if stderr.contains("toolchain") && stderr.contains("not installed") {
            return Err(format!(
                "nightly toolchain not found. Install it with:\n  rustup toolchain install nightly\n\n{}",
                stderr
            ));
        }
        return Err(format!("cargo rustdoc failed:\n{}", stderr));
    }

    // Locate the JSON file under target/doc/
    let doc_dir = target_dir.join("doc");
    let json_path = find_rustdoc_json(&doc_dir, safe_name).ok_or_else(|| {
        format!(
            "rustdoc JSON not found in {}. Expected {}.json",
            doc_dir.display(),
            safe_name
        )
    })?;

    let content = std::fs::read_to_string(&json_path)
        .map_err(|e| format!("read {}: {}", json_path.display(), e))?;
    let version = extract_crate_version(&content).unwrap_or_default();

    Ok((content, version))
}

/// Return true if the rustdoc JSON contains at least one public function.
fn json_has_functions(json: &str) -> bool {
    if let Ok(doc) = serde_json::from_str::<serde_json::Value>(json) {
        if let Some(index) = doc["index"].as_object() {
            return index.values().any(|item| {
                item.get("inner")
                    .and_then(|i| i.get("function"))
                    .is_some()
            });
        }
    }
    false
}

/// Scan the rustdoc JSON index for a glob re-export (`pub use other_crate::*`)
/// and return the source crate name.  Used to follow thin re-export facades.
fn find_glob_reexport_source(json: &str) -> Option<String> {
    let doc: serde_json::Value = serde_json::from_str(json).ok()?;
    let index = doc["index"].as_object()?;
    for item in index.values() {
        if let Some(use_inner) = item.get("inner").and_then(|i| i.get("use")) {
            if use_inner["is_glob"].as_bool().unwrap_or(false) {
                if let Some(src) = use_inner["source"].as_str() {
                    // Skip stdlib-style re-exports (e.g. re-exporting from std::)
                    if !src.starts_with("std") && !src.starts_with("core")
                        && !src.starts_with("alloc")
                    {
                        return Some(src.to_string());
                    }
                }
            }
        }
    }
    None
}

fn find_rustdoc_json(doc_dir: &PathBuf, safe_name: &str) -> Option<PathBuf> {
    // Direct match first
    let direct = doc_dir.join(format!("{}.json", safe_name));
    if direct.exists() {
        return Some(direct);
    }
    // Scan directory for any .json file (handles edge cases in crate name casing)
    if let Ok(entries) = std::fs::read_dir(doc_dir) {
        for entry in entries.flatten() {
            let name = entry.file_name();
            let n = name.to_string_lossy();
            if n.ends_with(".json") && !n.starts_with('_') {
                return Some(entry.path());
            }
        }
    }
    None
}

fn fetch_dep(manifest_str: &str) -> Result<(), String> {
    // Offline first (cache hit, fast)
    if let Ok(o) = Command::new("cargo")
        .args(["fetch", "--offline", "--manifest-path", manifest_str])
        .output()
    {
        if o.status.success() {
            return Ok(());
        }
    }
    // Fall back to network
    let o = Command::new("cargo")
        .args(["fetch", "--manifest-path", manifest_str])
        .output()
        .map_err(|e| format!("cargo fetch: {}", e))?;
    if o.status.success() {
        Ok(())
    } else {
        Err(format!(
            "cargo fetch failed: {}",
            String::from_utf8_lossy(&o.stderr)
        ))
    }
}

fn build_dep_entry(crate_name: &str, features: &[String]) -> String {
    if features.is_empty() {
        format!("{} = \"*\"", crate_name)
    } else {
        let feats = features
            .iter()
            .map(|f| format!("\"{}\"", f))
            .collect::<Vec<_>>()
            .join(", ");
        format!(
            "{} = {{ version = \"*\", features = [{}] }}",
            crate_name, feats
        )
    }
}

fn extract_crate_version(json: &str) -> Option<String> {
    let doc: serde_json::Value = serde_json::from_str(json).ok()?;
    doc["crate_version"].as_str().map(|s| s.to_string())
}

// ── Parse rustdoc JSON → PkgInfo ───────────────────────────────────────

fn parse_rustdoc(doc: &serde_json::Value, crate_name: &str, version: &str) -> PkgInfo {
    let index = match doc["index"].as_object() {
        Some(idx) => idx,
        None => return pkg_error(crate_name, "rustdoc JSON missing 'index' field"),
    };

    let aliases: HashMap<String, String> = HashMap::new();
    let mut functions: Vec<Function> = Vec::new();
    let mut display_types: HashSet<String> = HashSet::new();
    let mut fromstr_types: HashSet<String> = HashSet::new();
    let mut errors: Vec<String> = Vec::new();

    for (_, item) in index {
        // Only items from this crate (crate_id == 0); deps have crate_id > 0
        let crate_id = item["crate_id"].as_u64().unwrap_or(1);
        if crate_id != 0 {
            continue;
        }

        let name = item["name"].as_str().unwrap_or("").to_string();
        let inner = &item["inner"];

        // Free function — must be public
        if let Some(fn_data) = inner.get("function") {
            if is_public(item) {
                if let Some(f) = parse_fn_item(&name, fn_data, &aliases, None) {
                    functions.push(f);
                }
            }
        }

        // Impl block — includes derive-generated trait impls.
        // Impl blocks always have visibility "default" (they don't have their
        // own visibility in Rust — it's inherited from the type), so we must
        // NOT filter by is_public() here.
        // The self type is under "for" (NOT "for_") in the rustdoc JSON.
        if let Some(impl_data) = inner.get("impl") {
            // "for" is a Rust keyword but JSON keys can be anything.
            let for_val = impl_data.get("for").or_else(|| impl_data.get("for_"));
            let self_sky = for_val
                .map(|v| rustdoc_type_to_sky(v, &aliases))
                .unwrap_or_default();
            let self_rust = for_val
                .map(|v| rustdoc_type_to_rust_str(v))
                .unwrap_or_default();

            if self_sky.is_empty() {
                continue;
            }

            // Track Display / FromStr for synthetic bridge functions
            let trait_name = impl_data
                .get("trait")
                .and_then(|t| t.as_object())
                .and_then(|t| t.get("name").or_else(|| t.get("path")))
                .and_then(|n| n.as_str())
                .unwrap_or("");
            if trait_name == "Display" || trait_name.ends_with("::Display") {
                display_types.insert(self_sky.clone());
            }
            if trait_name == "FromStr" || trait_name.ends_with("::FromStr") {
                fromstr_types.insert(self_sky.clone());
            }

            // Walk method items.
            // Item IDs may be integers (new format) or strings (old format).
            if let Some(items) = impl_data["items"].as_array() {
                for method_id in items {
                    let id = item_id_to_str(method_id);
                    if let Some(method_item) = index.get(&id) {
                        if !is_public(method_item) {
                            continue;
                        }
                        let method_name = method_item["name"].as_str().unwrap_or("");
                        if let Some(fn_data) = method_item["inner"].get("function") {
                            if let Some(f) =
                                parse_fn_item(method_name, fn_data, &aliases, Some((&self_sky, &self_rust)))
                            {
                                functions.push(f);
                            }
                        }
                    }
                }
            }
        }
    }

    // Synthetic to_string / from_string bridge functions (Display/FromStr)
    emit_display_fromstr_bridges(&mut functions, &display_types, &fromstr_types);

    if functions.is_empty() && !errors.is_empty() {
        // surface errors visibly
        errors.insert(0, format!("{}: 0 functions extracted", crate_name));
    }

    PkgInfo {
        pkg: crate_name.to_string(),
        name: crate_name.to_string(),
        version: version.to_string(),
        functions,
        errors,
    }
}

fn is_public(item: &serde_json::Value) -> bool {
    item["visibility"].as_str() == Some("public")
}

/// Parse a function item from the rustdoc JSON index.
///
/// `recv` is `Some((sky_type, rust_type))` for methods, `None` for free fns.
fn parse_fn_item(
    name: &str,
    fn_data: &serde_json::Value,
    aliases: &HashMap<String, String>,
    recv: Option<(&str, &str)>,
) -> Option<Function> {
    // Signature is under "sig" (format v38+) or "decl" (earlier).
    let sig = fn_data.get("sig").or_else(|| fn_data.get("decl"))?;

    let inputs = sig["inputs"].as_array()?;
    let output = &sig["output"];

    let is_async = fn_data["header"]["is_async"].as_bool().unwrap_or(false)
        || fn_data["header"]["async_"].as_bool().unwrap_or(false);

    // Skip generic functions — type parameters can't be resolved without
    // a concrete call site.  This matches the previous syn-based behaviour.
    if let Some(params) = fn_data["generics"]["params"].as_array() {
        if !params.is_empty() {
            return None;
        }
    }

    let mut params: Vec<Param> = Vec::new();

    // Receiver param for methods
    if let Some((sky_ty, rust_ty)) = recv {
        params.push(Param {
            name: "self".into(),
            ty: sky_ty.to_string(),
            sky_type: sky_ty.to_string(),
            rust_type: rust_ty.to_string(),
        });
    }

    // Ordinary parameters: inputs is [(name, type_json)]
    for input in inputs {
        let param_name = input[0].as_str().unwrap_or("_");
        let type_json = &input[1];
        let sky = rustdoc_type_to_sky(type_json, aliases);
        let rust = rustdoc_type_to_rust_str(type_json);
        params.push(Param {
            name: param_name.to_string(),
            ty: sky.clone(),
            sky_type: sky,
            rust_type: rust,
        });
    }

    // Return type
    let mut results: Vec<Param> = Vec::new();
    if !output.is_null() {
        let sky = rustdoc_type_to_sky(output, aliases);
        let rust = rustdoc_type_to_rust_str(output);
        if sky != "()" {
            results.push(Param {
                name: String::new(),
                ty: sky.clone(),
                sky_type: sky,
                rust_type: rust,
            });
        }
    }

    let effect = classify_effect(output, &params, is_async);
    let (recv_sky, recv_rust) = recv.unwrap_or(("", ""));

    Some(Function {
        name: name.to_string(),
        params,
        results,
        variadic: false,
        effect,
        exported: true,
        recv_type: recv_sky.to_string(),
        recv_rust_type: recv_rust.to_string(),
        method_name: if recv.is_some() { name.to_string() } else { String::new() },
        is_field: false,
        is_field_set: false,
        is_pkg_var: false,
    })
}

fn classify_effect(
    output: &serde_json::Value,
    _params: &[Param],
    is_async: bool,
) -> String {
    if is_async {
        return "effectful".into();
    }
    if is_future_type(output) {
        return "effectful".into();
    }
    let sky = rustdoc_type_to_sky(output, &HashMap::new());
    if sky.starts_with("Result ") {
        return "fallible".into();
    }
    if sky.starts_with("Task ") {
        return "effectful".into();
    }
    "pure".into()
}

fn is_future_type(val: &serde_json::Value) -> bool {
    if let Some(rp) = val.get("resolved_path") {
        let n = rp["name"].as_str().unwrap_or("");
        if n == "Pin" || n == "Future" || n == "BoxFuture" {
            return true;
        }
    }
    false
}

// ── Synthetic bridge functions ─────────────────────────────────────────

fn emit_display_fromstr_bridges(
    functions: &mut Vec<Function>,
    display_types: &HashSet<String>,
    fromstr_types: &HashSet<String>,
) {
    for ty in display_types {
        functions.push(Function {
            name: "to_string".into(),
            params: vec![Param {
                name: "self".into(),
                ty: ty.clone(),
                sky_type: ty.clone(),
                rust_type: ty.clone(),
            }],
            results: vec![Param {
                name: String::new(),
                ty: "String".into(),
                sky_type: "String".into(),
                rust_type: String::new(),
            }],
            variadic: false,
            effect: "pure".into(),
            exported: true,
            recv_type: ty.clone(),
            recv_rust_type: ty.clone(),
            method_name: "to_string".into(),
            is_field: false,
            is_field_set: false,
            is_pkg_var: false,
        });
    }

    for ty in fromstr_types {
        functions.push(Function {
            name: "from_string".into(),
            params: vec![Param {
                name: "s".into(),
                ty: "String".into(),
                sky_type: "String".into(),
                rust_type: "&str".into(),
            }],
            results: vec![Param {
                name: String::new(),
                ty: ty.clone(),
                sky_type: ty.clone(),
                rust_type: ty.clone(),
            }],
            variadic: false,
            effect: "fallible".into(),
            exported: true,
            recv_type: ty.clone(),
            recv_rust_type: ty.clone(),
            method_name: "from_string".into(),
            is_field: false,
            is_field_set: false,
            is_pkg_var: false,
        });
    }
}

// ── rustdoc JSON type → Sky type string ───────────────────────────────
//
// The rustdoc JSON represents Rust types as tagged JSON objects.  The
// tag names have been stable across format versions 28–38+.  We
// gracefully fall back to "String" for unknown shapes rather than
// crashing, so format version drift degrades gracefully.

fn rustdoc_type_to_sky(val: &serde_json::Value, aliases: &HashMap<String, String>) -> String {
    if val.is_null() {
        return "()".to_string();
    }

    // { "primitive": "bool" | "usize" | "str" | … }
    if let Some(prim) = val.get("primitive") {
        return type_str_to_sky(prim.as_str().unwrap_or(""), aliases);
    }

    // { "borrowed_ref": { "type_": … } }  →  strip the reference
    if let Some(inner) = val.get("borrowed_ref") {
        return rustdoc_type_to_sky(&inner["type_"], aliases);
    }

    // { "raw_pointer": { "type_": … } }
    if let Some(inner) = val.get("raw_pointer") {
        return rustdoc_type_to_sky(&inner["type_"], aliases);
    }

    // { "resolved_path": { "name": "Vec", "args": { "angle_bracketed": … } } }
    if let Some(rp) = val.get("resolved_path") {
        return resolve_path_to_sky(rp, aliases);
    }

    // { "tuple": [type, …] }
    if let Some(items) = val.get("tuple") {
        let parts: Vec<String> = items
            .as_array()
            .map(|arr| {
                arr.iter()
                    .map(|t| rustdoc_type_to_sky(t, aliases))
                    .collect()
            })
            .unwrap_or_default();
        return if parts.is_empty() {
            "()".to_string()
        } else {
            format!("({})", parts.join(", "))
        };
    }

    // { "slice": type }  →  List T
    if let Some(inner) = val.get("slice") {
        return format!("List {}", rustdoc_type_to_sky(inner, aliases));
    }

    // { "array": { "type_": …, "len": "N" } }
    if let Some(arr) = val.get("array") {
        let inner = rustdoc_type_to_sky(&arr["type_"], aliases);
        // [u8; N] → Bytes, other fixed arrays → List T
        return if inner == "Int" {
            "Bytes".to_string()
        } else {
            format!("List {}", inner)
        };
    }

    // { "generic": "T" }  — unresolved type parameter
    if let Some(g) = val.get("generic") {
        return g.as_str().unwrap_or("String").to_string();
    }

    // impl Trait / dyn Trait — opaque
    if val.get("impl_trait").is_some() || val.get("dyn_trait").is_some() {
        return "String".to_string();
    }

    // Associated type path
    if let Some(qp) = val.get("qualified_path") {
        let name = qp["name"].as_str().unwrap_or("");
        return name.to_string();
    }

    "String".to_string()
}

fn resolve_path_to_sky(rp: &serde_json::Value, aliases: &HashMap<String, String>) -> String {
    // "name" (format <35) or "path" (format 35+) — try both
    let name = rp["name"]
        .as_str()
        .or_else(|| rp["path"].as_str())
        .unwrap_or("");
    let args = extract_angle_type_args(rp.get("args"), aliases);

    match name {
        "Vec" => format!(
            "List {}",
            args.first().cloned().unwrap_or_else(|| "String".into())
        ),
        "Option" => format!(
            "Maybe {}",
            args.first().cloned().unwrap_or_else(|| "String".into())
        ),
        "Box" | "Arc" | "Rc" | "Mutex" | "RwLock" | "Cell" | "RefCell" => {
            args.first().cloned().unwrap_or_else(|| name.to_string())
        }
        "String" | "str" | "OsStr" | "OsString" | "PathBuf" | "Path" => "String".to_string(),
        "HashMap" | "BTreeMap" | "IndexMap" | "AHashMap" => {
            let val = args.get(1).cloned().unwrap_or_else(|| "String".into());
            format!("Dict String {}", val)
        }
        "Result" => {
            // Rust Result<T, E>  →  Sky Result E T
            let ok = args.first().cloned().unwrap_or_else(|| "()".into());
            let err = args.get(1).cloned().unwrap_or_else(|| "String".into());
            format!("Result {} {}", err, ok)
        }
        "SkyResult" => {
            // SkyResult<E, A>  →  Result E A
            let err = args.first().cloned().unwrap_or_else(|| "String".into());
            let ok = args.get(1).cloned().unwrap_or_else(|| "()".into());
            format!("Result {} {}", err, ok)
        }
        "SkyError" => "Error".to_string(),
        "SkyTask" => {
            let err = args.first().cloned().unwrap_or_else(|| "Error".into());
            let ok = args.get(1).cloned().unwrap_or_else(|| "()".into());
            format!("Task {} {}", err, ok)
        }
        // async / future wrappers
        "Pin" => {
            // Pin<Box<dyn Future<Output = T>>>  →  Task Error T
            // Try to extract Output from the inner Future
            args.first()
                .map(|inner| {
                    if inner.starts_with("Task ") {
                        inner.clone()
                    } else {
                        format!("Task Error {}", inner)
                    }
                })
                .unwrap_or_else(|| "Task Error ()".into())
        }
        "Future" => {
            // Extract Output = T binding
            let output = extract_binding_type(rp.get("args"), "Output", aliases)
                .unwrap_or_else(|| "()".into());
            format!("Task Error {}", output)
        }
        _ => {
            // Strip module-path qualifier: std::collections::HashMap → HashMap
            let base = name.rsplit_once("::").map(|(_, last)| last).unwrap_or(name);
            aliases.get(base).cloned().unwrap_or_else(|| base.to_string())
        }
    }
}

/// Extract angle-bracket type arguments from a rustdoc args object.
/// Each entry looks like `{ "type": <type_json> }` (or lifetime, const — skip those).
fn extract_angle_type_args(
    args: Option<&serde_json::Value>,
    aliases: &HashMap<String, String>,
) -> Vec<String> {
    args.and_then(|a| a.get("angle_bracketed"))
        .and_then(|ab| ab.get("args"))
        .and_then(|a| a.as_array())
        .map(|arr| {
            arr.iter()
                .filter_map(|arg| {
                    arg.get("type")
                        .map(|t| rustdoc_type_to_sky(t, aliases))
                })
                .collect()
        })
        .unwrap_or_default()
}

/// Extract an associated-type binding (e.g. `Output = T`) from args.
fn extract_binding_type(
    args: Option<&serde_json::Value>,
    binding_name: &str,
    aliases: &HashMap<String, String>,
) -> Option<String> {
    let bindings = args?
        .get("angle_bracketed")?
        .get("bindings")?
        .as_array()?;
    for b in bindings {
        if b["name"].as_str() == Some(binding_name) {
            // binding value is under b["binding"]["equality"] in newer formats
            if let Some(ty) = b.get("binding").and_then(|bv| bv.get("equality")) {
                return Some(rustdoc_type_to_sky(ty, aliases));
            }
            // older format: b["value"] or b["type"]
            if let Some(ty) = b.get("value").or_else(|| b.get("type")) {
                return Some(rustdoc_type_to_sky(ty, aliases));
            }
        }
    }
    None
}

// ── rustdoc JSON type → Rust type string ──────────────────────────────
//
// Used to populate the `rustType` field in the output JSON that
// FfiGen.hs reads for coercion decisions.

fn rustdoc_type_to_rust_str(val: &serde_json::Value) -> String {
    if val.is_null() {
        return "()".to_string();
    }

    if let Some(prim) = val.get("primitive") {
        return prim.as_str().unwrap_or("()").to_string();
    }

    if let Some(inner) = val.get("borrowed_ref") {
        let m = if inner["mutable"].as_bool().unwrap_or(false) {
            "mut "
        } else {
            ""
        };
        let lt = inner["lifetime"]
            .as_str()
            .map(|l| format!("'{} ", l))
            .unwrap_or_default();
        return format!("&{}{}{}", lt, m, rustdoc_type_to_rust_str(&inner["type_"]));
    }

    if let Some(inner) = val.get("raw_pointer") {
        let m = if inner["mutable"].as_bool().unwrap_or(false) {
            "mut"
        } else {
            "const"
        };
        return format!("*{} {}", m, rustdoc_type_to_rust_str(&inner["type_"]));
    }

    if let Some(rp) = val.get("resolved_path") {
        let name = rp["name"]
            .as_str()
            .or_else(|| rp["path"].as_str())
            .unwrap_or("");
        let args: Vec<String> = rp
            .get("args")
            .and_then(|a| a.get("angle_bracketed"))
            .and_then(|ab| ab.get("args"))
            .and_then(|a| a.as_array())
            .map(|arr| {
                arr.iter()
                    .filter_map(|arg| {
                        if let Some(t) = arg.get("type") {
                            Some(rustdoc_type_to_rust_str(t))
                        } else if let Some(l) = arg.get("lifetime") {
                            Some(format!("'{}", l.as_str().unwrap_or("a")))
                        } else {
                            None
                        }
                    })
                    .collect()
            })
            .unwrap_or_default();
        return if args.is_empty() {
            name.to_string()
        } else {
            format!("{}<{}>", name, args.join(", "))
        };
    }

    if let Some(items) = val.get("tuple") {
        let parts: Vec<String> = items
            .as_array()
            .map(|arr| arr.iter().map(|t| rustdoc_type_to_rust_str(t)).collect())
            .unwrap_or_default();
        return format!("({})", parts.join(", "));
    }

    if let Some(inner) = val.get("slice") {
        return format!("[{}]", rustdoc_type_to_rust_str(inner));
    }

    if let Some(arr) = val.get("array") {
        let len = arr["len"].as_str().unwrap_or("?");
        return format!("[{}; {}]", rustdoc_type_to_rust_str(&arr["type_"]), len);
    }

    if let Some(g) = val.get("generic") {
        return g.as_str().unwrap_or("_").to_string();
    }

    String::new()
}

// ── String-based type mapping (for primitives) ─────────────────────────

fn type_str_to_sky(s: &str, aliases: &HashMap<String, String>) -> String {
    let s = s.trim();

    if let Some(sky) = aliases.get(s) {
        return sky.clone();
    }

    match s {
        "str" | "String" | "OsStr" | "OsString" | "CStr" | "CString" => "String".into(),
        "bool" => "Bool".into(),
        "()" => "()".into(),
        "i8" | "i16" | "i32" | "i64" | "i128" | "isize" | "u8" | "u16" | "u32" | "u64"
        | "u128" | "usize" => "Int".into(),
        "f32" | "f64" => "Float".into(),
        "SkyError" | "Error" => "Error".into(),
        _ => {
            // Strip module path
            let base = s.rsplit_once("::").map(|(_, l)| l).unwrap_or(s);
            let base = base.split('<').next().unwrap_or(base).trim();
            if base.is_empty() {
                return "String".into();
            }
            // Lowercase primitive names
            match base {
                "string" | "str" => "String".into(),
                "bool" => "Bool".into(),
                "int" | "integer" => "Int".into(),
                "float" => "Float".into(),
                _ => base.to_string(),
            }
        }
    }
}

// ── Helpers ────────────────────────────────────────────────────────────

/// Convert a rustdoc item ID to a string key for index lookups.
/// Item IDs appear as integers in new format (35+) and strings in old format.
fn item_id_to_str(id: &serde_json::Value) -> String {
    if let Some(n) = id.as_u64() {
        return n.to_string();
    }
    id.as_str().unwrap_or("").to_string()
}

fn pkg_error(name: &str, msg: &str) -> PkgInfo {
    PkgInfo {
        pkg: name.into(),
        name: name.into(),
        version: String::new(),
        functions: vec![],
        errors: vec![msg.into()],
    }
}

/// Split a comma-separated generic arg list respecting nested `<>` and `()`.
#[allow(dead_code)]
fn split_top_level(s: &str, sep: char) -> Vec<&str> {
    let mut result = Vec::new();
    let mut depth = 0i32;
    let mut start = 0;
    for (i, c) in s.char_indices() {
        match c {
            '<' | '(' => depth += 1,
            '>' | ')' => depth -= 1,
            _ if depth == 0 && c == sep => {
                result.push(s[start..i].trim());
                start = i + 1;
            }
            _ => {}
        }
    }
    if start < s.len() {
        result.push(s[start..].trim());
    }
    result
}

// ── Tests ──────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    fn sky(val: &serde_json::Value) -> String {
        rustdoc_type_to_sky(val, &HashMap::new())
    }

    fn prim(s: &str) -> serde_json::Value {
        serde_json::json!({ "primitive": s })
    }

    fn path(name: &str) -> serde_json::Value {
        // Use both "name" and "path" to cover old and new format versions.
        serde_json::json!({ "resolved_path": { "name": name, "path": name, "id": 0, "args": null } })
    }

    fn path_with_args(name: &str, args: Vec<serde_json::Value>) -> serde_json::Value {
        let type_args: Vec<serde_json::Value> = args
            .into_iter()
            .map(|t| serde_json::json!({ "type": t }))
            .collect();
        serde_json::json!({
            "resolved_path": {
                "name": name,
                "path": name,
                "id": 0,
                "args": {
                    "angle_bracketed": {
                        "args": type_args,
                        "bindings": []
                    }
                }
            }
        })
    }

    fn borrowed(inner: serde_json::Value) -> serde_json::Value {
        serde_json::json!({ "borrowed_ref": { "lifetime": null, "mutable": false, "type_": inner } })
    }

    #[test]
    fn test_primitives() {
        assert_eq!(sky(&prim("u64")), "Int");
        assert_eq!(sky(&prim("usize")), "Int");
        assert_eq!(sky(&prim("i32")), "Int");
        assert_eq!(sky(&prim("f32")), "Float");
        assert_eq!(sky(&prim("bool")), "Bool");
        assert_eq!(sky(&prim("str")), "String");
    }

    #[test]
    fn test_string_path() {
        assert_eq!(sky(&path("String")), "String");
        assert_eq!(sky(&path("OsString")), "String");
    }

    #[test]
    fn test_generic_containers() {
        assert_eq!(sky(&path_with_args("Vec", vec![prim("u64")])), "List Int");
        assert_eq!(
            sky(&path_with_args("Option", vec![path("String")])),
            "Maybe String"
        );
        assert_eq!(
            sky(&path_with_args("HashMap", vec![path("String"), prim("u64")])),
            "Dict String Int"
        );
    }

    #[test]
    fn test_result_and_sky_result() {
        // Rust Result<String, SkyError>  →  Sky Result Error String
        let r = path_with_args("Result", vec![path("String"), path("SkyError")]);
        assert_eq!(sky(&r), "Result Error String");

        // SkyResult<SkyError, String>  →  Sky Result Error String
        let sr = path_with_args("SkyResult", vec![path("SkyError"), path("String")]);
        assert_eq!(sky(&sr), "Result Error String");
    }

    #[test]
    fn test_borrowed_ref_stripped() {
        // &str → String
        assert_eq!(sky(&borrowed(prim("str"))), "String");
        // &Vec<u64> → List Int
        assert_eq!(
            sky(&borrowed(path_with_args("Vec", vec![prim("u64")]))),
            "List Int"
        );
    }
}
