-- | Rust-target project codegen orchestration: emit main.rs + module files,
-- copy the runtime, write Cargo.toml, copy FFI bindings. Extracted from the
-- Compile.hs `TargetRust` branch (plus the Rust-only helpers `generateRust`
-- and `copyRustRuntime`) so upstream's Go-codegen block in Compile.hs stays
-- minimally wrapped and merges cleanly. Dependency is one-way: Compile.hs
-- imports this module, never the reverse.
module Sky.Generate.Rust.Project
    ( generateRustProject
    , generateRust
    , copyRustRuntime
    ) where

import qualified Data.Map.Strict as Map
import qualified Data.Char as Char
import Control.Monad (when)
import System.Directory
    ( createDirectoryIfMissing, doesFileExist, doesDirectoryExist
    , copyFile, getCurrentDirectory, listDirectory )
import qualified System.Directory
import qualified System.Environment
import System.FilePath ((</>), takeDirectory, takeExtension)

import qualified Sky.AST.Source as Src
import qualified Sky.AST.Canonical as Can
import qualified Sky.Sky.ModuleName as ModuleName
import qualified Sky.Type.Solve as Solve
import qualified Sky.Generate.Rust.Builder as RustBuilder
import qualified Sky.Sky.Toml as Toml


-- | Orchestrate Rust-target codegen for the whole program. `rawAliases` is the
-- contents of Compile.hs's global kernel-alias IORef (read by the caller and
-- passed in to avoid depending on that module-global here).
generateRustProject
    :: Toml.SkyConfig
    -> [Can.Module]                                                -- ^ all modules (entry : deps)
    -> Src.Module                                                  -- ^ entry source module
    -> Solve.SolvedTypes
    -> Map.Map (ModuleName.Canonical, String) (String, String)     -- ^ raw kernel aliases
    -> FilePath                                                    -- ^ output dir
    -> String                                                      -- ^ source hash
    -> IO (Either String FilePath)
generateRustProject config allMods entrySrcMod typesWithDeps rawAliases outDir srcHash = do
    let dbUrl = case Toml._dbDriver config of
            "sqlite" -> "sqlite:" ++ Toml._dbPath config ++ "?mode=rwc"
            _        -> Toml._dbPath config
        dbDriver = if null (Toml._dbDriver config) then "sqlite" else Toml._dbDriver config
        -- Derive a Rust-valid module name from the dep name.
        -- Replaces non-alphanumeric (including hyphens) with _.
        depToIdent = map (\c -> if Char.isAlphaNum c then c else '_')
        depSlugs = [ depToIdent (fst dep) ++ "_bindings"
                   | dep <- Toml._rustDeps config ]
        ffiSlugs = depSlugs
        kernelAliases = Map.mapKeys (\(cn, fn) -> (ModuleName._name cn, fn)) rawAliases
        (rustCode, moduleFiles, usage) = generateRust allMods entrySrcMod typesWithDeps dbUrl dbDriver ffiSlugs kernelAliases
        rustDir = outDir </> "Rust"
    createDirectoryIfMissing True rustDir
    let srcDir = rustDir </> "src"
        mainRustPath = srcDir </> "main.rs"
        cargoTomlPath = rustDir </> "Cargo.toml"
    createDirectoryIfMissing True srcDir
    copyRustRuntime outDir
    let configPath = srcDir </> "sky_runtime" </> "config.rs"
        usesDb = RustBuilder.usesDb usage
        dbPool = RustBuilder.dbPoolType dbDriver
        dbRow = RustBuilder.dbRowType dbDriver
        configCode = unlines
            ([ "// GENERATED by Sky compiler — do not edit" ] ++
             (if usesDb
              then [ "pub type DbPool = " ++ dbPool ++ ";"
                   , "pub type DbRow = " ++ dbRow ++ ";"
                   , "pub const SKY_DB_URL: &str = " ++ show dbUrl ++ ";"
                   ]
              else [ "// (no DB)" ]))
    writeFile configPath configCode
    putStrLn $ "   Wrote " ++ configPath
    let modPath = srcDir </> "sky_runtime" </> "mod.rs"
        baseMods = ["// GENERATED by Sky compiler — do not edit"
                   ,"pub mod config;","pub mod core;","pub mod task;"
                   ,"pub mod log;","pub mod system;","pub mod time;"
                   ,"pub mod random;","pub mod file;","pub mod crypto;"
                   ,"pub mod json;"
                   -- Sub-project A — stdlib kernel modules (sub-A.1, A.2, A.4, A.6)
                   ,"pub mod encoding;","pub mod regex_kernel;","pub mod jwt;"
                   ,"pub mod decimal;"
                   -- Sub-A codegen completion — Ffi.* runtime polyfills
                   ,"pub mod ffi_polyfills;"
                   -- Sub-A.8 — runtime kernel coverage
                   ,"pub mod money;","pub mod math;","pub mod dict;"]
        dbMod = if usesDb then ["pub mod db;"] else []
        baseUse = ["pub use config::*;","pub use core::*;"
                  ,"pub use task::*;","pub use log::*;"
                  ,"pub use system::*;","pub use time::*;"
                  ,"pub use random::*;","pub use file::*;"
                  ,"pub use crypto::*;","pub use json::*;"
                  ,"pub use encoding::*;","pub use regex_kernel::*;"
                  ,"pub use jwt::*;","pub use decimal::*;"
                  ,"pub use ffi_polyfills::*;"
                  ,"pub use money::*;","pub use math::*;"
                  ,"pub use dict::*;"]
        dbUse = if usesDb then ["pub use db::*;"] else []
        modCode = unlines (baseMods ++ dbMod ++ baseUse ++ dbUse)
    writeFile modPath modCode
    putStrLn $ "   Wrote " ++ modPath
    writeFile mainRustPath rustCode
    putStrLn $ "   Wrote " ++ mainRustPath
    mapM_ (\(modName, modContent) -> do
        let modPath' = srcDir </> modName ++ ".rs"
        writeFile modPath' modContent
        putStrLn $ "   Wrote " ++ modPath'
        ) moduleFiles
    let sqlxTls = Toml._sqlxTls config
        rustDeps = Toml._rustDeps config
    writeFile cargoTomlPath (RustBuilder.emitCargoToml usage dbDriver sqlxTls rustDeps)
    putStrLn $ "   Wrote " ++ cargoTomlPath
    -- Copy Rust FFI binding files into sky-out/Rust/src/
    -- Slugs must match what generateBindings writes (via slugify).
    mapM_ (\(depName, _) -> do
        let fileSlug = map (\c -> if c `elem` ("./" :: String) then '_' else c) depName
            modSlug  = map (\c -> if Char.isAlphaNum c then c else '_') depName
            srcPath' = ".skycache/ffi/rust" </> fileSlug ++ "_bindings.rs"
            dstPath' = srcDir </> modSlug ++ "_bindings.rs"
        exists <- doesFileExist srcPath'
        when exists $ do
            copyFile srcPath' dstPath'
            putStrLn $ "   Copied " ++ srcPath'
        ) (Toml._rustDeps config)
    let cacheDir = ".skycache"
    createDirectoryIfMissing True cacheDir
    writeFile (cacheDir </> "source.hash") srcHash
    putStrLn "Compilation successful"
    return (Right mainRustPath)


-- | Run the Rust code generator over the whole canonicalised program.
generateRust :: [Can.Module] -> Src.Module -> Solve.SolvedTypes
    -> String -> String -> [String]
    -> Map.Map (String, String) (String, String)  -- kernel alias map (keys as strings)
    -> (String, [(String, String)], RustBuilder.UsedKernels)
generateRust canMods _srcMod solvedTypes dbPath dbDriver ffiSlugs kernelAliases =
    -- v0.15: Solve.SolvedTypes became a record; the Rust codegen (RustBuilder)
    -- consumes the bare env map, so project the `_stEnv` field out.
    let builder = RustBuilder.buildProgram canMods (Solve._stEnv solvedTypes) kernelAliases
        (code, moduleFiles) = RustBuilder.emitRust builder dbPath dbDriver ffiSlugs
        usage = RustBuilder.builderKernels builder
    in (code, moduleFiles, usage)


-- | Copy the Rust sky_runtime module into sky-out/Rust/src/sky_runtime/
-- so `mod sky_runtime; use sky_runtime::*;` resolves at compile time.
copyRustRuntime :: FilePath -> IO ()
copyRustRuntime outDir = do
    let targetDir = outDir </> "Rust" </> "src" </> "sky_runtime"
    createDirectoryIfMissing True targetDir
    exePath <- System.Environment.getExecutablePath
    -- Walk up from the exe directory looking for runtime-rust/src/sky_runtime/
    let dir = takeDirectory exePath
        walkUp d = do
            let candidate = d </> "runtime-rust" </> "src" </> "sky_runtime"
            ok <- doesDirectoryExist candidate
            if ok then return (Just candidate) else
                if takeDirectory d == d then return Nothing  -- reached filesystem root
                else walkUp (takeDirectory d)
    mSrcDir <- walkUp dir
    case mSrcDir of
        Nothing -> do
            -- Fallback: walk up from CWD to find the repo root
            cwd <- getCurrentDirectory
            let walkUpFromCwd d = do
                    let candidate = d </> "runtime-rust" </> "src" </> "sky_runtime"
                    ok <- doesDirectoryExist candidate
                    if ok then return (Just candidate)
                    else if takeDirectory d == d then return Nothing
                    else walkUpFromCwd (takeDirectory d)
            mCwdSrc <- walkUpFromCwd cwd
            case mCwdSrc of
                Just srcDir -> do
                    files <- listDirectory srcDir
                    let rsFiles = filter (\f -> takeExtension f == ".rs") files
                    mapM_ (\name -> copyFile (srcDir </> name) (targetDir </> name)) rsFiles
                    putStrLn $ "   Copied runtime-rust/src/sky_runtime/ (" ++ show (length rsFiles) ++ " files)"
                Nothing -> putStrLn "  [warn] could not locate runtime-rust/src/sky_runtime/"
        Just srcDir -> do
            files <- listDirectory srcDir
            let rsFiles = filter (\f -> takeExtension f == ".rs") files
            mapM_ (\name -> copyFile (srcDir </> name) (targetDir </> name)) rsFiles
            putStrLn $ "   Copied runtime-rust/src/sky_runtime/ (" ++ show (length rsFiles) ++ " files)"
