-- | Rust-target project codegen orchestration: emit main.rs + module files,
-- copy the runtime, write Cargo.toml, copy FFI bindings. Extracted from the
-- Compile.hs `TargetRust` branch (plus the Rust-only helpers `generateRust`
-- and `copyRustRuntime`) so upstream's Go-codegen block in Compile.hs stays
-- minimally wrapped and merges cleanly. Dependency is one-way: Compile.hs
-- imports this module, never the reverse.
module Sky.Generate.Rust.Project
    ( generateRustProject
    , generateRust
    , copyRustRuntime
    ) where

import qualified Data.Map.Strict as Map
import qualified Data.Char as Char
import Data.List (isInfixOf)
import Control.Monad (when)
import System.Directory
    ( createDirectoryIfMissing, doesFileExist, doesDirectoryExist
    , copyFile, getCurrentDirectory, listDirectory )
import qualified System.Directory
import qualified System.Environment
import System.FilePath ((</>), takeDirectory, takeExtension)

import qualified Sky.AST.Source as Src
import qualified Sky.AST.Canonical as Can
import qualified Sky.Sky.ModuleName as ModuleName
import qualified Sky.Type.Solve as Solve
import qualified Sky.Generate.Rust.Builder as RustBuilder
import qualified Sky.Sky.Toml as Toml


-- | Orchestrate Rust-target codegen for the whole program. `rawAliases` is the
-- contents of Compile.hs's global kernel-alias IORef (read by the caller and
-- passed in to avoid depending on that module-global here).
generateRustProject
    :: Toml.SkyConfig
    -> [Can.Module]                                                -- ^ all modules (entry : deps)
    -> Src.Module                                                  -- ^ entry source module
    -> Solve.SolvedTypes
    -> Map.Map (ModuleName.Canonical, String) (String, String)     -- ^ raw kernel aliases
    -> FilePath                                                    -- ^ output dir
    -> String                                                      -- ^ source hash
    -> IO (Either String FilePath)
generateRustProject config allMods entrySrcMod typesWithDeps rawAliases outDir srcHash = do
    let dbUrl = case Toml._dbDriver config of
            "sqlite" -> "sqlite:" ++ Toml._dbPath config ++ "?mode=rwc"
            _        -> Toml._dbPath config
        dbDriver = if null (Toml._dbDriver config) then "sqlite" else Toml._dbDriver config
        -- Derive a Rust-valid module name from the dep name.
        -- Replaces non-alphanumeric (including hyphens) with _.
        depToIdent = map (\c -> if Char.isAlphaNum c then c else '_')
        depSlugs = [ depToIdent (fst dep) ++ "_bindings"
                   | dep <- Toml._rustDeps config ]
        ffiSlugs = depSlugs
        kernelAliases = Map.mapKeys (\(cn, fn) -> (ModuleName._name cn, fn)) rawAliases
        (rustCode, moduleFiles, usage0) = generateRust allMods entrySrcMod typesWithDeps dbUrl dbDriver ffiSlugs kernelAliases (Toml._liveStore config) (Toml._liveStorePath config)
        -- usesUuid is detected from Sky-module usage (Uuid.*), but a transitive
        -- reference can slip past it: importing Sky.Core.Pure emits its whole
        -- module incl. uuidV4/uuidV7 bindings that call the uuid_v4/uuid_v7
        -- kernels, even when the app only used Pure.systemArgs. The emitted Rust
        -- then references the kernel while usesUuid stays false → undefined
        -- (35-composite-generics). Scan the final emitted code for the kernel
        -- references and force the gate (pulls uuid_kernel + the uuid crate).
        -- An app that FFIs the uuid crate itself never emits the bare
        -- `uuid_v4`/`uuid_v7` kernel name, so this can't false-trigger it.
        allEmitted = rustCode ++ concatMap snd moduleFiles
        uuidReferenced = "uuid_v4" `isInfixOf` allEmitted || "uuid_v7" `isInfixOf` allEmitted
        usage = usage0 { RustBuilder.usesUuid = RustBuilder.usesUuid usage0 || uuidReferenced }
        rustDir = outDir </> "Rust"
    createDirectoryIfMissing True rustDir
    let srcDir = rustDir </> "src"
        mainRustPath = srcDir </> "main.rs"
        cargoTomlPath = rustDir </> "Cargo.toml"
    createDirectoryIfMissing True srcDir
    copyRustRuntime outDir
    let configPath = srcDir </> "sky_runtime" </> "config.rs"
        usesDb = RustBuilder.usesDb usage
        dbPool = RustBuilder.dbPoolType dbDriver
        dbRow = RustBuilder.dbRowType dbDriver
        configCode = unlines
            ([ "// GENERATED by Sky compiler — do not edit" ] ++
             (if usesDb
              then [ "pub type DbPool = " ++ dbPool ++ ";"
                   , "pub type DbRow = " ++ dbRow ++ ";"
                   , "pub const SKY_DB_URL: &str = " ++ show dbUrl ++ ";"
                   , ""
                   -- sub-B.1: driver-specific helpers so db.rs stays backend-agnostic
                   ] ++ RustBuilder.dbBackendHelpers dbDriver
              else [ "// (no DB)" ]))
    writeFile configPath configCode
    putStrLn $ "   Wrote " ++ configPath
    let modPath = srcDir </> "sky_runtime" </> "mod.rs"
        baseMods = ["// GENERATED by Sky compiler — do not edit"
                   ,"pub mod config;","pub mod core;","pub mod task;"
                   ,"pub mod log;","pub mod trace;","pub mod system;","pub mod time;"
                   ,"pub mod random;","pub mod file;","pub mod crypto;"
                   ,"pub mod json;"
                   -- Sub-project A — stdlib kernel modules (sub-A.1, A.2, A.4, A.6)
                   ,"pub mod encoding;","pub mod regex_kernel;","pub mod jwt;"
                   ,"pub mod decimal;"
                   -- Sub-A codegen completion — Ffi.* runtime polyfills
                   ,"pub mod ffi_polyfills;"
                   -- Sub-A.8 — runtime kernel coverage
                   ,"pub mod money;","pub mod math;","pub mod dict;","pub mod string;"
                   ,"pub mod basics;","pub mod char_kernel;","pub mod list;","pub mod io;"
                   -- v0.15.47 stdlib modules
                   ,"pub mod compression;","pub mod csv;","pub mod config_decode;"
                   -- Std.Cache — pure-std LRU+TTL, no external dep (always declared)
                   ,"pub mod cache;"]
        -- sub-C — Std.Auth requires db.rs + jwt; gated together
        dbMod = if usesDb then ["pub mod db;", "pub mod auth;"] else []
        baseUse = ["pub use config::*;","pub use core::*;"
                  ,"pub use task::*;","pub use log::*;","pub use trace::*;"
                  ,"pub use system::*;","pub use time::*;"
                  ,"pub use random::*;","pub use file::*;"
                  ,"pub use crypto::*;","pub use json::*;"
                  ,"pub use encoding::*;","pub use regex_kernel::*;"
                  ,"pub use jwt::*;","pub use decimal::*;"
                  ,"pub use ffi_polyfills::*;"
                  ,"pub use money::*;","pub use math::*;"
                  ,"pub use dict::*;","pub use string::*;"
                  ,"pub use basics::*;","pub use char_kernel::*;","pub use list::*;"
                  ,"pub use io::*;"
                  ,"pub use compression::*;","pub use csv::*;"
                  ,"pub use config_decode::*;","pub use cache::*;"]
        dbUse = if usesDb then ["pub use db::*;", "pub use auth::*;"] else []
        -- uuid_kernel only when Sky.Core.Uuid is used — it needs the uuid crate
        -- with v4+v7; including it unconditionally clashes with projects that
        -- FFI the uuid crate themselves with different features (e.g. 04-uuid).
        uuidMod = if RustBuilder.usesUuid usage then ["pub mod uuid_kernel;"] else []
        uuidUse = if RustBuilder.usesUuid usage then ["pub use uuid_kernel::*;"] else []
        -- Sub-D.1: Sky.Http.Server only when used (pulls axum at step 4).
        srvMod = if RustBuilder.usesHttpServer usage then ["pub mod server;", "pub mod server_stream;"] else []
        srvUse = if RustBuilder.usesHttpServer usage then ["pub use server::*;", "pub use server_stream::*;"] else []
        -- Sky.Core.Http client only when used (pulls reqwest). http_stream rides
        -- along — it shares the reqwest dep + the HttpRequest bridge struct.
        httpMod = if RustBuilder.usesHttp usage then ["pub mod http_client;", "pub mod http_stream;"] else []
        httpUse = if RustBuilder.usesHttp usage then ["pub use http_client::*;", "pub use http_stream::*;"] else []
        -- Std.Email only when used (pulls reqwest; mirrors http_client).
        emailMod = if RustBuilder.usesEmail usage then ["pub mod email;"] else []
        emailUse = if RustBuilder.usesEmail usage then ["pub use email::*;"] else []
        -- Sub-E: TEA (Cmd/Sub/Cli.program) only when used. Std.Live's live/mod.rs
        -- imports SkyCmd/SkySub from tea, so usesLive pulls tea too.
        teaMod = if RustBuilder.usesTea usage || RustBuilder.usesLive usage then ["pub mod tea;"] else []
        teaUse = if RustBuilder.usesTea usage || RustBuilder.usesLive usage then ["pub use tea::*;"] else []
        -- Sky.Core.WebSocket client only when used (pulls tokio-tungstenite).
        wscMod = if RustBuilder.usesWsClient usage then ["pub mod ws_client;"] else []
        wscUse = if RustBuilder.usesWsClient usage then ["pub use ws_client::*;"] else []
        -- Std.Html / Std.Ui render surface — the standalone, PURE `html` module
        -- (Html/Attribute/Event ADTs + render_html + htmlXxx kernels). A non-Live
        -- CLI/Tui app that renders via Html.toString needs ONLY this, no server,
        -- no tea, no tokio. The live module (below) re-exports from it, so Live
        -- apps pull it too. Declared before live so live's re-export resolves.
        htmlMod = if RustBuilder.usesHtml usage || RustBuilder.usesLive usage then ["pub mod html;"] else []
        htmlUse = if RustBuilder.usesHtml usage || RustBuilder.usesLive usage then ["pub use html::*;"] else []
        -- Std.Live only when used — live submodule (the Sky.Live server).
        liveMod = if RustBuilder.usesLive usage then ["pub mod live;"] else []
        liveUse = if RustBuilder.usesLive usage then ["pub use live::*;"] else []
        -- Std.Tui — terminal backend (pulls crossterm). Only when used.
        tuiMod = if RustBuilder.usesTui usage then ["pub mod tui;"] else []
        tuiUse = if RustBuilder.usesTui usage then ["pub use tui::tui_app;"] else []
        modCode = unlines (baseMods ++ dbMod ++ uuidMod ++ srvMod ++ httpMod ++ emailMod ++ teaMod ++ wscMod ++ htmlMod ++ liveMod ++ tuiMod ++ baseUse ++ dbUse ++ uuidUse ++ srvUse ++ httpUse ++ emailUse ++ teaUse ++ wscUse ++ htmlUse ++ liveUse ++ tuiUse)
    writeFile modPath modCode
    putStrLn $ "   Wrote " ++ modPath
    writeFile mainRustPath rustCode
    putStrLn $ "   Wrote " ++ mainRustPath
    mapM_ (\(modName, modContent) -> do
        let modPath' = srcDir </> modName ++ ".rs"
        writeFile modPath' modContent
        putStrLn $ "   Wrote " ++ modPath'
        ) moduleFiles
    let sqlxTls = Toml._sqlxTls config
        rustDeps = Toml._rustDeps config
    writeFile cargoTomlPath (RustBuilder.emitCargoToml usage dbDriver sqlxTls rustDeps (Toml._liveStore config))
    putStrLn $ "   Wrote " ++ cargoTomlPath
    -- Copy Rust FFI binding files into sky-out/Rust/src/
    -- Slugs must match what generateBindings writes (via slugify).
    mapM_ (\(depName, _) -> do
        let fileSlug = map (\c -> if c `elem` ("./" :: String) then '_' else c) depName
            modSlug  = map (\c -> if Char.isAlphaNum c then c else '_') depName
            srcPath' = ".skycache/ffi/rust" </> fileSlug ++ "_bindings.rs"
            dstPath' = srcDir </> modSlug ++ "_bindings.rs"
        exists <- doesFileExist srcPath'
        when exists $ do
            copyFile srcPath' dstPath'
            putStrLn $ "   Copied " ++ srcPath'
        ) (Toml._rustDeps config)
    let cacheDir = ".skycache"
    createDirectoryIfMissing True cacheDir
    writeFile (cacheDir </> "source.hash") srcHash
    putStrLn "Compilation successful"
    return (Right mainRustPath)


-- | Run the Rust code generator over the whole canonicalised program.
generateRust :: [Can.Module] -> Src.Module -> Solve.SolvedTypes
    -> String -> String -> [String]
    -> Map.Map (String, String) (String, String)  -- kernel alias map (keys as strings)
    -> String -> String                            -- [live] store kind + store path
    -> (String, [(String, String)], RustBuilder.UsedKernels)
generateRust canMods _srcMod solvedTypes dbPath dbDriver ffiSlugs kernelAliases liveStore liveStorePath =
    -- v0.15: Solve.SolvedTypes became a record; the Rust codegen (RustBuilder)
    -- consumes the bare env map, so project the `_stEnv` field out.
    let builder = RustBuilder.buildProgram canMods
                                            (Solve._stEnv solvedTypes)
                                            (Solve._stPerModuleEnv solvedTypes)
                                            (Solve._stRegions solvedTypes)
                                            kernelAliases
                                            liveStore
                                            liveStorePath
        (code, moduleFiles) = RustBuilder.emitRust builder dbPath dbDriver ffiSlugs
        usage = RustBuilder.builderKernels builder
    in (code, moduleFiles, usage)


-- | Copy the Rust sky_runtime module into sky-out/Rust/src/sky_runtime/
-- so `mod sky_runtime; use sky_runtime::*;` resolves at compile time.
copyRustRuntime :: FilePath -> IO ()
copyRustRuntime outDir = do
    let targetDir = outDir </> "Rust" </> "src" </> "sky_runtime"
    createDirectoryIfMissing True targetDir
    exePath <- System.Environment.getExecutablePath
    -- Walk up from the exe directory looking for runtime-rust/src/sky_runtime/
    let dir = takeDirectory exePath
        walkUp d = do
            let candidate = d </> "runtime-rust" </> "src" </> "sky_runtime"
            ok <- doesDirectoryExist candidate
            if ok then return (Just candidate) else
                if takeDirectory d == d then return Nothing  -- reached filesystem root
                else walkUp (takeDirectory d)
    mSrcDir <- walkUp dir
    case mSrcDir of
        Nothing -> do
            -- Fallback: walk up from CWD to find the repo root
            cwd <- getCurrentDirectory
            let walkUpFromCwd d = do
                    let candidate = d </> "runtime-rust" </> "src" </> "sky_runtime"
                    ok <- doesDirectoryExist candidate
                    if ok then return (Just candidate)
                    else if takeDirectory d == d then return Nothing
                    else walkUpFromCwd (takeDirectory d)
            mCwdSrc <- walkUpFromCwd cwd
            case mCwdSrc of
                Just srcDir -> do
                    copyRuntimeDir srcDir targetDir
                Nothing -> putStrLn "  [warn] could not locate runtime-rust/src/sky_runtime/"
        Just srcDir -> copyRuntimeDir srcDir targetDir

-- | Copy all .rs files from srcDir to targetDir, plus the .rs files in any
-- immediate subdirectory (e.g. live/). One level deep only — sufficient for
-- the current runtime layout; add real recursion if a deeper tree appears.
copyRuntimeDir :: FilePath -> FilePath -> IO ()
copyRuntimeDir srcDir targetDir = do
    files <- listDirectory srcDir
    let rsFiles = filter (\f -> takeExtension f == ".rs") files
    mapM_ (\name -> copyFile (srcDir </> name) (targetDir </> name)) rsFiles
    -- Candidate subdirs: entries with no extension. doesDirectoryExist below is
    -- the real discriminant (a plain extensionless file is probed then skipped).
    let subDirs = filter (\f -> takeExtension f == "") files
    subCounts <- mapM (\sub -> do
        let srcSub = srcDir </> sub
            tgtSub = targetDir </> sub
        isDir <- doesDirectoryExist srcSub
        if isDir
            then do
                createDirectoryIfMissing True tgtSub
                subFiles <- listDirectory srcSub
                -- Copy .rs sources plus non-Rust assets the runtime include_str!'s
                -- (e.g. live/client.js embedded by render_page_full).
                let subAssets = filter (\f -> takeExtension f `elem` [".rs", ".js"]) subFiles
                mapM_ (\name -> copyFile (srcSub </> name) (tgtSub </> name)) subAssets
                pure (length subAssets)
            else pure 0
        ) subDirs
    let totalFiles = length rsFiles + sum subCounts
    putStrLn $ "   Copied runtime-rust/src/sky_runtime/ (" ++ show totalFiles ++ " files)"
