-- | Core type representation for Sky's type inference.
--
-- Derivative work adapted from elm/compiler's @Type.Type@
-- (Copyright © 2012–present Evan Czaplicki, BSD-3-Clause). See
-- NOTICE.md at the repo root for the full attribution and licence
-- text.
--
-- Adapted with Sky module names and without elm/compiler's
-- `Elm.Package` qualification. Uses Union-Find variables for
-- efficient unification. Two levels: Variable (mutable, for
-- inference) and Type (immutable, canonical).
module Sky.Type.Type
    ( -- Re-exported from Canonical
      Type(..), FieldType(..), AliasType(..), Annotation(..)
      -- Solver types
    , Variable, Descriptor(..), Content(..), SuperType(..), FlatType(..)
      -- Constraints
    , Constraint(..), Expected(..), PExpected(..), Context(..), SubContext(..)
    , PContext(..), Category(..), PCategory(..)
      -- Constants
    , Region, Located
    , noMark, outermostRank
    )
    where

import qualified Data.Map.Strict as Map
import qualified Sky.Type.UnionFind as UF
import qualified Sky.Sky.ModuleName as ModuleName
import qualified Sky.Reporting.Annotation as A
import Sky.AST.Canonical (Type(..), FieldType(..), AliasType(..), Annotation(..))


-- ═══════════════════════════════════════════════════════════
-- SOLVER-LEVEL TYPES (mutable, during inference)
-- ═══════════════════════════════════════════════════════════

-- | A type variable backed by Union-Find
type Variable = UF.Point Descriptor


-- | Descriptor for a type variable
data Descriptor = Descriptor
    { _content :: !Content
    , _rank    :: {-# UNPACK #-} !Int
    , _mark    :: {-# UNPACK #-} !Int
    , _copy    :: !(Maybe Variable)
    }


-- | What a type variable resolves to
data Content
    = FlexVar !(Maybe String)                     -- unconstrained inferred variable
    | FlexSuper !SuperType !(Maybe String)        -- constrained inferred variable
    | RigidVar !String                            -- from user annotation (cannot unify with concrete)
    | RigidSuper !SuperType !String               -- constrained rigid
    | Structure !FlatType                         -- resolved concrete type
    | Alias !ModuleName.Canonical !String [(String, Variable)] !Variable  -- type alias
    | Error                                       -- error recovery


-- | Constraint categories for special types
data SuperType
    = Number        -- Int or Float
    | Comparable    -- types that support ==, <, >
    | Appendable    -- String or List a
    | CompAppend    -- String or List a where a is Comparable
    deriving (Eq, Show)


-- | Concrete type structures (flattened for efficiency)
data FlatType
    = App1 !ModuleName.Canonical !String [Variable]     -- type constructor application
    | Fun1 !Variable !Variable                          -- function type a -> b
    | EmptyRecord1                                      -- empty record {}
    | Record1 !(Map.Map String Variable) !Variable      -- record with extension var
    | Unit1                                             -- unit type ()
    | Tuple1 !Variable !Variable !(Maybe Variable)      -- 2 or 3 element tuple


instance Show FlatType where
    show _ = "<FlatType>"


-- ═══════════════════════════════════════════════════════════
-- CANONICAL-LEVEL TYPES (imported from Sky.AST.Canonical)
-- ═══════════════════════════════════════════════════════════
-- Type, FieldType, AliasType, Annotation are defined in Sky.AST.Canonical
-- and re-exported here for use by the constraint system and solver.


-- ═══════════════════════════════════════════════════════════
-- CONSTRAINTS (generated by Constrain, solved by Solve)
-- ═══════════════════════════════════════════════════════════

-- | Type constraints for the solver
data Constraint
    = CTrue                                             -- always satisfied
    | CSaveTheEnvironment                               -- sentinel: capture env
    | CEqual !Region !Category !Type !(Expected Type)   -- two types must unify
    | CLocal !Region !String !(Expected Type)            -- local variable usage
    | CForeign !Region !String !Annotation !(Expected Type) -- imported value
    | CPattern !Region !PCategory !Type !(PExpected Type)   -- pattern constraint
    | CAnd [Constraint]                                  -- conjunction
    | CArityMismatch !Region !String !Int !Int
        -- v0.17 strict-HM gate (Limitation #7 close path).
        -- Fields: source region; binding name (for diagnostic);
        -- declared arity D; supplied arity S. Emitted by the
        -- gate when a call site's arity disagrees with the
        -- declared binding shape (e.g. `Uuid.v4 ()` when
        -- `Uuid.v4 : String` — D=0, S=1). PR-A scaffolds the
        -- constructor + solver arm + count; PR-B-D wire callers.
    | CLet                                               -- let binding
        { _rigidVars  :: [Variable]
        , _flexVars   :: [Variable]
        , _header     :: Map.Map String (Located Type)
        , _headerCon  :: Constraint
        , _bodyCon    :: Constraint
        }


-- | What was expected (for error messages)
data Expected a
    = NoExpectation a
    | FromContext !Region !Context a
    | FromAnnotation !String !Int !SubContext a
    deriving (Show)


-- | Pattern expectation
data PExpected a
    = PNoExpectation a
    | PFromContext !Region !PContext a
    deriving (Show)


-- | Context for error reporting
data Context
    = ListEntry !Int
    | Negate
    | OpLeft !String
    | OpRight !String
    | IfCondition
    | IfBranch !Int
    | CaseBranch !Int
    | CallArity !Int !Int
    | CallArg !String !Int
    | RecordAccess !String !String
    | RecordUpdate !String !String
    | Destructure
    deriving (Show)


data SubContext
    = TypedIfBranch !Int
    | TypedCaseBranch !Int
    | TypedBody
    deriving (Show)


data PContext
    = PTypedArg !String !Int
    | PCaseMatch
    | PCtorArg !String !Int
    | PListEntry !Int
    | PTail
    deriving (Show)


-- | Error category
data Category
    = CList
    | CNumber
    | CFloat
    | CString
    | CChar
    | CIf
    | CCase
    | CRecord
    | CAccess !String
    | CLambda
    | CApp
    | CCustom !String
    deriving (Show)


data PCategory
    = PCRecord
    | PCUnit
    | PCTuple
    | PCList
    | PCCtor !String
    | PCInt
    | PCFloat
    | PCChar
    | PCString
    | PCBool
    deriving (Show)


-- Annotation is imported from Sky.AST.Canonical


-- | Sentinel mark values
noMark :: Int
noMark = 0

outermostRank :: Int
outermostRank = 0


-- Use the same Region type as the annotation module
type Region = A.Region
type Located a = (Region, a)
