module Sky.Generate.Rust.Builder.Kernel
  ( kernelToRust
  , kernelSigPrefix
  , splitKernelName
  ) where

import Data.List (isPrefixOf)
import Sky.Generate.Rust.Builder.Naming (toSnakeCase)

-- | Split a Sky kernel-name like "Decimal_fromInt" into ("Decimal", "fromInt").
-- The FIRST underscore is the module/fn boundary; subsequent underscores
-- stay in the function name ("Decimal_toStringFixed" -> ("Decimal", "toStringFixed")).
-- Used by the Ffi.callPure peephole to feed kernelToRust.
splitKernelName :: String -> (String, String)
splitKernelName s = case break (== '_') s of
    (m, '_' : f) -> (m, f)
    (m, "")      -> (m, "")  -- malformed; kernelToRust returns the snake-cased default

-- | Normalise a kernel module name to the underscore prefix knownDefSig keys
-- on. Short names ("List") get the "Sky_Core_" prefix; dotted names
-- ("Sky.Core.List") just swap dots for underscores.
kernelSigPrefix :: String -> String
kernelSigPrefix m
    | '.' `elem` m = map (\c -> if c == '.' then '_' else c) m
    | otherwise    = "Sky_Core_" ++ m

-- | Map a Sky kernel (module, name) pair to its Rust runtime function name.
-- This is the single source of truth for kernel-to-Rust routing.
kernelToRust :: String -> String -> String
kernelToRust mod name = case (mod, name) of
    -- List functions (Q3)
    ("List", "map") -> "list_map_consume"
    ("Sky.Core.List", "map") -> "list_map_consume"
    ("List", "foldl") -> "list_foldl"
    ("Sky.Core.List", "foldl") -> "list_foldl"
    ("List", "foldr") -> "list_foldr"
    ("Sky.Core.List", "foldr") -> "list_foldr"
    ("List", "range") -> "list_range"
    ("Sky.Core.List", "range") -> "list_range"
    ("List", "indexedMap") -> "list_indexed_map"
    ("Sky.Core.List", "indexedMap") -> "list_indexed_map"
    ("List", "concatMap") -> "list_concat_map"
    ("Sky.Core.List", "concatMap") -> "list_concat_map"
    ("List", "zip") -> "list_zip"
    ("Sky.Core.List", "zip") -> "list_zip"
    ("List", "filter") -> "list_filter"
    ("Sky.Core.List", "filter") -> "list_filter"
    ("List", "member") -> "list_member"
    ("Sky.Core.List", "member") -> "list_member"
    ("List", "any") -> "list_any"
    ("Sky.Core.List", "any") -> "list_any"
    ("List", "all") -> "list_all"
    ("Sky.Core.List", "all") -> "list_all"
    -- String kernel functions: route directly to runtime implementations
    ("String", "fromInt") -> "string_from_int"
    ("Sky.Core.String", "fromInt") -> "string_from_int"
    ("String", "fromFloat") -> "string_from_float"
    ("Sky.Core.String", "fromFloat") -> "string_from_float"
    ("String", "length") -> "string_length"
    ("Sky.Core.String", "length") -> "string_length"
    ("String", "isEmpty") -> "string_is_empty"
    ("Sky.Core.String", "isEmpty") -> "string_is_empty"
    ("String", "reverse") -> "string_reverse"
    ("Sky.Core.String", "reverse") -> "string_reverse"
    ("String", "append") -> "string_append"
    ("Sky.Core.String", "append") -> "string_append"
    ("String", "toInt") -> "string_to_int"
    ("Sky.Core.String", "toInt") -> "string_to_int"
    ("String", "toLower") -> "string_to_lower"
    ("Sky.Core.String", "toLower") -> "string_to_lower"
    ("String", "toUpper") -> "string_to_upper"
    ("Sky.Core.String", "toUpper") -> "string_to_upper"
    ("String", "trim") -> "string_trim"
    ("Sky.Core.String", "trim") -> "string_trim"
    ("String", "split") -> "string_split"
    ("Sky.Core.String", "split") -> "string_split"
    ("String", "join") -> "string_join"
    ("Sky.Core.String", "join") -> "string_join"
    -- Encoding (sub-A.1)
    ("Encoding", "base64Encode")        -> "base64_encode"
    ("Sky.Core.Encoding", "base64Encode") -> "base64_encode"
    ("Encoding", "base64Decode")        -> "base64_decode"
    ("Sky.Core.Encoding", "base64Decode") -> "base64_decode"
    ("Encoding", "urlEncode")           -> "url_encode"
    ("Sky.Core.Encoding", "urlEncode")  -> "url_encode"
    ("Encoding", "urlDecode")           -> "url_decode"
    ("Sky.Core.Encoding", "urlDecode")  -> "url_decode"
    -- Renamed (was hex_encode/hex_decode) to avoid colliding with
    -- user-FFI bindings to the `hex` crate (examples/rust/16-hex).
    ("Encoding", "hexEncode")           -> "encoding_hex_encode"
    ("Sky.Core.Encoding", "hexEncode")  -> "encoding_hex_encode"
    ("Encoding", "hexDecode")           -> "encoding_hex_decode"
    ("Sky.Core.Encoding", "hexDecode")  -> "encoding_hex_decode"
    -- Regex (sub-A.2)
    ("Regex", "match")              -> "regex_match"
    ("Sky.Core.Regex", "match")     -> "regex_match"
    ("Regex", "find")               -> "regex_find"
    ("Sky.Core.Regex", "find")      -> "regex_find"
    ("Regex", "findAll")            -> "regex_find_all"
    ("Sky.Core.Regex", "findAll")   -> "regex_find_all"
    ("Regex", "replace")            -> "regex_replace"
    ("Sky.Core.Regex", "replace")   -> "regex_replace"
    ("Regex", "split")              -> "regex_split"
    ("Sky.Core.Regex", "split")     -> "regex_split"
    -- Crypto completion (sub-A.3) — sha256 + random* already present
    ("Crypto", "sha512")                       -> "crypto_sha512"
    ("Sky.Core.Crypto", "sha512")              -> "crypto_sha512"
    ("Crypto", "sha1")                         -> "crypto_sha1"
    ("Sky.Core.Crypto", "sha1")                -> "crypto_sha1"
    ("Crypto", "md5")                          -> "crypto_md5"
    ("Sky.Core.Crypto", "md5")                 -> "crypto_md5"
    ("Crypto", "hmacSha256")                   -> "crypto_hmac_sha256"
    ("Sky.Core.Crypto", "hmacSha256")          -> "crypto_hmac_sha256"
    ("Crypto", "hmacSha512")                   -> "crypto_hmac_sha512"
    ("Sky.Core.Crypto", "hmacSha512")          -> "crypto_hmac_sha512"
    ("Crypto", "rsaSha256Sign")                -> "crypto_rsa_sha256_sign"
    ("Sky.Core.Crypto", "rsaSha256Sign")       -> "crypto_rsa_sha256_sign"
    ("Crypto", "rsaSha256Verify")              -> "crypto_rsa_sha256_verify"
    ("Sky.Core.Crypto", "rsaSha256Verify")     -> "crypto_rsa_sha256_verify"
    ("Crypto", "constantTimeEqual")            -> "crypto_constant_time_equal"
    ("Sky.Core.Crypto", "constantTimeEqual")   -> "crypto_constant_time_equal"
    -- v0.15.44 symmetric AEAD (sub-D)
    -- Sky.Core.Uuid (String surface; v0.15.x)
    ("Uuid", "v4")                             -> "uuid_v4"
    ("Sky.Core.Uuid", "v4")                    -> "uuid_v4"
    ("Uuid", "v7")                             -> "uuid_v7"
    ("Sky.Core.Uuid", "v7")                    -> "uuid_v7"
    ("Uuid", "parse")                          -> "uuid_parse"
    ("Sky.Core.Uuid", "parse")                 -> "uuid_parse"
    ("Crypto", "aesGcmEncrypt")                -> "crypto_aes_gcm_encrypt"
    ("Sky.Core.Crypto", "aesGcmEncrypt")       -> "crypto_aes_gcm_encrypt"
    ("Crypto", "aesGcmDecrypt")                -> "crypto_aes_gcm_decrypt"
    ("Sky.Core.Crypto", "aesGcmDecrypt")       -> "crypto_aes_gcm_decrypt"
    ("Crypto", "chacha20Encrypt")              -> "crypto_chacha20_encrypt"
    ("Sky.Core.Crypto", "chacha20Encrypt")     -> "crypto_chacha20_encrypt"
    ("Crypto", "chacha20Decrypt")              -> "crypto_chacha20_decrypt"
    ("Sky.Core.Crypto", "chacha20Decrypt")     -> "crypto_chacha20_decrypt"
    ("Crypto", "aesKeyFromPassword")           -> "crypto_aes_key_from_password"
    ("Sky.Core.Crypto", "aesKeyFromPassword")  -> "crypto_aes_key_from_password"
    ("Crypto", "chachaKeyFromPassword")        -> "crypto_chacha_key_from_password"
    ("Sky.Core.Crypto", "chachaKeyFromPassword") -> "crypto_chacha_key_from_password"
    -- Std.Time advanced (sub-A.5)
    ("Time", "inZone")            -> "time_in_zone"
    ("Time", "formatInZone")      -> "time_format_in_zone"
    ("Time", "addDays")           -> "time_add_days"
    ("Time", "addHours")          -> "time_add_hours"
    ("Time", "addMinutes")        -> "time_add_minutes"
    ("Time", "addSeconds")        -> "time_add_seconds"
    ("Time", "addMonths")         -> "time_add_months"
    ("Time", "addYears")          -> "time_add_years"
    ("Time", "year")              -> "time_year"
    ("Time", "month")             -> "time_month"
    ("Time", "day")               -> "time_day"
    ("Time", "dayOfWeek")         -> "time_day_of_week"
    ("Time", "dayOfYear")         -> "time_day_of_year"
    ("Time", "weekOfYear")        -> "time_week_of_year"
    ("Time", "isWeekend")         -> "time_is_weekend"
    ("Time", "daysInMonth")       -> "time_days_in_month"
    ("Time", "isLeapYear")        -> "time_is_leap_year"
    ("Time", "startOfDay")        -> "time_start_of_day"
    ("Time", "endOfDay")          -> "time_end_of_day"
    ("Time", "startOfWeek")       -> "time_start_of_week"
    ("Time", "startOfMonth")      -> "time_start_of_month"
    ("Time", "endOfMonth")        -> "time_end_of_month"
    ("Time", "startOfYear")       -> "time_start_of_year"
    ("Time", "endOfYear")         -> "time_end_of_year"
    -- Std.Decimal (sub-A.6)
    ("Decimal", "fromString")     -> "decimal_from_string"
    ("Decimal", "fromInt")        -> "decimal_from_int"
    ("Decimal", "fromFloat")      -> "decimal_from_float"
    ("Decimal", "fromMinor")      -> "decimal_from_minor"
    ("Decimal", "zero")           -> "decimal_zero"
    ("Decimal", "one")            -> "decimal_one"
    ("Decimal", "oneHundred")     -> "decimal_one_hundred"
    ("Decimal", "toString")       -> "decimal_to_string"
    ("Decimal", "toStringFixed")  -> "decimal_to_string_fixed"
    ("Decimal", "toFloat")        -> "decimal_to_float"
    ("Decimal", "toInt")          -> "decimal_to_int"
    ("Decimal", "toMinor")        -> "decimal_to_minor"
    ("Decimal", "add")            -> "decimal_add"
    ("Decimal", "sub")            -> "decimal_sub"
    ("Decimal", "mul")            -> "decimal_mul"
    ("Decimal", "div")            -> "decimal_div"
    ("Decimal", "mod")            -> "decimal_mod"
    ("Decimal", "neg")            -> "decimal_neg"
    ("Decimal", "abs")            -> "decimal_abs"
    ("Decimal", "round")          -> "decimal_round"
    ("Decimal", "roundHalfUp")    -> "decimal_round_half_up"
    ("Decimal", "truncate")       -> "decimal_truncate"
    ("Decimal", "floor")          -> "decimal_floor"
    ("Decimal", "ceil")           -> "decimal_ceil"
    ("Decimal", "compare")        -> "decimal_compare"
    -- sub-A.8 T1 — Std.Decimal completion (15 kernels)
    ("Decimal", "eq")             -> "decimal_eq"
    ("Decimal", "neq")            -> "decimal_neq"
    ("Decimal", "lt")             -> "decimal_lt"
    ("Decimal", "lte")            -> "decimal_lte"
    ("Decimal", "gt")             -> "decimal_gt"
    ("Decimal", "gte")            -> "decimal_gte"
    ("Decimal", "min")            -> "decimal_min"
    ("Decimal", "max")            -> "decimal_max"
    ("Decimal", "isZero")         -> "decimal_is_zero"
    ("Decimal", "isPositive")     -> "decimal_is_positive"
    ("Decimal", "isNegative")     -> "decimal_is_negative"
    ("Decimal", "percentOf")      -> "decimal_percent_of"
    ("Decimal", "addPercent")     -> "decimal_add_percent"
    ("Decimal", "subPercent")     -> "decimal_sub_percent"
    ("Decimal", "formatWith")     -> "decimal_format_with"
    -- sub-A.8 T2 — Std.Money (11 kernels)
    ("Money", "format")               -> "money_format"
    ("Money", "formatWithCode")       -> "money_format_with_code"
    ("Money", "currencyName")         -> "money_currency_name"
    ("Money", "symbol")               -> "money_symbol"
    ("Money", "minorUnits")           -> "money_minor_units"
    ("Money", "isKnownCurrency")      -> "money_is_known_currency"
    ("Money", "setRate")              -> "money_set_rate"
    ("Money", "getRate")              -> "money_get_rate"
    ("Money", "hasRate")              -> "money_has_rate"
    ("Money", "clearRates")           -> "money_clear_rates"
    ("Money", "allocate")             -> "money_allocate"
    -- Sky.Core.Char (8 kernels). toLower/toUpper return a single-rune String
    -- (kernel shape Char -> String); toCode/fromCode are v0.16.7 #419.
    ("Char", "isAlpha")          -> "char_is_alpha"
    ("Sky.Core.Char", "isAlpha") -> "char_is_alpha"
    ("Char", "isDigit")          -> "char_is_digit"
    ("Sky.Core.Char", "isDigit") -> "char_is_digit"
    ("Char", "isLower")          -> "char_is_lower"
    ("Sky.Core.Char", "isLower") -> "char_is_lower"
    ("Char", "isUpper")          -> "char_is_upper"
    ("Sky.Core.Char", "isUpper") -> "char_is_upper"
    ("Char", "toLower")          -> "char_to_lower"
    ("Sky.Core.Char", "toLower") -> "char_to_lower"
    ("Char", "toUpper")          -> "char_to_upper"
    ("Sky.Core.Char", "toUpper") -> "char_to_upper"
    ("Char", "toCode")           -> "char_to_code"
    ("Sky.Core.Char", "toCode")  -> "char_to_code"
    ("Char", "fromCode")         -> "char_from_code"
    ("Sky.Core.Char", "fromCode") -> "char_from_code"
    -- sub-A.8 T3 — Sky.Core.Math (8 kernels)
    ("Math", "abs")             -> "math_abs"
    ("Sky.Core.Math", "abs")    -> "math_abs"
    ("Math", "min")             -> "math_min"
    ("Sky.Core.Math", "min")    -> "math_min"
    ("Math", "max")             -> "math_max"
    ("Sky.Core.Math", "max")    -> "math_max"
    ("Math", "sqrt")            -> "math_sqrt"
    ("Sky.Core.Math", "sqrt")   -> "math_sqrt"
    ("Math", "pow")             -> "math_pow"
    ("Sky.Core.Math", "pow")    -> "math_pow"
    ("Math", "floor")           -> "math_floor"
    ("Sky.Core.Math", "floor")  -> "math_floor"
    ("Math", "ceil")            -> "math_ceil"
    ("Sky.Core.Math", "ceil")   -> "math_ceil"
    ("Math", "round")           -> "math_round"
    ("Sky.Core.Math", "round")  -> "math_round"
    ("Math", "pi")              -> "math_pi"
    ("Sky.Core.Math", "pi")     -> "math_pi"
    ("Math", "e")               -> "math_e"
    ("Sky.Core.Math", "e")      -> "math_e"
    -- sub-A.8 T4 — Std.Time advanced (7 kernels)
    ("Time", "diffSeconds")     -> "time_diff_seconds"
    ("Time", "diffMinutes")     -> "time_diff_minutes"
    ("Time", "diffHours")       -> "time_diff_hours"
    ("Time", "diffDays")        -> "time_diff_days"
    ("Time", "fromParts")       -> "time_from_parts"
    ("Time", "zoneOffset")      -> "time_zone_offset"
    ("Time", "zoneName")        -> "time_zone_name"
    -- sub-A.8 T5 — Sky.Core.Dict (6 kernels)
    ("Dict", "empty")           -> "dict_empty"
    ("Sky.Core.Dict", "empty")  -> "dict_empty"
    ("Dict", "insert")          -> "dict_insert"
    ("Sky.Core.Dict", "insert") -> "dict_insert"
    ("Dict", "get")             -> "dict_get"
    ("Sky.Core.Dict", "get")    -> "dict_get"
    ("Dict", "keys")            -> "dict_keys"
    ("Sky.Core.Dict", "keys")   -> "dict_keys"
    ("Dict", "remove")          -> "dict_remove"
    ("Sky.Core.Dict", "remove") -> "dict_remove"
    ("Dict", "member")          -> "dict_member"
    ("Sky.Core.Dict", "member") -> "dict_member"
    ("Dict", "fromList")        -> "dict_from_list"
    ("Sky.Core.Dict", "fromList") -> "dict_from_list"
    -- sub-A.8 T6 — Sky.Core.String additions (4 kernels)
    ("String", "replace")           -> "string_replace"
    ("Sky.Core.String", "replace")  -> "string_replace"
    ("String", "startsWith")        -> "string_starts_with"
    ("Sky.Core.String", "startsWith") -> "string_starts_with"
    ("String", "endsWith")          -> "string_ends_with"
    ("Sky.Core.String", "endsWith") -> "string_ends_with"
    ("String", "repeat")            -> "string_repeat"
    ("Sky.Core.String", "repeat")   -> "string_repeat"
    -- sub-A.8 T7 — Sky.Core.Basics + List (3 kernels)
    ("Basics", "modBy")               -> "basics_mod_by"
    ("Sky.Core.Basics", "modBy")      -> "basics_mod_by"
    ("Basics", "errorToString")       -> "basics_error_to_string"
    ("Sky.Core.Basics", "errorToString") -> "basics_error_to_string"
    ("List", "filterMap")             -> "list_filter_map"
    ("Sky.Core.List", "filterMap")    -> "list_filter_map"
    -- Json.Encode kernel functions: route to runtime implementations
    ("JsonEnc", "string") -> "json_enc_string"
    ("Sky.Core.Json.Encode", "string") -> "json_enc_string"
    ("JsonEnc", "int") -> "json_enc_int"
    ("Sky.Core.Json.Encode", "int") -> "json_enc_int"
    ("JsonEnc", "float") -> "json_enc_float"
    ("Sky.Core.Json.Encode", "float") -> "json_enc_float"
    ("JsonEnc", "bool") -> "json_enc_bool"
    ("Sky.Core.Json.Encode", "bool") -> "json_enc_bool"
    ("JsonEnc", "null") -> "json_enc_null"
    ("Sky.Core.Json.Encode", "null") -> "json_enc_null"
    ("JsonEnc", "encode") -> "json_enc_encode"
    ("Sky.Core.Json.Encode", "encode") -> "json_enc_encode"
    ("JsonEnc", "list") -> "json_enc_list"
    ("Sky.Core.Json.Encode", "list") -> "json_enc_list"
    ("JsonEnc", "object") -> "json_enc_object"
    ("Sky.Core.Json.Encode", "object") -> "json_enc_object"
    -- Json.Decode kernel functions: route to runtime implementations
    ("JsonDec", "string") -> "json_dec_string"
    ("Sky.Core.Json.Decode", "string") -> "json_dec_string"
    ("JsonDec", "int") -> "json_dec_int"
    ("Sky.Core.Json.Decode", "int") -> "json_dec_int"
    ("JsonDec", "float") -> "json_dec_float"
    ("Sky.Core.Json.Decode", "float") -> "json_dec_float"
    ("JsonDec", "bool") -> "json_dec_bool"
    ("Sky.Core.Json.Decode", "bool") -> "json_dec_bool"
    ("JsonDec", "null") -> "json_dec_null"
    ("Sky.Core.Json.Decode", "null") -> "json_dec_null"
    ("JsonDec", "field") -> "json_dec_field"
    ("Sky.Core.Json.Decode", "field") -> "json_dec_field"
    ("JsonDec", "at") -> "json_dec_at"
    ("Sky.Core.Json.Decode", "at") -> "json_dec_at"
    ("JsonDec", "list") -> "json_dec_list"
    ("Sky.Core.Json.Decode", "list") -> "json_dec_list"
    ("JsonDec", "map") -> "json_dec_map"
    ("Sky.Core.Json.Decode", "map") -> "json_dec_map"
    ("JsonDec", "andThen") -> "json_dec_and_then"
    ("Sky.Core.Json.Decode", "andThen") -> "json_dec_and_then"
    ("JsonDec", "succeed") -> "json_dec_succeed"
    ("Sky.Core.Json.Decode", "succeed") -> "json_dec_succeed"
    ("JsonDec", "fail") -> "json_dec_fail"
    ("Sky.Core.Json.Decode", "fail") -> "json_dec_fail"
    ("JsonDec", "decodeString") -> "json_dec_decode_string"
    ("Sky.Core.Json.Decode", "decodeString") -> "json_dec_decode_string"
    ("JsonDec", "oneOf") -> "json_dec_one_of"
    ("Sky.Core.Json.Decode", "oneOf") -> "json_dec_one_of"
    -- Std.Config — typed TOML/YAML/JSON decoders. The `Decoder a` is the same
    -- runtime representation as Json.Decode's (Decoder<E,T> over a serde_json
    -- Value), so the pure combinators route straight to the json_dec_* kernels
    -- (which already carry their turbofish entries). Only nullable + the format
    -- front-ends (String-first arg order) + loadFromFile live in config_decode.rs.
    ("Config", "string")  -> "json_dec_string"
    ("Std.Config", "string")  -> "json_dec_string"
    ("Config", "int")     -> "json_dec_int"
    ("Std.Config", "int")     -> "json_dec_int"
    ("Config", "float")   -> "json_dec_float"
    ("Std.Config", "float")   -> "json_dec_float"
    ("Config", "bool")    -> "json_dec_bool"
    ("Std.Config", "bool")    -> "json_dec_bool"
    ("Config", "field")   -> "json_dec_field"
    ("Std.Config", "field")   -> "json_dec_field"
    ("Config", "at")      -> "json_dec_at"
    ("Std.Config", "at")      -> "json_dec_at"
    ("Config", "list")    -> "json_dec_list"
    ("Std.Config", "list")    -> "json_dec_list"
    ("Config", "map")     -> "json_dec_map"
    ("Std.Config", "map")     -> "json_dec_map"
    ("Config", "andThen") -> "json_dec_and_then"
    ("Std.Config", "andThen") -> "json_dec_and_then"
    ("Config", "succeed") -> "json_dec_succeed"
    ("Std.Config", "succeed") -> "json_dec_succeed"
    ("Config", "fail")    -> "json_dec_fail"
    ("Std.Config", "fail")    -> "json_dec_fail"
    ("Config", "nullable")     -> "config_nullable"
    ("Std.Config", "nullable")     -> "config_nullable"
    ("Config", "decodeJson")   -> "config_decode_json"
    ("Std.Config", "decodeJson")   -> "config_decode_json"
    ("Config", "decodeToml")   -> "config_decode_toml"
    ("Std.Config", "decodeToml")   -> "config_decode_toml"
    ("Config", "decodeYaml")   -> "config_decode_yaml"
    ("Std.Config", "decodeYaml")   -> "config_decode_yaml"
    ("Config", "loadFromFile") -> "config_load_from_file"
    ("Std.Config", "loadFromFile") -> "config_load_from_file"
    -- Std.Trace — opt-in spans / events / attrs (output gated on SKY_TRACE).
    -- span runs + returns the wrapped task's result unchanged.
    ("Trace", "span") -> "trace_span"
    ("Std.Trace", "span") -> "trace_span"
    ("Trace", "event") -> "trace_event"
    ("Std.Trace", "event") -> "trace_event"
    ("Trace", "attr") -> "trace_attr"
    ("Std.Trace", "attr") -> "trace_attr"
    -- Task kernel functions: route to runtime implementations
    ("Task", "succeed") -> "task_succeed"
    ("Sky.Core.Task", "succeed") -> "task_succeed"
    ("Task", "map") -> "task_map"
    ("Sky.Core.Task", "map") -> "task_map"
    ("Task", "andThen") -> "task_and_then"
    ("Sky.Core.Task", "andThen") -> "task_and_then"
    ("Task", "mapError") -> "task_map_error"
    ("Sky.Core.Task", "mapError") -> "task_map_error"
    ("Task", "onError") -> "task_on_error"
    ("Sky.Core.Task", "onError") -> "task_on_error"
    -- Task.perform : Task e a -> Result e a (runs synchronously, keeps the
    -- value). That is task_run, not task_perform (which returns a Task<()> and
    -- drops the value). sub-D fix — surfaced by the retryWith test.
    ("Task", "perform") -> "task_run"
    ("Sky.Core.Task", "perform") -> "task_run"
    ("Task", "sequence") -> "task_sequence"
    ("Sky.Core.Task", "sequence") -> "task_sequence"
    ("Task", "run") -> "task_run"
    ("Sky.Core.Task", "run") -> "task_run"
    ("Task", "parallel") -> "task_parallel"
    ("Sky.Core.Task", "parallel") -> "task_parallel"
    ("Task", "lazy") -> "task_lazy"
    ("Task", "retryWith") -> "task_retry_with"  -- sub-D: run-once (see task.rs)
    ("Sky.Core.Task", "lazy") -> "task_lazy"
    ("Task", "fail") -> "task_fail"
    ("Sky.Core.Task", "fail") -> "task_fail"
    ("Task", "fromResult") -> "task_from_result"
    ("Sky.Core.Task", "fromResult") -> "task_from_result"
    ("Task", "andThenResult") -> "task_and_then_result"
    ("Sky.Core.Task", "andThenResult") -> "task_and_then_result"
    -- Json.Decode.Pipeline
    ("JsonDecP", "required") -> "json_dec_p_required"
    ("Sky.Core.Json.Decode.Pipeline", "required") -> "json_dec_p_required"
    ("JsonDecP", "optional") -> "json_dec_p_optional"
    ("Sky.Core.Json.Decode.Pipeline", "optional") -> "json_dec_p_optional"
    -- Log kernel functions: route to runtime implementations
    ("Log", "println") -> "log_info"
    ("Std.Log", "println") -> "log_info"
    ("Log", "info") -> "log_info"
    ("Std.Log", "info") -> "log_info"
    ("Log", "debug") -> "log_debug"
    ("Std.Log", "debug") -> "log_debug"
    ("Log", "warn") -> "log_warn"
    ("Std.Log", "warn") -> "log_warn"
    ("Log", "error") -> "log_error"
    ("Std.Log", "error") -> "log_error"
    ("Log", "infoWith") -> "log_info_with"
    ("Std.Log", "infoWith") -> "log_info_with"
    ("Log", "debugWith") -> "log_debug_with"
    ("Std.Log", "debugWith") -> "log_debug_with"
    ("Log", "warnWith") -> "log_warn_with"
    ("Std.Log", "warnWith") -> "log_warn_with"
    ("Log", "errorWith") -> "log_error_with"
    ("Std.Log", "errorWith") -> "log_error_with"
    -- Db kernel functions: route to runtime implementations
    ("Db", "open") -> "db_open"
    ("Std.Db", "open") -> "db_open"
    ("Db", "connect") -> "db_connect"
    ("Std.Db", "connect") -> "db_connect"
    ("Db", "exec") -> "db_exec"
    ("Std.Db", "exec") -> "db_exec"
    ("Db", "execRaw") -> "db_exec_raw"
    ("Std.Db", "execRaw") -> "db_exec_raw"
    ("Db", "query") -> "db_query"
    ("Std.Db", "query") -> "db_query"
    ("Db", "getField") -> "db_get_field"
    ("Std.Db", "getField") -> "db_get_field"
    ("Db", "getString") -> "db_get_string"
    ("Std.Db", "getString") -> "db_get_string"
    ("Db", "getInt") -> "db_get_int"
    ("Std.Db", "getInt") -> "db_get_int"
    ("Db", "migrateApply") -> "db_migrate_apply"
    ("Std.Db", "migrateApply") -> "db_migrate_apply"
    -- sub-B: 12 missing Std.Db kernels (lifecycle + CRUD + search + tx)
    ("Db", "close")             -> "db_close"
    ("Std.Db", "close")         -> "db_close"
    ("Db", "getBool")           -> "db_get_bool"
    ("Std.Db", "getBool")       -> "db_get_bool"
    ("Db", "insertRow")         -> "db_insert_row"
    ("Std.Db", "insertRow")     -> "db_insert_row"
    ("Db", "getById")           -> "db_get_by_id"
    ("Std.Db", "getById")       -> "db_get_by_id"
    ("Db", "updateById")        -> "db_update_by_id"
    ("Std.Db", "updateById")    -> "db_update_by_id"
    ("Db", "deleteById")        -> "db_delete_by_id"
    ("Std.Db", "deleteById")    -> "db_delete_by_id"
    ("Db", "findOneByField")    -> "db_find_one_by_field"
    ("Std.Db", "findOneByField") -> "db_find_one_by_field"
    ("Db", "findManyByField")   -> "db_find_many_by_field"
    ("Std.Db", "findManyByField") -> "db_find_many_by_field"
    ("Db", "findByConditions")  -> "db_find_by_conditions"
    ("Std.Db", "findByConditions") -> "db_find_by_conditions"
    ("Db", "unsafeFindWhere")   -> "db_unsafe_find_where"
    ("Std.Db", "unsafeFindWhere") -> "db_unsafe_find_where"
    ("Db", "queryDecode")       -> "db_query_decode"
    ("Std.Db", "queryDecode")   -> "db_query_decode"
    ("Db", "withTransaction")   -> "db_with_transaction"
    ("Std.Db", "withTransaction") -> "db_with_transaction"
    -- Sub-C: Std.Auth — 6 pure crypto + 3 DB-touching kernels.
    ("Auth", "hashPassword")     -> "auth_hash_password"
    ("Std.Auth", "hashPassword") -> "auth_hash_password"
    ("Auth", "hashPasswordCost")     -> "auth_hash_password_cost"
    ("Std.Auth", "hashPasswordCost") -> "auth_hash_password_cost"
    ("Auth", "verifyPassword")     -> "auth_verify_password"
    ("Std.Auth", "verifyPassword") -> "auth_verify_password"
    ("Auth", "passwordStrength")     -> "auth_password_strength"
    ("Std.Auth", "passwordStrength") -> "auth_password_strength"
    ("Auth", "signToken")     -> "auth_sign_token"
    ("Std.Auth", "signToken") -> "auth_sign_token"
    ("Auth", "verifyToken")     -> "auth_verify_token"
    ("Std.Auth", "verifyToken") -> "auth_verify_token"
    ("Auth", "register")     -> "auth_register"
    ("Std.Auth", "register") -> "auth_register"
    ("Auth", "login")     -> "auth_login"
    ("Std.Auth", "login") -> "auth_login"
    ("Auth", "setRole")     -> "auth_set_role"
    ("Std.Auth", "setRole") -> "auth_set_role"
    -- Ffi.kernel: the codegen routes every call through the kernel dispatch,
    -- but the Rust target resolves Ffi.kernel calls directly during
    -- canonicalisation.  Any Ffi.kernel reference that reaches codegen is
    -- a polyfill call site — emit a diagnostic panic.
    -- Sub-E: TEA Cmd/Sub/Cli — map directly to the tea.rs kernels (don't rely on
    -- the Ffi.kernel-alias table, which mis-resolves in nested expr positions and
    -- would call the generated stdlib wrapper -> Ffi.kernel polyfill panic).
    ("Cmd", "none")     -> "cmd_none"
    ("Std.Cmd", "none") -> "cmd_none"
    ("Cmd", "batch")     -> "cmd_batch"
    ("Std.Cmd", "batch") -> "cmd_batch"
    ("Cmd", "perform")     -> "cmd_perform"
    ("Std.Cmd", "perform") -> "cmd_perform"
    ("Sub", "none")     -> "sub_none"
    ("Std.Sub", "none") -> "sub_none"
    ("Sub", "batch")     -> "sub_batch"
    ("Std.Sub", "batch") -> "sub_batch"
    ("Sub", "every")     -> "sub_every"
    ("Std.Sub", "every") -> "sub_every"
    ("Cmd", "publish")            -> "cmd_publish"
    ("Std.Cmd", "publish")        -> "cmd_publish"
    ("Cmd", "publishNoEcho")      -> "cmd_publish_no_echo"
    ("Std.Cmd", "publishNoEcho")  -> "cmd_publish_no_echo"
    ("Sub", "subscribeTopic")     -> "sub_subscribe_topic"
    ("Std.Sub", "subscribeTopic") -> "sub_subscribe_topic"
    ("PubSub", "publish")            -> "pubsub_publish"
    ("Std.PubSub", "publish")        -> "pubsub_publish"
    ("PubSub", "publishNoEcho")      -> "pubsub_publish_no_echo"
    ("Std.PubSub", "publishNoEcho")  -> "pubsub_publish_no_echo"
    ("Cli", "program")     -> "cli_program"
    ("Std.Cli", "program") -> "cli_program"
    -- Sky.Http.Middleware + Sky.Http.RateLimit — map both the short kernel-module
    -- form and the fully-qualified Sky module to the runtime fns (robust against
    -- the alias-table resolution path).
    ("Middleware", "withCors")              -> "middleware_with_cors"
    ("Sky.Http.Middleware", "withCors")     -> "middleware_with_cors"
    ("Middleware", "withLogging")           -> "middleware_with_logging"
    ("Sky.Http.Middleware", "withLogging")  -> "middleware_with_logging"
    ("Middleware", "withBasicAuth")             -> "middleware_with_basic_auth"
    ("Sky.Http.Middleware", "withBasicAuth")    -> "middleware_with_basic_auth"
    ("Middleware", "withRateLimit")             -> "middleware_with_rate_limit"
    ("Sky.Http.Middleware", "withRateLimit")    -> "middleware_with_rate_limit"
    ("RateLimit", "allow")            -> "rate_limit_allow"
    ("Sky.Http.RateLimit", "allow")   -> "rate_limit_allow"
    -- Std.Live — P0 scaffold kernel (bridge + render path gate).
    ("Live", "renderStatic")     -> "live_render_static"
    ("Std.Live", "renderStatic") -> "live_render_static"
    ("Live", "app")              -> "live_app"
    ("Std.Live", "app")          -> "live_app"
    ("Ffi", "kernel") -> "ffi_kernel_polyfill"
    -- Ffi.callPure / callTask / toAny: the peephole rewriter in exprToRustInner
    -- handles the common case (literal kernel name + literal args list) by
    -- emitting a direct kernel call. Non-peephole-matched references land
    -- here and route to runtime polyfills: ffi_to_any_polyfill is compile-
    -- time identity; ffi_call_pure_polyfill / ffi_call_task_polyfill panic
    -- with an actionable message. See runtime-rust/src/sky_runtime/ffi_polyfills.rs.
    ("Ffi", "callPure") -> "ffi_call_pure_polyfill"
    ("Ffi", "callTask") -> "ffi_call_task_polyfill"
    ("Ffi", "call")     -> "ffi_call_pure_polyfill"  -- deprecated alias of callPure
    ("Ffi", "toAny")    -> "ffi_to_any_polyfill"
    -- Rust user-FFI kernel: snake_case the suffix, no panic stub.
    -- The wrapper function lives in a .skycache/ffi/rust/*_bindings.rs file
    -- that gets copied into sky-out/Rust/src/ at codegen time.
    _ | "Rust_" `isPrefixOf` mod ->
        toSnakeCase (drop 5 mod ++ "_" ++ name)
    _ -> toSnakeCase (map (\c -> if c == '.' then '_' else c) mod ++ "_" ++ name)
